apiVersion: v1
kind: Service
metadata:
  name: {{ include "scm-cache.fullname" . }}-api
  labels:
    {{- include "scm-cache.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceApi.type }}
  ports:
    - port: {{ .Values.serviceApi.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "scm-cache.selectorLabels" . | nindent 4 }}
