scm:
  metadata:
    namespace: ${SCM_METADATA_NAMESPACE:local}
    instance-id: ${SCM_METADATA_INSTANCE_ID:local-scm-cm-connector}
  observation:
    log:
      console:
        enabled: true
    trace:
      console:
        enabled: true
    audit:
      console:
        enabled: true

SCM_SERVER_PORT: ${SERVER_PORT:8080}

SCM_CONFIG_ENABLED: false
SCM_CONFIG_SERVER_IMPORT: ""
SCM_CONFIG_FAIL_FAST: false

SCM_UAA_BASE_URL: http://localhost:8000

SCM_CACHE_DISTRIBUTED: true
SCM_CACHE_CLUSTER_NAME: scm-cache-dev
SCM_CACHE_ADDRESS: 127.0.0.1:5701
SCM_CM_CONNECTOR_ADMIN_CACHE_ENDPOINTS_ENABLED: false
