spring:
  cloud:
    config:
      enabled: false

SCM_ENV: dev
SCM_APPLICATION_NAME: scm-cm-connector
SCM_INSTANCE_ID: local-scm-cm-connector
SCM_SERVER_PORT: ${SERVER_PORT:8080}

SCM_UAA_BASE_URL: http://localhost:8000
SCM_UAA_ISSUER_URL: http://localhost:8000
SCM_UAA_JWK_SET_URL: http://localhost:8000/oauth2/jwks

SCM_CACHE_DISTRIBUTED: true
SCM_CACHE_CLUSTER_NAME: dev3
SCM_CACHE_ADDRESS: 127.0.0.1:5701
SCM_CM_CONNECTOR_ADMIN_CACHE_ENDPOINTS_ENABLED: false

SCM_OBS_ROOT_DIR: ${user.home}/scm/obs
SCM_OBS_LOG_CONSOLE_ENABLED: true
SCM_OBS_LOG_FILE_ENABLED: true
SCM_OBS_TRACE_FILE_ENABLED: true
SCM_OBS_AUDIT_ENABLED: false
