---
# Source: scm-uaa/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scm-uaa
  labels:
    helm.sh/chart: scm-uaa-8.5.4
    app.kubernetes.io/name: scm-uaa
    app.kubernetes.io/instance: scm-uaa
    app.kubernetes.io/version: "8.5.4"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: scm-uaa/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: scm-uaa-configmap
data:
  # Key-value pairs for your configuration
  SPRING_SECURITY_ISSUER_URI: "http://scm-uaa.scm.svc.cluster.local:8000"
---
# Source: scm-uaa/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: scm-uaa
  labels:
    helm.sh/chart: scm-uaa-8.5.4
    app.kubernetes.io/name: scm-uaa
    app.kubernetes.io/instance: scm-uaa
    app.kubernetes.io/version: "8.5.4"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  externalIPs:
    - 10.10.4.126
  selector:
    app.kubernetes.io/name: scm-uaa
    app.kubernetes.io/instance: scm-uaa
---
# Source: scm-uaa/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scm-uaa
  labels:
    helm.sh/chart: scm-uaa-8.5.4
    app.kubernetes.io/name: scm-uaa
    app.kubernetes.io/instance: scm-uaa
    app.kubernetes.io/version: "8.5.4"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scm-uaa
      app.kubernetes.io/instance: scm-uaa
  template:
    metadata:
      labels:
        helm.sh/chart: scm-uaa-8.5.4
        app.kubernetes.io/name: scm-uaa
        app.kubernetes.io/instance: scm-uaa
        app.kubernetes.io/version: "8.5.4"
        app.kubernetes.io/managed-by: Helm
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: scm-uaa
      securityContext:
        {}
      containers:
        - name: scm-uaa
          securityContext:
            {}
          image: "reg.daneshrefah.ir/modern-banking/scm-app:8.5.4"
          imagePullPolicy: IfNotPresent
          env:
            - name: JDWP_OPTS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            - name: SPRING_PROFILES_ACTIVE
              value: test
            - name: SPRING_APPLICATION_NAME
              value: scm-uaa
            - name: VERSION
              value: 8.5.4
            - name: SERVER_PORT
              value: "8000"
            - name: SPRING_CLOUD_CONFIG_URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CLOUD_CONFIG_URI
                  name: scm-config-configmap
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP




          resources:
            {}
          volumeMounts:
            - mountPath: /mnt/log
              name: log-volume
      volumes:
        - hostPath:
            path: /log
            type: DirectoryOrCreate
          name: log-volume
      nodeSelector:
        app: scm-uaa
      tolerations:
        - effect: NoSchedule
          key: daneshrefah.ir/group
          operator: Equal
          value: scm
