UPDATE REF.TBL_SCM_OPERATION_PROVIDER
SET NAME = 'hps-shetab7',
    URI = 'shetab:hps-shetab7',
    LAST_EDIT_DATE = CURRENT_TIMESTAMP
WHERE OPERATION_PROVIDER_ID IN (
    SELECT OPERATION_PROVIDER_ID
    FROM REF.TBL_SCM_OPERATION
    WHERE NAME = 'SVC_CARD_INQUIRY_TCP'
)
  AND (NAME = 'hps' OR URI = 'shetab:' || 'hps');
