CREATE TABLE REF.TBL_SCM_DEFINITION
(
    DEFINITION_ID  VARCHAR(255) NOT NULL,
    NAME           VARCHAR(100) NOT NULL ,
    CODE           VARCHAR(50) NOT NULL ,
    ENGINE         VARCHAR(20),
    DETAILS        VARCHAR(2048),
    CREATOR        VARCHAR(255),
    LAST_EDITOR    VARCHAR(255),
    CREATE_DATE    TIMESTAMP,
    LAST_EDIT_DATE TIMESTAMP,
    VERSION        INTEGER,
    CONSTRAINT PK_DEFINITION PRIMARY KEY (DEFINITION_ID)
);
ALTER TABLE REF.TBL_SCM_DEFINITION
    ADD CONSTRAINT UC_DEF_ON_CODE UNIQUE (CODE);
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REF.TBL_SCM_OPERATION_PROVIDER
(
    OPERATION_PROVIDER_ID VARCHAR(36)  NOT NULL,
    NAME                  VARCHAR(100) NOT NULL,
    CODE                  VARCHAR(50)  NOT NULL,
    URI                   VARCHAR(100) NOT NULL,
    ACTIVE                SMALLINT     NOT NULL,
    CREATOR               VARCHAR(255),
    LAST_EDITOR           VARCHAR(255),
    CREATE_DATE           TIMESTAMP,
    LAST_EDIT_DATE        TIMESTAMP,
    VERSION               INTEGER,
    CONSTRAINT PK_OPERATION_PROVIDER PRIMARY KEY (OPERATION_PROVIDER_ID)
);

ALTER TABLE REF.TBL_SCM_OPERATION_PROVIDER
    ADD CONSTRAINT UC_OPT_PVD_ON_CODE UNIQUE (code);
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REF.TBL_SCM_OPERATION
(
    OPERATION_ID          VARCHAR(36)  NOT NULL,
    NAME                  VARCHAR(100) NOT NULL,
    CODE                  VARCHAR(50)  NOT NULL,
    PATH                  VARCHAR(100),
    ACTIVE                SMALLINT     NOT NULL,
    DESCRIPTION           VARCHAR(255),
    OPERATION_TYPE        VARCHAR(20) NOT NULL,
    OPERATION_PROVIDER_ID VARCHAR(36)  NOT NULL,
    CREATOR               VARCHAR(255),
    LAST_EDITOR           VARCHAR(255),
    CREATE_DATE           TIMESTAMP,
    LAST_EDIT_DATE        TIMESTAMP,
    VERSION               INTEGER,
    CONSTRAINT PK_OPERATION PRIMARY KEY (OPERATION_ID)
);

ALTER TABLE REF.TBL_SCM_OPERATION
    ADD CONSTRAINT UC_OPT_ON_CODE UNIQUE (CODE);

ALTER TABLE REF.TBL_SCM_OPERATION
    ADD CONSTRAINT FK_OPT_ON_OPT_PVD FOREIGN KEY (OPERATION_PROVIDER_ID) REFERENCES REF.TBL_SCM_OPERATION_PROVIDER (OPERATION_PROVIDER_ID);

------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REF.TBL_SCM_OPERATION_DEF
(
    OPERATION_DEF_ID      VARCHAR(36)  NOT NULL,
    TYPE                  VARCHAR(20)  NOT NULL,
    OPERATION_ID          VARCHAR(36)  NOT NULL,
    DEFINITION_ID         VARCHAR(36)  NOT NULL,
    CREATOR               VARCHAR(255),
    LAST_EDITOR           VARCHAR(255),
    CREATE_DATE           TIMESTAMP,
    LAST_EDIT_DATE        TIMESTAMP,
    VERSION               INTEGER,
    CONSTRAINT PK_OPERATION_DEF PRIMARY KEY (OPERATION_DEF_ID)
);

ALTER TABLE REF.TBL_SCM_OPERATION_DEF
    ADD CONSTRAINT UC_OPT_DEF_ON_TYP_OPT_DEF UNIQUE (TYPE, OPERATION_ID, DEFINITION_ID);

ALTER TABLE REF.TBL_SCM_OPERATION_DEF
    ADD CONSTRAINT FK_OPT_PVD_ON_OPT FOREIGN KEY (OPERATION_ID) REFERENCES REF.TBL_SCM_OPERATION (OPERATION_ID);

ALTER TABLE REF.TBL_SCM_OPERATION_DEF
    ADD CONSTRAINT FK_OPT_PVD_ON_DEF FOREIGN KEY (DEFINITION_ID) REFERENCES REF.TBL_SCM_DEFINITION (DEFINITION_ID);
------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REF.TBL_SCM_PLUGIN
(
    PLUGIN_ID      VARCHAR(36)  NOT NULL,
    NAME           VARCHAR(100) NOT NULL,
    TYPE           VARCHAR(20)  NOT NULL,
    DESCRIPTION    VARCHAR(255),
    DEFINITION_ID  VARCHAR(255),
    CREATOR        VARCHAR(255),
    LAST_EDITOR    VARCHAR(255),
    CREATE_DATE    TIMESTAMP,
    LAST_EDIT_DATE TIMESTAMP,
    VERSION        INTEGER,
    CONSTRAINT PK_PLUGIN PRIMARY KEY (PLUGIN_ID)
);

ALTER TABLE REF.TBL_SCM_PLUGIN
    ADD CONSTRAINT FK_PLG_ON_DEF FOREIGN KEY (DEFINITION_ID) REFERENCES REF.TBL_SCM_DEFINITION (DEFINITION_ID);

------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REF.TBL_SCM_PLUGIN_BINDING
(
    PLUGIN_BINDING_ID VARCHAR(36) NOT NULL,
    PLUGIN_ID         VARCHAR(36) NOT NULL,
    SCOPE             VARCHAR(20) NOT NULL,
    SCOPE_ID          VARCHAR(36) NOT NULL,
    ORDER             SMALLINT    NOT NULL,
    PHASE             VARCHAR(20) NOT NULL,
    ACTIVE            SMALLINT    NOT NULL,
    DEFINITION_ID     VARCHAR(255),
    CREATOR           VARCHAR(255),
    LAST_EDITOR       VARCHAR(255),
    CREATE_DATE       TIMESTAMP,
    LAST_EDIT_DATE    TIMESTAMP,
    VERSION           INTEGER,
    CONSTRAINT PK_PLUGIN_BINDING PRIMARY KEY (PLUGIN_BINDING_ID)
);

ALTER TABLE REF.TBL_SCM_PLUGIN_BINDING
    ADD CONSTRAINT UC_PLG_BND_ON_PLG_SCP UNIQUE (PLUGIN_ID, SCOPE, SCOPE_ID);

ALTER TABLE REF.TBL_SCM_PLUGIN_BINDING
    ADD CONSTRAINT FK_PLG_ON_DEF FOREIGN KEY (DEFINITION_ID) REFERENCES REF.TBL_SCM_DEFINITION (DEFINITION_ID);

ALTER TABLE REF.TBL_SCM_PLUGIN_BINDING
    ADD CONSTRAINT FK_PLG_BND_ON_PLG FOREIGN KEY (PLUGIN_ID) REFERENCES REF.TBL_SCM_PLUGIN (PLUGIN_ID);

------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REF.TBL_SCM_GATEWAY_CHANNEL
(
    GATEWAY_CHANNEL_ID VARCHAR(36)  NOT NULL,
    NAME               VARCHAR(100) NOT NULL,
    CODE               VARCHAR(50)  NOT NULL,
    ACTIVE             SMALLINT     NOT NULL,
    DESCRIPTION        VARCHAR(255),
    CHANNEL_ID         SMALLINT     NOT NULL,
    PROTOCOL_TYPE      VARCHAR(20)  NOT NULL,
    HOST               VARCHAR(50),
    PORT               SMALLINT,
    PATH               VARCHAR(100),
    METADATA           VARCHAR(2048),
    CREATOR            VARCHAR(255),
    LAST_EDITOR        VARCHAR(255),
    CREATE_DATE        TIMESTAMP,
    LAST_EDIT_DATE     TIMESTAMP,
    VERSION            INTEGER,
    CONSTRAINT PK_GATEWAY_CHANNEL PRIMARY KEY (GATEWAY_CHANNEL_ID)
);

ALTER TABLE REF.TBL_SCM_GATEWAY_CHANNEL
    ADD CONSTRAINT UC_GTW_CHN_ON_PTC_CHN UNIQUE (CHANNEL_ID, PROTOCOL_TYPE);

ALTER TABLE REF.TBL_SCM_GATEWAY_CHANNEL
    ADD CONSTRAINT UC_GATEWAY_CHANNEL_CODE UNIQUE (CODE);

ALTER TABLE REF.TBL_SCM_GATEWAY_CHANNEL
    ADD CONSTRAINT FK_GTW_CHN_ON_CHN FOREIGN KEY (CHANNEL_ID) REFERENCES REF.CHANNEL (CHANNEL_ID);

------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REF.TBL_SCM_CHANNEL_SERVICE_DEF
(
    CHANNEL_SERVICE_DEF_ID    VARCHAR(36) NOT NULL,
    CHANNEL_SERVICE_ACCESS_ID BIGINT      NOT NULL,
    GATEWAY_CHANNEL_CODE      VARCHAR(50) NOT NULL,
    TYPE                      VARCHAR(20) NOT NULL,
    METADATA                  VARCHAR(2048),
    CREATOR                   VARCHAR(255),
    LAST_EDITOR               VARCHAR(255),
    CREATE_DATE               TIMESTAMP,
    LAST_EDIT_DATE            TIMESTAMP,
    VERSION                   INTEGER,
    CONSTRAINT PK_CHANNEL_SERVICE_DEF PRIMARY KEY (CHANNEL_SERVICE_DEF_ID)
);

ALTER TABLE REF.TBL_SCM_CHANNEL_SERVICE_DEF
    ADD CONSTRAINT UC_GTW_ON_PTC_CHN UNIQUE (CHANNEL_SERVICE_ACCESS_ID, GATEWAY_CHANNEL_CODE, TYPE);

ALTER TABLE REF.TBL_SCM_CHANNEL_SERVICE_DEF
    ADD CONSTRAINT FK_CHN_SVC_DEF_ON_CHN_SVC FOREIGN KEY (CHANNEL_SERVICE_ACCESS_ID) REFERENCES REF.CHANNEL_SERVICE_ACCESS (CHANNEL_SERVICE_ACCESS_ID);

------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REF.TBL_SCM_SERVICE_OPERATION
(
    SERVICE_OPERATION_ID VARCHAR(36) NOT NULL,
    ACTIVE               SMALLINT    NOT NULL,
    EB_SERVICE_ID        SMALLINT    NOT NULL,
    OPERATION_CODE       VARCHAR(50) NOT NULL,
    METADATA             VARCHAR(2048),
    CREATOR              VARCHAR(255),
    LAST_EDITOR          VARCHAR(255),
    CREATE_DATE          TIMESTAMP,
    LAST_EDIT_DATE       TIMESTAMP,
    VERSION              INTEGER,
    CONSTRAINT PK_SERVICE_OPERATION PRIMARY KEY (SERVICE_OPERATION_ID)
);

ALTER TABLE REF.TBL_SCM_SERVICE_OPERATION
    ADD CONSTRAINT UC_GTW_OPT_ON_SVC_OPT UNIQUE (EB_SERVICE_ID, OPERATION_CODE);

ALTER TABLE REF.TBL_SCM_SERVICE_OPERATION
    ADD CONSTRAINT FK_GTW_OPT_ON_SVC FOREIGN KEY (EB_SERVICE_ID) REFERENCES REF.EB_SERVICE (EB_SERVICE_ID);

------------------------------------------------------------------------------------------------------------------------
alter table REF.TBL_SCM_ERROR_MAPPING
    add VERSION INTEGER;

------------------------------------------------------------------------------------------------------------------------
alter table REF.TBL_SCM_SERVICE_PROVIDER
    add VERSION INTEGER;

------------------------------------------------------------------------------------------------------------------------
alter table REF.TBL_SCM_SERVICE_RESPONSE_CONDITION
    add VERSION INTEGER;

------------------------------------------------------------------------------------------------------------------------
alter table REF.TBL_SCM_PARAMETERS
    add VERSION INTEGER;

------------------------------------------------------------------------------------------------------------------------
alter table REF.TBL_SCM_DATASOURCE_CONDITION
    add VERSION INTEGER;

------------------------------------------------------------------------------------------------------------------------
alter table REF.EB_SERVICE
    add ROUTING_STRATEGY VARCHAR(20);

------------------------------------------------------------------------------------------------------------------------
alter table REF.EB_SERVICE
    add METADATA VARCHAR(2048);
