CREATE TABLE REF.TBL_SCM_DEFINITION
(
    DEFINITION_ID  VARCHAR(36)  NOT NULL,
    TITLE          VARCHAR(100) NOT NULL,
    NAME           VARCHAR(50)  NOT NULL,
    ENGINE         VARCHAR(20),
    DETAILS        VARCHAR(2048),
    CREATOR        INTEGER DEFAULT 0,
    LAST_EDITOR    INTEGER DEFAULT 0,
    CREATE_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERSION        INTEGER DEFAULT 0,
    CONSTRAINT PK_DEFINITION PRIMARY KEY (DEFINITION_ID)
);
ALTER TABLE REF.TBL_SCM_DEFINITION
    ADD CONSTRAINT UC_DEF_ON_NAME UNIQUE (NAME);

------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REF.TBL_SCM_OPERATION_PROVIDER
(
    OPERATION_PROVIDER_ID VARCHAR(36)  NOT NULL,
    TITLE                 VARCHAR(100) NOT NULL,
    NAME                  VARCHAR(50)  NOT NULL,
    URI                   VARCHAR(100) NOT NULL,
    ACTIVE                SMALLINT     NOT NULL,
    CREATOR        INTEGER DEFAULT 0,
    LAST_EDITOR    INTEGER DEFAULT 0,
    CREATE_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERSION        INTEGER DEFAULT 0,
    CONSTRAINT PK_OPERATION_PROVIDER PRIMARY KEY (OPERATION_PROVIDER_ID)
);

ALTER TABLE REF.TBL_SCM_OPERATION_PROVIDER
    ADD CONSTRAINT UC_OPT_PVD_ON_NAME UNIQUE (NAME);

------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REF.TBL_SCM_OPERATION
(
    OPERATION_ID          VARCHAR(36)  NOT NULL,
    TITLE                 VARCHAR(100) NOT NULL,
    NAME                  VARCHAR(50)  NOT NULL,
    PATH                  VARCHAR(100),
    ACTIVE                SMALLINT     NOT NULL,
    DESCRIPTION           VARCHAR(255),
    TYPE                  VARCHAR(20)  NOT NULL,
    OPERATION_PROVIDER_ID VARCHAR(36)  NOT NULL,
    CREATOR        INTEGER DEFAULT 0,
    LAST_EDITOR    INTEGER DEFAULT 0,
    CREATE_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERSION        INTEGER DEFAULT 0,
    CONSTRAINT PK_OPERATION PRIMARY KEY (OPERATION_ID)
);

ALTER TABLE REF.TBL_SCM_OPERATION
    ADD CONSTRAINT UC_OPT_ON_NAME UNIQUE (NAME);

ALTER TABLE REF.TBL_SCM_OPERATION
    ADD CONSTRAINT FK_OPT_ON_OPT_PVD FOREIGN KEY (OPERATION_PROVIDER_ID) REFERENCES REF.TBL_SCM_OPERATION_PROVIDER (OPERATION_PROVIDER_ID);

------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REF.TBL_SCM_OPERATION_DEFINITION
(
    OPERATION_DEFINITION_ID VARCHAR(36) NOT NULL,
    TYPE                    VARCHAR(20) NOT NULL,
    OPERATION_ID            VARCHAR(36) NOT NULL,
    DEFINITION_ID           VARCHAR(36) NOT NULL,
    CREATOR        INTEGER DEFAULT 0,
    LAST_EDITOR    INTEGER DEFAULT 0,
    CREATE_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERSION        INTEGER DEFAULT 0,
    CONSTRAINT PK_OPERATION_DEFINITION PRIMARY KEY (OPERATION_DEFINITION_ID)
);

ALTER TABLE REF.TBL_SCM_OPERATION_DEFINITION
    ADD CONSTRAINT UC_OPT_DEF_ON_OPT_DEF_TYP UNIQUE (OPERATION_ID, DEFINITION_ID, TYPE);

ALTER TABLE REF.TBL_SCM_OPERATION_DEFINITION
    ADD CONSTRAINT FK_OPT_PVD_ON_DEF FOREIGN KEY (DEFINITION_ID) REFERENCES REF.TBL_SCM_DEFINITION (DEFINITION_ID);

ALTER TABLE REF.TBL_SCM_OPERATION_DEFINITION
    ADD CONSTRAINT FK_OPT_PVD_ON_OPT FOREIGN KEY (OPERATION_ID) REFERENCES REF.TBL_SCM_OPERATION (OPERATION_ID);

------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REF.TBL_SCM_PLUGIN_BINDING
(
    PLUGIN_BINDING_ID VARCHAR(36) NOT NULL,
    SCOPE             VARCHAR(20) NOT NULL,
    SCOPE_ID          VARCHAR(36) NOT NULL,
    ACTIVE            SMALLINT    NOT NULL,
    DEFINITION_ID     VARCHAR(36),
    CREATOR        INTEGER DEFAULT 0,
    LAST_EDITOR    INTEGER DEFAULT 0,
    CREATE_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERSION        INTEGER DEFAULT 0,
    CONSTRAINT PK_PLUGIN_BINDING PRIMARY KEY (PLUGIN_BINDING_ID)
);

ALTER TABLE REF.TBL_SCM_PLUGIN_BINDING
    ADD CONSTRAINT UC_PLG_BND_ON_SCP UNIQUE (SCOPE, SCOPE_ID);

ALTER TABLE REF.TBL_SCM_PLUGIN_BINDING
    ADD CONSTRAINT FK_PLG_ON_DEF FOREIGN KEY (DEFINITION_ID) REFERENCES REF.TBL_SCM_DEFINITION (DEFINITION_ID);

------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REF.TBL_SCM_GATEWAY_CHANNEL
(
    GATEWAY_CHANNEL_ID VARCHAR(36)  NOT NULL,
    TITLE              VARCHAR(100) NOT NULL,
    NAME               VARCHAR(50)  NOT NULL,
    ACTIVE             SMALLINT     NOT NULL,
    DESCRIPTION        VARCHAR(255),
    CHANNEL_ID         SMALLINT     NOT NULL,
    PROTOCOL_TYPE      VARCHAR(20)  NOT NULL,
    HOST               VARCHAR(50),
    PORT               SMALLINT,
    PATH               VARCHAR(100),
    CREATOR        INTEGER DEFAULT 0,
    LAST_EDITOR    INTEGER DEFAULT 0,
    CREATE_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERSION        INTEGER DEFAULT 0,
    CONSTRAINT PK_GATEWAY_CHANNEL PRIMARY KEY (GATEWAY_CHANNEL_ID)
);

ALTER TABLE REF.TBL_SCM_GATEWAY_CHANNEL
    ADD CONSTRAINT UC_GTW_CHN_ON_PTC_CHN UNIQUE (CHANNEL_ID, PROTOCOL_TYPE);

ALTER TABLE REF.TBL_SCM_GATEWAY_CHANNEL
    ADD CONSTRAINT UC_GTW_CHN_ON_NAME UNIQUE (NAME);

ALTER TABLE REF.TBL_SCM_GATEWAY_CHANNEL
    ADD CONSTRAINT FK_GTW_CHN_ON_CHN FOREIGN KEY (CHANNEL_ID) REFERENCES REF.CHANNEL (CHANNEL_ID);

------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REF.TBL_SCM_CHN_SVC_DEFINITION
(
    CHN_SVC_DEFINITION_ID     VARCHAR(36) NOT NULL,
    CHANNEL_SERVICE_ACCESS_ID DECIMAL(22) NOT NULL,
    GATEWAY_CHANNEL_ID        VARCHAR(36) NOT NULL,
    TYPE                      VARCHAR(20) NOT NULL,
    DEFINITION_ID             VARCHAR(36) NOT NULL,
    CREATOR        INTEGER DEFAULT 0,
    LAST_EDITOR    INTEGER DEFAULT 0,
    CREATE_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERSION        INTEGER DEFAULT 0,
    CONSTRAINT PK_CHN_SVC_DEFINITION PRIMARY KEY (CHN_SVC_DEFINITION_ID)
);

ALTER TABLE REF.TBL_SCM_CHN_SVC_DEFINITION
    ADD CONSTRAINT UC_GTW_ON_PTC_CHN UNIQUE (CHANNEL_SERVICE_ACCESS_ID, GATEWAY_CHANNEL_ID, TYPE);

ALTER TABLE REF.TBL_SCM_CHN_SVC_DEFINITION
    ADD CONSTRAINT FK_CHN_SVC_DEF_ON_CHN_SVC FOREIGN KEY (CHANNEL_SERVICE_ACCESS_ID) REFERENCES REF.CHANNEL_SERVICE_ACCESS (CHANNEL_SERVICE_ACCESS_ID);

ALTER TABLE REF.TBL_SCM_CHN_SVC_DEFINITION
    ADD CONSTRAINT FK_CHN_SVC_DEF_ON_DEF FOREIGN KEY (DEFINITION_ID) REFERENCES REF.TBL_SCM_DEFINITION (DEFINITION_ID);

ALTER TABLE REF.TBL_SCM_CHN_SVC_DEFINITION
    ADD CONSTRAINT FK_CHN_SVC_DEF_ON_GTW_CHN FOREIGN KEY (GATEWAY_CHANNEL_ID) REFERENCES REF.TBL_SCM_GATEWAY_CHANNEL (GATEWAY_CHANNEL_ID);

------------------------------------------------------------------------------------------------------------------------
CREATE TABLE REF.TBL_SCM_SERVICE_OPERATION
(
    SERVICE_OPERATION_ID VARCHAR(36) NOT NULL,
    EB_SERVICE_ID        SMALLINT    NOT NULL,
    OPERATION_NAME       VARCHAR(50) NOT NULL,
    DEFINITION_ID        VARCHAR(255),
    ACTIVE               SMALLINT    NOT NULL,
    CREATOR        INTEGER DEFAULT 0,
    LAST_EDITOR    INTEGER DEFAULT 0,
    CREATE_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERSION        INTEGER DEFAULT 0,

    CONSTRAINT PK_SERVICE_OPERATION PRIMARY KEY (SERVICE_OPERATION_ID)
);

ALTER TABLE REF.TBL_SCM_SERVICE_OPERATION
    ADD CONSTRAINT UC_GTW_OPT_ON_SVC_OPT UNIQUE (EB_SERVICE_ID, OPERATION_NAME);

ALTER TABLE REF.TBL_SCM_SERVICE_OPERATION
    ADD CONSTRAINT FK_GTW_OPT_ON_DEF FOREIGN KEY (DEFINITION_ID) REFERENCES REF.TBL_SCM_DEFINITION (DEFINITION_ID);

ALTER TABLE REF.TBL_SCM_SERVICE_OPERATION
    ADD CONSTRAINT FK_GTW_OPT_ON_SVC FOREIGN KEY (EB_SERVICE_ID) REFERENCES REF.EB_SERVICE (EB_SERVICE_ID);

------------------------------------------------------------------------------------------------------------------------
alter table REF.TBL_SCM_ERROR_MAPPING
    add VERSION INTEGER NOT NULL DEFAULT 0;

------------------------------------------------------------------------------------------------------------------------
alter table REF.TBL_SCM_SERVICE_PROVIDER
    add VERSION INTEGER  NOT NULL DEFAULT 0;

------------------------------------------------------------------------------------------------------------------------
alter table REF.TBL_SCM_SERVICE_RESPONSE_CONDITION
    add VERSION INTEGER  NOT NULL DEFAULT 0;

------------------------------------------------------------------------------------------------------------------------
alter table REF.TBL_SCM_PARAMETERS
    add VERSION  INTEGER NOT NULL DEFAULT 0;

------------------------------------------------------------------------------------------------------------------------
alter table REF.TBL_SCM_DATASOURCE_CONDITION
    add VERSION INTEGER NOT NULL DEFAULT 0;

------------------------------------------------------------------------------------------------------------------------
alter table REF.EB_SERVICE
    add ROUTING_STRATEGY VARCHAR(20);
