package ir.daneshrefah.scm.common.constant;

import ir.daneshrefah.scm.common.model.service.ServiceImplementationType;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ServiceCode {


    /**
     * Use this type as NULL
     * Set NULL status for accept database status, by selecting another status
     * system automatically ignore database status
     *
     */
    NULL(null),
    /* JAVA SERVICE CODE */
    SVC_TERMINAL_LIST_SAMPLE(ServiceImplementationType.JAVA),
    SVC_TERMINAL_LIST(ServiceImplementationType.JAVA),
    SVC_TERMINAL_FIND_BY_ID(ServiceImplementationType.JAVA),
    SVC_TERMINAL_CREATE(ServiceImplementationType.JAVA),
    SVC_TERMINAL_EDIT(ServiceImplementationType.JAVA),
    SVC_TERMINAL_DELETE(ServiceImplementationType.JAVA),
    SVC_BUNDLE_LOCALES_LIST(ServiceImplementationType.JAVA),
    SVC_TERMINAL_ADD_SERVICE(ServiceImplementationType.JAVA),
    SVC_TERMINAL_DELETE_SERVICE(ServiceImplementationType.JAVA),
    SVC_CHANNEL_LIST(ServiceImplementationType.JAVA),
    SVC_CHANNEL_FIND_BY_ID(ServiceImplementationType.JAVA),
    SVC_CHANNEL_CREATE(ServiceImplementationType.JAVA),
    SVC_CHANNEL_EDIT(ServiceImplementationType.JAVA),
    SVC_CHANNEL_DELETE(ServiceImplementationType.JAVA),
    SVC_SERVICE_LIST(ServiceImplementationType.JAVA),
    SVC_SERVICE_BY_CODE(ServiceImplementationType.JAVA),
    SVC_SERVICE_BY_ID(ServiceImplementationType.JAVA),
    SVC_SERVICE_CREATE(ServiceImplementationType.JAVA),
    SVC_CARTABLE_APPROVE_PROCESS(ServiceImplementationType.JAVA),
    SVC_CARTABLE_START_PROCESS(ServiceImplementationType.JAVA),
    SVC_CARTABLE_GET_ALL_PROCESS(ServiceImplementationType.JAVA),
    SVC_SERVICE_PROVIDER_CREATE(ServiceImplementationType.JAVA),
    SVC_CARTABLE_COMPLETE_PROCESS(ServiceImplementationType.JAVA),
    SVC_CARTABLE_CANCEL_PROCESS(ServiceImplementationType.JAVA),
    SVC_CARTABLE_GET_ALL_TASK(ServiceImplementationType.JAVA),
    SVC_JOB_CLASS_NAME(ServiceImplementationType.JAVA),
    SVC_ASSETS_SYNC(ServiceImplementationType.JAVA),
    SVC_ASSET_PROVIDER_LIST(ServiceImplementationType.JAVA),
    SVC_JOB_MANAGEMENT_LIST(ServiceImplementationType.JAVA),
    SCV_SERVICE_DELETE(ServiceImplementationType.JAVA),
    SVC_SERVICE_EDIT(ServiceImplementationType.JAVA),
    SVC_TERMINAL_ACCESS_TERMINAL_LIST(ServiceImplementationType.JAVA),
    SVC_SERVICE_ACCESS_SERVICE_LIST(ServiceImplementationType.JAVA),
    SVC_JOB_MANAGEMENT_EXIST(ServiceImplementationType.JAVA),
    SVC_PROCESS_START(ServiceImplementationType.JAVA),
    SVC_GET_ALL_TASK(ServiceImplementationType.JAVA),
    SVC_COMPLETE_TASK(ServiceImplementationType.JAVA),
    SVC_PROCESS_HISTORY_LIST(ServiceImplementationType.JAVA),
    SVC_JOB_MANAGEMENT_FIND_JOB_GROUP_NAME(ServiceImplementationType.JAVA),
    SVC_PROCESS_DEFINITION_LIST(ServiceImplementationType.JAVA),
    SVC_PROCESS_TASK_DETAIL_HISTORY_LIST(ServiceImplementationType.JAVA),
    SVC_JOB_MANAGEMENT_RESUME_JOB(ServiceImplementationType.JAVA),
    SVC_JOB_MANAGEMENT_PAUSE_JOB(ServiceImplementationType.JAVA),
    SVC_PROCESS_CANCEL(ServiceImplementationType.JAVA),
    SVC_JOB_MANAGEMENT_DELETE_ENTITY(ServiceImplementationType.JAVA),
    SVC_ASSETS_LIST_LOCAL(ServiceImplementationType.JAVA),
    SVC_ATTACHMENT_TASK(ServiceImplementationType.JAVA),
    SVC_BUNDLE_LIST(ServiceImplementationType.JAVA),
    SVC_JOB_LIST(ServiceImplementationType.JAVA),
    SVC_JOB_NAMES(ServiceImplementationType.JAVA),
    SVC_BUNDLE_LIST_FIND_BY_ID(ServiceImplementationType.JAVA),
    SVC_BUNDLE_EDIT(ServiceImplementationType.JAVA),
    SVC_JOB_LIST_FIND_BY_EXECUTION_ID(ServiceImplementationType.JAVA),
    SVC_ATTACHMENT_DELETE_TASK(ServiceImplementationType.JAVA),
    SVC_ASSETS_FIND_ACCOUNT_MEMBERSHIP(ServiceImplementationType.JAVA),
    SVC_JOB_MANAGEMENT_SAVE(ServiceImplementationType.JAVA),
    SVC_ERROR_LIST(ServiceImplementationType.JAVA),
    SVC_ERROR_FIND_BY_ID(ServiceImplementationType.JAVA),
    SVC_ERROR_EDIT(ServiceImplementationType.JAVA),
    SVC_PROCESS_DEFINITION_DEPLOY(ServiceImplementationType.JAVA),
    SVC_ATTACHMENT_PROCESS(ServiceImplementationType.JAVA),
    SVC_ATTACHMENT_DELETE_PROCESS(ServiceImplementationType.JAVA),
    SVC_PROCESS_ACTIVE_LIST(ServiceImplementationType.JAVA),
    SVC_PROCESS_ACTIVE_COUNT(ServiceImplementationType.JAVA),
    SVC_PROCESS_DEFINITION_GET(ServiceImplementationType.JAVA),
    SVC_PROCESS_DEFINITION_DELETE(ServiceImplementationType.JAVA),
    SVC_JOB_MANAGEMENT_RUN_JOB(ServiceImplementationType.JAVA),
    SVC_JOB_MANAGEMENT_RUN_JOB_BY_NAME_GROUP(ServiceImplementationType.JAVA),
    SVC_JOB_MANAGEMENT_DELETE_TRIGGER(ServiceImplementationType.JAVA),
    SVC_JOB_MANAGEMENT_RESUME_TRIGGER(ServiceImplementationType.JAVA),
    SVC_JOB_MANAGEMENT_PAUSE_TRIGGER(ServiceImplementationType.JAVA),
    SVC_JOB_MANAGEMENT_DELETE_TRIGGER_ENTITY(ServiceImplementationType.JAVA),
    SVC_RESPONSE_CONDITION_DATA_SOURCE_LIST(ServiceImplementationType.JAVA),
    SVC_ASSETS_FAVOURITE(ServiceImplementationType.JAVA),
    SVC_ASSETS_PROVIDER_FIND_ONE(ServiceImplementationType.JAVA),
    SVC_PARAMETER_CREATE(ServiceImplementationType.JAVA),
    SVC_RESPONSE_CONDITION_DATA_SOURCE_CREATE(ServiceImplementationType.JAVA),
    SVC_RESPONSE_CREATE(ServiceImplementationType.JAVA),
    SVC_PARAMETER_CHANGE(ServiceImplementationType.JAVA),
    SVC_RESPONSE_CHANGE(ServiceImplementationType.JAVA),
    SVC_RESPONSE_CONDITION_DATA_SOURCE_CHANGE(ServiceImplementationType.JAVA),
    SVC_PARAMETER_DELETE(ServiceImplementationType.JAVA),
    SVC_RESPONSE_DELETE(ServiceImplementationType.JAVA),
    SVC_RESPONSE_CONDITION_DATA_SOURCE_DELETE(ServiceImplementationType.JAVA),
    SVC_PARAMETER_FIND_BY_ID(ServiceImplementationType.JAVA),
    SVC_PARAMETER_FIND(ServiceImplementationType.JAVA),
    SVC_PARAMETER_FIND_TREE(ServiceImplementationType.JAVA),
    SVC_RESPONSE_FIND(ServiceImplementationType.JAVA),
    SVC_CARTABLE_COMPLTE_TASK(ServiceImplementationType.JAVA),
    SVC_ASSETS_LIST(ServiceImplementationType.JAVA),
    SVC_CARTABLE_UPDATE_PROCESS_DESCRIPTION(ServiceImplementationType.JAVA),
    SVC_CARTABLE_GET_TASK_BY_PROCESS_ID(ServiceImplementationType.JAVA),
    SVC_SERVICE_PROVIDER_CHANGE(ServiceImplementationType.JAVA),
    SVC_SERVICE_PROVIDER_DELETE(ServiceImplementationType.JAVA),
    SVC_ERROR_CREATE(ServiceImplementationType.JAVA),
    SVC_PARENT_SERVICE_LIST(ServiceImplementationType.JAVA),
    SVC_ERROR_SEARCH(ServiceImplementationType.JAVA),
    SVC_SERVICE_PROVIDER_LIST(ServiceImplementationType.JAVA),
    SVC_SERVICE_PROVIDER_BY_ID(ServiceImplementationType.JAVA),
    SCV_LOG_FIND_BY_ID(ServiceImplementationType.JAVA),
    SCV_LOG_LIST(ServiceImplementationType.JAVA),
    SVC_SERVICE_PROVIDER_PROTOCOL_LIST(ServiceImplementationType.JAVA),
    SVC_SERVICE_PROVIDER_STATUS_LIST(ServiceImplementationType.JAVA),
    SVC_PARAMETER_ACTION_TYPE_LIST(ServiceImplementationType.JAVA),
    SVC_PARAMETER_AUTO_COMPLETE(ServiceImplementationType.JAVA),
    SVC_CONVERTERS_LIST(ServiceImplementationType.JAVA),
    SVC_BUNDLE_CREATE(ServiceImplementationType.JAVA),
    SVC_SERVICE_PROVIDER_NAME_LIST(ServiceImplementationType.JAVA),
    SVC_SERVICE_CREATE_PARENT(ServiceImplementationType.JAVA),
    SVC_SERVICE_EDIT_PARENT(ServiceImplementationType.JAVA),
    SVC_SERVICE_FIND_PARENT(ServiceImplementationType.JAVA),
    SVC_SERVICE_CREATE_JAVA(ServiceImplementationType.JAVA),
    SVC_SERVICE_EDIT_JAVA(ServiceImplementationType.JAVA),
    SVC_SERVICE_FIND_JAVA(ServiceImplementationType.JAVA),
    SVC_SERVICE_CREATE_COMPOSITION(ServiceImplementationType.JAVA),
    SVC_SERVICE_EDIT_COMPOSITION(ServiceImplementationType.JAVA),
    SVC_SERVICE_FIND_COMPOSITION(ServiceImplementationType.JAVA),
    SVC_ASSETS_ASSIGN_MEMBERSHIP_CHANNEL(ServiceImplementationType.JAVA),
    SVC_ASSETS_REVOKE_MEMBERSHIP_CHANNEL(ServiceImplementationType.JAVA),
    SVC_ASSETS_MEMBERSHIP_CHL_WDR_LIMIT(ServiceImplementationType.JAVA),


    /* PARENT SERVICE */
    SVC_TERMINAL_PARENT(ServiceImplementationType.PARENT),
    SVC_CHANNEL_PARENT(ServiceImplementationType.PARENT),
    SVC_SERVICE_PARENT(ServiceImplementationType.PARENT),
    SVC_ACCOUNT_PARENT(ServiceImplementationType.PARENT),
    SVC_CARTABLE_PARENT(ServiceImplementationType.PARENT),
    SVC_JOB_MANAGEMENT_PARENT(ServiceImplementationType.PARENT),
    SVC_CUSTOMER_PARENT(ServiceImplementationType.PARENT),
    SVC_BASE_INFO_PARENT(ServiceImplementationType.PARENT),
    SVC_LOAN_PARENT(ServiceImplementationType.PARENT),
    SVC_CHEQUE_ORDER_PARENT(ServiceImplementationType.PARENT),
    SVC_BILL_PARENT(ServiceImplementationType.PARENT),
    SVC_ASSETS_PARENT(ServiceImplementationType.PARENT),
    SVC_XFER_PARENT(ServiceImplementationType.PARENT),
    SVC_CARD_MANAGEMENT_PARENT(ServiceImplementationType.PARENT),
    SVC_ASSET_PROVIDER_PARENT(ServiceImplementationType.PARENT),
    SVC_CARD_PAYMENT_PARENT(ServiceImplementationType.PARENT),
    SVC_TOPUP_PARENT(ServiceImplementationType.PARENT),
    SVC_PICHACK_PARENT(ServiceImplementationType.PARENT),
    SVC_CHACKAD_PARENT(ServiceImplementationType.PARENT),
    SVC_PAYMENT_ORDER_PARENT(ServiceImplementationType.PARENT),
    SVC_PROCESS_MANAGEMENT_PARENT(ServiceImplementationType.PARENT),
    SVC_PROCESS_TASK_MANAGEMENT(ServiceImplementationType.PARENT),
    SVC_HISTORY_MANAGEMENT_PARENT(ServiceImplementationType.PARENT),
    SVC_PROCESS_DEFINITION_MANAGEMENT_PARENT(ServiceImplementationType.PARENT),
    SVC_PROCESS_INSTANCE_MANAGEMENT_PARENT(ServiceImplementationType.PARENT),
    SVC_ATTACHMENT_MANAGEMENT_PARENT(ServiceImplementationType.PARENT),
    SVC_BUNDLE_PARENT(ServiceImplementationType.PARENT),
    SVC_JOB_REPORT_PARENT(ServiceImplementationType.PARENT),
    SVC_ERROR_PARENT(ServiceImplementationType.PARENT),
    SVC_DYNAMIC_REST_PARENT(ServiceImplementationType.PARENT),
    SVC_CACHE_PARENT(ServiceImplementationType.PARENT),
    SVC_SERVICE_PROVIDER_PARENT(ServiceImplementationType.PARENT),
    SVC_CONVERTERS_PARENT(ServiceImplementationType.PARENT),
    SVC_CONFIG_PARENT(ServiceImplementationType.PARENT),
    SVC_PARAMETER_PARENT(ServiceImplementationType.PARENT),
    SVC_LOG_PARENT(ServiceImplementationType.PARENT);

    private final ServiceImplementationType type;
}
