plugins {
    id 'ir.daneshrefah.scm.java-library-conventions'
}

dependencies {
    compileOnly 'org.springframework.boot:spring-boot-starter-data-jpa'
    compileOnly 'org.springframework.boot:spring-boot-starter'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-db2'
}