plugins {
    id 'ir.daneshrefah.scm.java-library-conventions'
    id 'maven-publish'
    id 'java'
}
publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'ir.daneshrefah.scm.cache'
            artifactId = 'scm-cache-starter'
            version = '1.0.0-SNAPSHOT'

            from components.java
        }
    }
}
//group = 'ir.daneshrefah.scm.cache'
//version = '0.0.1-SNAPSHOT'

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.apache.commons:commons-lang3'

    api 'com.hazelcast:hazelcast-spring'
    api 'com.github.ben-manes.caffeine:caffeine'
    implementation 'com.ibm.db2.jcc:db2jcc:db2jcc4'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.core:jackson-annotations'
    implementation'com.fasterxml.jackson.core:jackson-core'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    api 'com.bucket4j:bucket4j_jdk17-core'
    api 'com.bucket4j:bucket4j_jdk17-hazelcast'
    implementation project(':scm-observation-starter')

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = 'ir.daneshrefah.scm.cache'
            artifactId = 'scm-cache-starter'
            version = '1.0.0-SNAPSHOT'
        }
    }
}
