stages:
  - build
  - docker
  - push

variables:
  REGISTRY_URL: "reg.daneshrefah.ir/modern-banking"
  IMAGE_NAME: "scm-app"
  KUBE_NAMESPACE: "scm"

build_jars:
  stage: build
  only:
    - tags
  image: reg.daneshrefah.ir/modern-banking/scm-ci:alpine-jdk21-gradle-docker

  cache:
    key: gradle-cache
    policy: pull-push
    paths:
      - .gradle/wrapper
      - .gradle/caches
  script:
    - chmod +x gradlew
    - ./gradlew clean :scm-config:bootJar :scm-cache:bootJar :scm-uaa:bootJar :scm-web:bootJar :scm-logging:bootJar --parallel --max-workers=4 -x test
  artifacts:
    paths:
      - "**/build/libs/*.jar"
    expire_in: 1 hour

docker_build:
  stage: docker
  tags:
    - docker
  only:
    - tags
  image: reg.daneshrefah.ir/modern-banking/scm-ci:alpine-jdk21-gradle-docker
  services:
    - docker:29-dind

  needs:
    - job: build_jars
      artifacts: true
  variables:
    DOCKER_TLS_CERTDIR: ""
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

  script:
    - export VERSION=$(echo "$CI_COMMIT_TAG" | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+')

    - echo "Building Single Image VERSION=$VERSION"

    - docker build --build-arg VERSION=$VERSION --build-arg SPRING_APPLICATION_NAME=scm-web -t $REGISTRY_URL/$IMAGE_NAME:$VERSION .

    - mkdir images
    - docker save $REGISTRY_URL/$IMAGE_NAME:$VERSION -o images/scm-app-$VERSION.tar

  artifacts:
    paths:
      - images/scm-app-*.tar
    expire_in: 1 days

docker_push:
  stage: push
  tags:
    - docker
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /_push$/
  image: reg.daneshrefah.ir/modern-banking/scm-ci:alpine-jdk21-gradle-docker
  services:
    - docker:29-dind

  needs:
    - job: docker_build
      artifacts: true
  variables:
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

  script:
    - export VERSION=$(echo "$CI_COMMIT_TAG" | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+')
    - echo "Pushing Single Image VERSION=$VERSION"
    - docker load -i images/scm-app-$VERSION.tar
    - docker push $REGISTRY_URL/$IMAGE_NAME:$VERSION


#  gzip -dc scm-all-8.5.3.tar.gz | docker load
#reg.daneshrefah.ir/modern-banking/scm-all-in-one
# helm upgrade --install scm-config scm-config/scm-config --namespace $KUBE_NAMESPACE --create-namespace --set image.repository=reg.daneshrefah.ir/modern-banking/scm-all-in-one --set image.tag=8.5.3 --wait
