stages:
  - build
  - deploy
image: registry.daneshrefah.ir/refahprojects/build-image:gradle-7-4-2-jdk17
build:
  stage: build
  when: manual
  artifacts:
    paths:
      - "scm-web/build/libs/*.jar"
  script:
    - gradle bootJar

deploy:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$DEV_SCM_1_SSH_PRIVATE_KEY")
    - ssh-add <(echo "$DEV_SCM_2_SSH_PRIVATE_KEY")
    - ssh -o StrictHostKeyChecking=no -p $DEV_SCM_1_SSH_PORT $DEV_SCM_1_SSH_USER@$DEV_SCM_1_SSH_SERVER "pkill -f scm-web.jar;"
    - current_date=$(date +\%Y\%m\%d)
    - ssh -o StrictHostKeyChecking=no -p $DEV_SCM_1_SSH_PORT $DEV_SCM_1_SSH_USER@$DEV_SCM_1_SSH_SERVER mv /home/pwausr/scm-web.jar /home/pwausr/scm-web-$current_date.jar
    - scp -o StrictHostKeyChecking=no -P $DEV_SCM_1_SSH_PORT scm-web/build/libs/*.jar $DEV_SCM_1_SSH_USER@$DEV_SCM_1_SSH_SERVER:/home/pwausr/scm-web.jar
    - ssh -o StrictHostKeyChecking=no -p $DEV_SCM_1_SSH_PORT $DEV_SCM_1_SSH_USER@$DEV_SCM_1_SSH_SERVER "bash -c /home/pwausr/server.sh"
        - ssh -o StrictHostKeyChecking=no -p $DEV_SCM_2_SSH_PORT $DEV_SCM_2_SSH_USER@$DEV_SCM_2_SSH_SERVER "pkill -f scm-web.jar;"
    - ssh -o StrictHostKeyChecking=no -p $DEV_SCM_2_SSH_PORT $DEV_SCM_2_SSH_USER@$DEV_SCM_2_SSH_SERVER mv /home/pwausr/scm-web.jar /home/pwausr/scm-web-$current_date.jar
    - scp -o StrictHostKeyChecking=no -P $DEV_SCM_2_SSH_PORT scm-web/build/libs/*.jar $DEV_SCM_2_SSH_USER@$DEV_SCM_2_SSH_SERVER:/home/pwausr/scm-web.jar
    - ssh -o StrictHostKeyChecking=no -p $DEV_SCM_2_SSH_PORT $DEV_SCM_2_SSH_USER@$DEV_SCM_2_SSH_SERVER "bash -c /home/pwausr/server.sh"
#    - ssh pwausr:pwausr@10.10.4.121 "sudo systemctl restart your-app.service"
#    - ssh pwausr:pwausr@10.10.4.121 "sudo systemctl stop your-app.service"
#    - ssh pwausr:pwausr@10.10.4.121 "mv /path/to/deployment/your-app.jar /path/to/deployment/your-app-$(date +\%Y\%m\%d).jar"
#    - scp target/your-app.jar pwausr:pwausr@10.10.4.121:/path/to/deployment/
#    - ssh user@server "sudo systemctl start your-app.service"
  only:
    - main
