plugins {
    id 'ir.daneshrefah.scm.java-library-conventions'
    id 'java'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

bootJar {
    enabled = true
    version = parent.version
}

compileJava.options.encoding = 'UTF-8'

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named("bootJar") {
    mainClass = 'ir.daneshrefah.scm.log.LoggingServerApplication'
    archiveClassifier = 'boot'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'com.ibm.mq:mq-jms-spring-boot-starter'
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'jakarta.servlet:jakarta.servlet-api'
    api project(':scm-logging')
}


