SCM_ENV: pilot
SCM_APPLICATION_NAME: scm-web
SCM_INSTANCE_ID: ${HOSTNAME:scm-web-pilot}
SCM_CHANNEL_CODE: ${SCM_WEB_PILOT_CHANNEL_CODE}
SCM_GATEWAY_NAME: ${SCM_WEB_PILOT_GATEWAY_NAME}

SCM_UAA_BASE_URL: ${SCM_UAA_PILOT_BASE_URL}

SCM_DB_URL: ${SCM_WEB_PILOT_DB_URL}
SCM_DB_USERNAME: ${SCM_WEB_PILOT_DB_USERNAME}
SCM_DB_PASSWORD: ${SCM_WEB_PILOT_DB_PASSWORD}
SCM_DB_DRIVER: ${SCM_WEB_PILOT_DB_DRIVER:com.ibm.db2.jcc.DB2Driver}
SCM_DB_SCHEMA: ${SCM_WEB_PILOT_DB_SCHEMA}
SCM_DB_MAX_CONNECTION: ${SCM_WEB_PILOT_DB_MAX_CONNECTION:10}

SCM_OBS_ROOT_DIR: ${SCM_WEB_PILOT_OBS_ROOT_DIR:/mnt/log/scm/obs}
SCM_OBS_LOG_CONSOLE_ENABLED: false
SCM_OBS_LOG_FILE_ENABLED: true
SCM_OBS_TRACE_ENABLED: true
SCM_OBS_TRACE_FILE_ENABLED: true
SCM_OBS_AUDIT_ENABLED: false

SCM_PROVIDER_DEFAULT_CONNECT_TIMEOUT_MS: ${SCM_WEB_PILOT_PROVIDER_CONNECT_TIMEOUT_MS:3000}
SCM_PROVIDER_DEFAULT_SOCKET_TIMEOUT_MS: ${SCM_WEB_PILOT_PROVIDER_SOCKET_TIMEOUT_MS:1000}
SCM_PROVIDER_DEFAULT_SEND_TIMEOUT_MS: ${SCM_WEB_PILOT_PROVIDER_SEND_TIMEOUT_MS:1000}
SCM_PROVIDER_DEFAULT_RESPONSE_TIMEOUT_MS: ${SCM_WEB_PILOT_PROVIDER_RESPONSE_TIMEOUT_MS:8000}
SCM_PROVIDER_DEFAULT_QUEUE_CAPACITY: ${SCM_WEB_PILOT_PROVIDER_QUEUE_CAPACITY:1000}

SCM_HPS_BASE_URL: ${SCM_WEB_PILOT_HPS_BASE_URL}
SCM_HPS_REST_BASE_URL: ${SCM_WEB_PILOT_HPS_REST_BASE_URL}
SCM_HPS_REST_USERNAME: ${SCM_WEB_PILOT_HPS_REST_USERNAME}
SCM_HPS_REST_PASSWORD: ${SCM_WEB_PILOT_HPS_REST_PASSWORD}
SCM_HPS_SHETAB7_ENDPOINTS: ${SCM_WEB_PILOT_HPS_SHETAB7_ENDPOINTS}
SCM_HPS_SHETAB7_PIN_KEY: ${SCM_WEB_PILOT_HPS_SHETAB7_PIN_KEY}
SCM_HPS_SHETAB7_MAC_KEY: ${SCM_WEB_PILOT_HPS_SHETAB7_MAC_KEY}

SCM_API_REPO_BASE_URL: ${SCM_WEB_PILOT_API_REPO_BASE_URL}

SCM_NAB_ATPS_ENDPOINT: ${SCM_WEB_PILOT_NAB_ATPS_ENDPOINT}
SCM_NAB_ATPS_USER_ID: ${SCM_WEB_PILOT_NAB_ATPS_USER_ID}
SCM_NAB_ATPS_PASSWORD: ${SCM_WEB_PILOT_NAB_ATPS_PASSWORD}

SCM_CACHE_CLUSTER_NAME: scm-cache-pilot
SCM_CACHE_ADDRESS: ${SCM_CACHE_PILOT_ADDRESS}
