plugins {
    id 'ir.daneshrefah.scm.java-library-conventions'
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.slf4j:slf4j-api'
    api 'net.logstash.logback:logstash-logback-encoder'
    implementation 'io.micrometer:micrometer-core'
    implementation 'io.micrometer:micrometer-tracing'
    implementation 'io.micrometer:micrometer-tracing-bridge-otel'
    implementation 'io.opentelemetry:opentelemetry-sdk'
    compileOnly 'ch.qos.logback:logback-classic'
    compileOnly 'jakarta.servlet:jakarta.servlet-api'
    compileOnly 'org.springframework:spring-web'
    compileOnly 'org.springframework:spring-webmvc'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
