/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ir.daneshrefah.scm.app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication(scanBasePackages = {"ir.daneshrefah"})
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
