/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ir.daneshrefah.scm.app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@SpringBootApplication(scanBasePackages = {"ir.daneshrefah"})
@EnableJpaRepositories(basePackages = "ir.daneshrefah.scm")
@EntityScan(basePackages = "ir.daneshrefah.scm")
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
