plugins {
    id 'ir.daneshrefah.scm.java-library-conventions'
}

dependencies {
    implementation project(':scm-observation-starter')
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework:spring-web'
    implementation 'org.slf4j:slf4j-api'
    compileOnly 'jakarta.servlet:jakarta.servlet-api'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
}
