plugins {
    id 'ir.daneshrefah.scm.java-library-conventions'
}

group = 'ir.daneshrefah.scm.plugin.camel'
version = parent.version

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.apache.camel.springboot:camel-spring-boot-starter'
    implementation 'org.apache.camel.springboot:camel-netty-starter'

//    implementation 'org.apache.httpcomponents:httpclient'
    implementation 'org.apache.httpcomponents.client5:httpclient5:5.3.1'
    implementation 'org.apache.commons:commons-text'
    implementation 'org.apache.camel:camel-groovy:4.14.2'
    implementation 'org.apache.groovy:groovy-json:4.0.29'
    implementation 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    api  project(':scm-utils')


    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.apache.camel.springboot:camel-spring-boot-starter-test'
    compileOnly project(':scm-common')
}

tasks.named('test') {
    useJUnitPlatform()
}
