server:
  port: 8888
spring:
  application:
    name: scm-config
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      server:
        git:
          uri: /mnt/config-repo-server
#            uri: /home/scm/docker/config/config-repo-server   for DOCKER
          search-paths: '{application}'
          clone-on-start: true
          default-label: master
          basedir: /app/config-repo
        encrypt:
          enabled: true
        prefix: /config
scm:
  config:
    applications:
      scm-web: ib4dev ,ib4test ,ib4prod ,scm4dev,ib4pilot ,scm4test ,scm4prod,scm4pilot , mb4dev, mb4test, mb4pilot,mb4prod, pwa4dev, pwa4test, pwa4prod,pwa4pilot
      scm-uaa: dev, test, prod,pilot
      scm-cache: dev, test, prod,pilot
      scm-logging: dev, test, prod,pilot
    scm-user:
      name: scm
      pass: scm
    cfg-user:
      name: cfg
      pass: cfg
    opr-user:
      name: opr
      pass: opr
encrypt:
  key: "WW@MwjtA9znCPVMi"
logging:
  file:
    path: /mnt/log