SCM_METADATA_NAMESPACE: local
SCM_METADATA_INSTANCE_ID: local-scm-config
SCM_OBS_LOG_CONSOLE_ENABLED: true
SCM_OBS_TRACE_CONSOLE_ENABLED: true
SCM_OBS_AUDIT_CONSOLE_ENABLED: true

SCM_CONFIG_SERVER_PORT: ${SERVER_PORT:8888}
SCM_CONFIG_SERVER_PREFIX: /config

SCM_CONFIG_REPO_URI: /mnt/config-repo-server
SCM_CONFIG_REPO_SEARCH_PATHS: "{application}"
SCM_CONFIG_REPO_BASEDIR: /app/config-repo
SCM_CONFIG_REPO_CLONE_ON_START: true
SCM_CONFIG_NATIVE_SEARCH_LOCATIONS: file:/mnt/config-repo-server

SCM_CONFIG_ADMIN_USERNAME: admin
SCM_CONFIG_ADMIN_PASSWORD: ${SCM_DEV_CONFIG_ADMIN_PASSWORD:change-me}
SCM_CONFIG_USERNAME: scm
SCM_CONFIG_PASSWORD: ${SCM_DEV_CONFIG_PASSWORD:change-me}
SCM_CONFIG_CFG_USERNAME: cfg
SCM_CONFIG_CFG_PASSWORD: ${SCM_DEV_CONFIG_CFG_PASSWORD:change-me}
SCM_CONFIG_OPR_USERNAME: opr
SCM_CONFIG_OPR_PASSWORD: ${SCM_DEV_CONFIG_OPR_PASSWORD:change-me}
SCM_CONFIG_ENCRYPT_KEY: ${SCM_DEV_CONFIG_ENCRYPT_KEY:change-me-local-only}

SCM_CONFIG_LOG_PATH: /mnt/log
SCM_CONFIG_APPLICATIONS_SCM_WEB: dev, test, pilot, prod
SCM_CONFIG_APPLICATIONS_SCM_CACHE: dev, test, pilot, prod
SCM_CONFIG_APPLICATIONS_SCM_UAA: dev, test, pilot, prod
SCM_CONFIG_APPLICATIONS_SCM_LOGGING: dev, test, pilot, prod
SCM_CONFIG_APPLICATIONS_SCM_CM_CONNECTOR: dev, test, pilot, prod
