server.port=8888
#spring.cloud.config.server.git.uri: file://${user.home}/IdeaProjects/config-repo
#spring.cloud.config.server.custom-repository-class=ir.daneshrefah.scm.config.DatabaseEnvironmentRepository
#spring.cloud.config.server.jdbc.enabled=true
#spring.cloud.config.server.git.default-label=main
#spring.cloud.config.server.jdbc.sql=SELECT key, value FROM properties WHERE application = ? and profile = ? and label = ?
#spring.cloud.config.server.jdbc.order=1
#spring.cloud.config.server.jdbc.sql=SELECT "PROP_KEY", "PROP_VALUE" from REF.TBL_SFG_PROPERT IES where APPLICATION_KEY=? and PROFILE_KEY=? and LABEL_KEY=?
#spring.cloud.config.server.jdbc.sqlWithoutProfile=SELECT "PROP_KEY", "PROP_VALUE" from REF.TBL_SFG_PROPERTIES where APPLICATION_KEY=? and PROFILE_KEY=?
spring.cloud.config.server.jdbc.defaultLabel=
spring.cloud.config.server.prefix=/config

# Database configuration
spring.datasource.url=jdbc:db2://10.10.4.104:50001/DBREFSW
spring.datasource.username=db2inst1
spring.datasource.password=db2inst1
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver
spring.jpa.properties.hibernate.default_schema=REF
spring.jpa.show-sql=true


# Hazelcast configuration
spring.cache.type=hazelcast
hazelcast.config-location=classpath:hazelcast.xml
#spring.hazelcast.config=classpath:hazelcast.xml

spring.cloud.config.server.jdbc.sql=SELECT "PROP_KEY", "PROP_VALUE" FROM "REF".TBL_SFG_PROPERTY tsp JOIN "REF".TBL_SFG_APPLICATION tsa ON tsp.APPLICATION_ID = tsa.APPLICATION_ID JOIN "REF".TBL_SFG_PROFILE tsp2 ON tsp.PROFILE_ID = tsp2.PROFILE_ID WHERE (tsa.CODE = ?) AND (tsp2.CODE = ?) AND (tsp.LABEL_KEY = ? OR tsp.LABEL_KEY IS NULL)
spring.cloud.config.server.jdbc.sql-without-profile=SELECT "PROP_KEY", "PROP_VALUE" FROM "REF".TBL_SFG_PROPERTY tsp INNER JOIN "REF".TBL_SFG_APPLICATION tsa ON tsp.APPLICATION_ID = tsa.APPLICATION_ID INNER JOIN "REF".TBL_SFG_PROFILE tsp2 ON tsp.PROFILE_ID = tsp2.PROFILE_ID WHERE tsa.CODE = ? AND tsp2.CODE = ?

