SCM_ENV: prod
SCM_APPLICATION_NAME: scm-config
SCM_INSTANCE_ID: scm-config-prod
SCM_CONFIG_SERVER_PORT: ${SERVER_PORT:8888}
SCM_CONFIG_SERVER_PREFIX: /config

SCM_CONFIG_REPO_URI: /mnt/config-repo-server
SCM_CONFIG_REPO_SEARCH_PATHS: "{application}"
SCM_CONFIG_REPO_BRANCH: master
SCM_CONFIG_REPO_BASEDIR: /app/config-repo
SCM_CONFIG_REPO_CLONE_ON_START: true
SCM_CONFIG_NATIVE_SEARCH_LOCATIONS: file:/mnt/config-repo-server
SCM_CONFIG_LOG_PATH: /mnt/log
SCM_OBS_ROOT_DIR: /mnt/log/scm/obs
SCM_OBS_LOG_CONSOLE_ENABLED: false
SCM_OBS_LOG_FILE_ENABLED: true
SCM_OBS_TRACE_FILE_ENABLED: true
SCM_OBS_AUDIT_ENABLED: false

SCM_CONFIG_APPLICATIONS_SCM_WEB: dev, test, pilot, prod
SCM_CONFIG_APPLICATIONS_SCM_CACHE: dev, test, pilot, prod
SCM_CONFIG_APPLICATIONS_SCM_UAA: dev, test, pilot, prod
SCM_CONFIG_APPLICATIONS_SCM_LOGGING: dev, test, pilot, prod
SCM_CONFIG_APPLICATIONS_SCM_CM_CONNECTOR: dev, test, pilot, prod
