spring:
  profiles:
    active: ${SCM_ENV:dev}
  application:
    name: ${SCM_APP:scm-config}
  security:
    user:
      name: ${SCM_CONFIG_ADMIN_USERNAME:admin}
      password: ${SCM_CONFIG_ADMIN_PASSWORD:${SCM_CONFIG_PASSWORD}}
  cloud:
    config:
      enabled: ${SCM_CONFIG_ENABLED:false}
      import-check:
        enabled: ${SCM_CONFIG_IMPORT_CHECK_ENABLED:false}
      server:
        git:
          uri: ${SCM_CONFIG_REPO_URI:/mnt/config-repo-server}
          search-paths: ${SCM_CONFIG_REPO_SEARCH_PATHS}
          clone-on-start: ${SCM_CONFIG_REPO_CLONE_ON_START:true}
          default-label: ${SCM_LABEL:master}
          basedir: ${SCM_CONFIG_REPO_BASEDIR:/app/config-repo}
          username: ${SCM_CONFIG_REPO_USERNAME:}
          password: ${SCM_CONFIG_REPO_PASSWORD:}
        native:
          search-locations: ${SCM_CONFIG_NATIVE_SEARCH_LOCATIONS:file:/mnt/config-repo-server}
        encrypt:
          enabled: ${SCM_CONFIG_ENCRYPT_ENABLED:true}
        prefix: ${SCM_CONFIG_SERVER_PREFIX:/config}

server:
  port: ${SCM_CONFIG_SERVER_PORT:${SERVER_PORT:8888}}

management:
  endpoints:
    web:
      exposure:
        include: ${SCM_MANAGEMENT_ENDPOINTS_INCLUDE:health,info,metrics,prometheus}
  endpoint:
    health:
      show-details: ${SCM_MANAGEMENT_HEALTH_SHOW_DETAILS:never}
      probes:
        enabled: ${SCM_MANAGEMENT_HEALTH_PROBES_ENABLED:true}

logging:
  config: ${SCM_LOGBACK_CONFIG:classpath:logback-spring.xml}
  file:
    path: ${SCM_CONFIG_LOG_PATH:/mnt/log}
  level:
    root: ${SCM_LOG_LEVEL_ROOT:INFO}
    ir.daneshrefah: ${SCM_LOG_LEVEL_APPLICATION:INFO}
    org.springframework: ${SCM_LOG_LEVEL_SPRING:INFO}

scm:
  metadata:
    namespace: ${SCM_METADATA_NAMESPACE:}
    instance-id: ${SCM_METADATA_INSTANCE_ID:}
    time-zone: ${SCM_METADATA_TIME_ZONE:}

  deployment:
    service-version: ${SCM_SERVICE_VERSION:${VERSION:8.6.0}}

  application:
    version: ${SCM_APPLICATION_VERSION:${VERSION:8.6.0}}
    build: ${SCM_APPLICATION_BUILD:unknown}

  runtime: ${SCM_RUNTIME:standalone}

  observation:
    http:
      server:
        span-name: ${SCM_OBS_HTTP_SERVER_SPAN_NAME:config.http.request}

  config:
    applications:
      scm-web: ${SCM_CONFIG_APPLICATIONS_SCM_WEB:dev, test, pilot, prod}
      scm-cache: ${SCM_CONFIG_APPLICATIONS_SCM_CACHE:dev, test, pilot, prod}
      scm-uaa: ${SCM_CONFIG_APPLICATIONS_SCM_UAA:dev, test, pilot, prod}
      scm-logging: ${SCM_CONFIG_APPLICATIONS_SCM_LOGGING:dev, test, pilot, prod}
      scm-cm-connector: ${SCM_CONFIG_APPLICATIONS_SCM_CM_CONNECTOR:dev, test, pilot, prod}
    scm-user:
      name: ${SCM_CONFIG_USERNAME:scm}
      pass: ${SCM_CONFIG_PASSWORD}
    cfg-user:
      name: ${SCM_CONFIG_CFG_USERNAME:cfg}
      pass: ${SCM_CONFIG_CFG_PASSWORD:${SCM_CONFIG_PASSWORD}}
    opr-user:
      name: ${SCM_CONFIG_OPR_USERNAME:opr}
      pass: ${SCM_CONFIG_OPR_PASSWORD:${SCM_CONFIG_PASSWORD}}

encrypt:
  key: ${SCM_CONFIG_ENCRYPT_KEY}
