server.port=8888
#spring.cloud.config.server.git.uri: file://${user.home}/IdeaProjects/config-repo
#spring.cloud.config.server.custom-repository-class=ir.daneshrefah.scm.config.DatabaseEnvironmentRepository
spring.cloud.config.server.jdbc.enabled=true
spring.cloud.config.server.git.default-label=main

# Database configuration
spring.datasource.url=jdbc:db2://10.10.4.104:50001/DBREFSW
spring.datasource.username=db2inst1
spring.datasource.password=db2inst1
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver
spring.jpa.properties.hibernate.default_schema=REF
spring.jpa.show-sql=true


# Hazelcast configuration
spring.hazelcast.config=classpath:hazelcast.xml
