
CREATE TABLE "REF"."TBL_SFG_PROFILE"  (
    "PROFILE_ID" DECIMAL(22,0) NOT NULL GENERATED ALWAYS AS IDENTITY (
        START WITH +1
        INCREMENT BY +1
        MINVALUE +1
        MAXVALUE +9999999999999999999999
        NO CYCLE
        CACHE 20
        NO ORDER ),
    "CODE" VARCHAR(255 OCTETS) NOT NULL,
    "TITLE" VARCHAR(255 OCTETS),
    "CREATE_DATE" TIMESTAMP NOT NULL,
    "CREATOR_USER" VARCHAR(255) NOT NULL,
    "LAST_EDIT_DTE" TIMESTAMP NOT NULL,
    "LAST_EDITOR_USER" VARCHAR(255) NOT NULL,
    PRIMARY KEY (PROFILE_ID)
);

INSERT INTO "REF".TBL_SFG_PROFILE (CODE, TITLE, CREATE_DATE, CREATOR_USER, LAST_EDIT_DTE, LAST_EDITOR_USER) VALUES
                                ('dev','توسعه', CURRENT TIMESTAMP, '', CURRENT TIMESTAMP, ''),
                                ('test-dd','تست بانکداری مجازی', CURRENT TIMESTAMP, '', CURRENT TIMESTAMP, ''),
                                ('test-ns','تست خدمات الکترونیک', CURRENT TIMESTAMP, '', CURRENT TIMESTAMP, ''),
                                ('pre-production','پایلوت', CURRENT TIMESTAMP, '', CURRENT TIMESTAMP, ''),
                                ('production','عملیاتی', CURRENT TIMESTAMP, '', CURRENT TIMESTAMP, '');

CREATE TABLE "REF"."TBL_SFG_APPLICATION"  (
    "APPLICATION_ID" DECIMAL(22,0) NOT NULL GENERATED ALWAYS AS IDENTITY (
        START WITH +1
        INCREMENT BY +1
        MINVALUE +1
        MAXVALUE +9999999999999999999999
        NO CYCLE
        CACHE 20
        NO ORDER ),
    "CODE" VARCHAR(255 OCTETS) NOT NULL,
    "TITLE" VARCHAR(255 OCTETS),
    "CREATE_DATE" TIMESTAMP NOT NULL,
    "CREATOR_USER" VARCHAR(255) NOT NULL,
    "LAST_EDIT_DTE" TIMESTAMP NOT NULL,
    "LAST_EDITOR_USER" VARCHAR(255) NOT NULL,
    PRIMARY KEY (APPLICATION_ID)
);

INSERT INTO "REF".TBL_SFG_APPLICATION (CODE,TITLE, CREATE_DATE, CREATOR_USER, LAST_EDIT_DTE, LAST_EDITOR_USER) VALUES
               ('application','تنظیمات کلی', CURRENT TIMESTAMP, '', CURRENT TIMESTAMP, ''),
               ('scm-app','سامانه مدیریت کانال', CURRENT TIMESTAMP, '', CURRENT TIMESTAMP, ''),
               ('scm-cache','سامانه حافظه پنهان', CURRENT TIMESTAMP, '', CURRENT TIMESTAMP, ''),
               ('scm-uaa','سامانه مدیریت کاربران', CURRENT TIMESTAMP, '', CURRENT TIMESTAMP, '');
-- DROP TABLE "REF".TBL_SFG_PROPERTY;

CREATE TABLE "REF".TBL_SFG_PROPERTY (
    "PROPERTY_ID" DECIMAL(22,0) NOT NULL GENERATED ALWAYS AS IDENTITY (
        START WITH +1
        INCREMENT BY +1
        MINVALUE +1
        MAXVALUE +9999999999999999999999
        NO CYCLE
        CACHE 20
        NO ORDER ),
    APPLICATION_ID DECIMAL(22,0) NOT NULL,
    PROFILE_ID DECIMAL(22,0) NOT NULL,
    LABEL_KEY VARCHAR(255),
    PROP_KEY VARCHAR(255) NOT NULL,
    PROP_VALUE VARCHAR(2500) NOT NULL,
    "CREATE_DATE" TIMESTAMP NOT NULL,
    "CREATOR_USER" VARCHAR(255) NOT NULL,
    "LAST_EDIT_DTE" TIMESTAMP NOT NULL,
    "LAST_EDITOR_USER" VARCHAR(255) NOT NULL,
    FOREIGN KEY (APPLICATION_ID) REFERENCES REF.TBL_SFG_APPLICATION (APPLICATION_ID),
    FOREIGN KEY (PROFILE_ID) REFERENCES REF.TBL_SFG_PROFILE (PROFILE_ID),
    PRIMARY KEY (PROPERTY_ID)
);
