
CREATE TABLE "REF"."TBL_SFG_PROFILE"  (
    "PROFILE_ID" DECIMAL(22,0) NOT NULL GENERATED ALWAYS AS IDENTITY (
        START WITH +1
        INCREMENT BY +1
        MINVALUE +1
        MAXVALUE +9999999999999999999999
        NO CYCLE
        CACHE 20
        NO ORDER ),
    "CODE" VARCHAR(255 OCTETS) NOT NULL,
    "TITLE" VARCHAR(255 OCTETS),
    PRIMARY KEY (PROFILE_ID)
);


CREATE TABLE "REF"."TBL_SFG_APPLICATION"  (
    "APPLICATION_ID" DECIMAL(22,0) NOT NULL GENERATED ALWAYS AS IDENTITY (
        START WITH +1
        INCREMENT BY +1
        MINVALUE +1
        MAXVALUE +9999999999999999999999
        NO CYCLE
        CACHE 20
        NO ORDER ),
    "CODE" VARCHAR(255 OCTETS) NOT NULL,
    "TITLE" VARCHAR(255 OCTETS),
    PRIMARY KEY (APPLICATION_ID)
);


-- DROP TABLE "REF".TBL_SFG_PROPERTY;

CREATE TABLE "REF".TBL_SFG_PROPERTY (
    "PROPERTY_ID" DECIMAL(22,0) NOT NULL GENERATED ALWAYS AS IDENTITY (
        START WITH +1
        INCREMENT BY +1
        MINVALUE +1
        MAXVALUE +9999999999999999999999
        NO CYCLE
        CACHE 20
        NO ORDER ),
    APPLICATION_ID DECIMAL(22,0) NOT NULL,
    PROFILE_ID DECIMAL(22,0) NOT NULL,
    LABEL_KEY VARCHAR(255),
    PROP_KEY VARCHAR(255) NOT NULL,
    PROP_VALUE VARCHAR(2500) NOT NULL,
    FOREIGN KEY (APPLICATION_ID) REFERENCES REF.TBL_SFG_APPLICATION (APPLICATION_ID),
    FOREIGN KEY (PROFILE_ID) REFERENCES REF.TBL_SFG_PROFILE (PROFILE_ID),
    PRIMARY KEY (PROPERTY_ID)
);
