plugins {
    id 'ir.daneshrefah.scm.java-library-conventions'
    id "org.springframework.boot" version'3.1.2'
    id 'java'
}

tasks.named("bootJar") {
    mainClass = 'ir.daneshrefah.scm.config.server.ConfigServerApplication'
    archiveClassifier = 'boot'

}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.cloud:spring-cloud-config-server'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    api 'org.springframework.boot:spring-boot-starter-web'
    implementation group: 'org.springdoc', name: 'springdoc-openapi-starter-webmvc-ui', version: '2.1.0'
    implementation 'org.mapstruct:mapstruct:1.5.3.Final'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.3.Final'
    implementation 'com.hazelcast:hazelcast-spring:5.2.2'
    implementation group: 'io.springfox', name: 'springfox-swagger-ui', version: '3.0.0'
    implementation group: 'org.eclipse.jgit', name: 'org.eclipse.jgit', version: '6.8.0.202311291450-r'
    implementation group: 'org.yaml', name: 'snakeyaml', version: '2.2'
}

