plugins {
    id 'ir.daneshrefah.scm.java-library-conventions'
    id 'java'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

bootJar {
    enabled = true
    version = parent.version
}

tasks.named("bootJar") {
    mainClass = 'ir.daneshrefah.scm.cache.CacheServerApplication'
    archiveClassifier = ''

}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'com.hazelcast:hazelcast-spring'
    compileOnly 'jakarta.persistence:jakarta.persistence-api'
    runtimeOnly 'com.ibm.db2:db2jcc'
    runtimeOnly 'com.ibm.db2:db2jcc_license_cisuz'
    runtimeOnly 'com.ibm.db2.jcc:db2jcc:db2jcc4'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
    implementation project(':scm-observation-starter')
    runtimeOnly 'org.codehaus.janino:janino'
}
