---
# Source: scm-cache/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scm-cache-service-account
  labels:
    helm.sh/chart: scm-cache-0.1.0
    app.kubernetes.io/name: scm-cache
    app.kubernetes.io/instance: scm-cache
    app.kubernetes.io/version: "8.3.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: scm-cache/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scm-cache-role
rules:
  - apiGroups: [""]
    resources: ["pods", "endpoints", "nodes", "services", "statefulsets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list"]
---
# Source: scm-cache/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scm-cache-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: scm-cache-service-account
roleRef:
  kind: Role
  name: scm-cache-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: scm-cache/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: scm-cache
  labels:
    helm.sh/chart: scm-cache-0.1.0
    app.kubernetes.io/name: scm-cache
    app.kubernetes.io/instance: scm-cache
    app.kubernetes.io/version: "8.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 5701
      targetPort: 5701
      protocol: TCP
      name: hazelcast
  externalIPs:
    - 10.10.4.122
    - 10.10.4.123

  selector:
    app.kubernetes.io/name: scm-cache
    app.kubernetes.io/instance: scm-cache
---
# Source: scm-cache/templates/serviceapi.yaml
apiVersion: v1
kind: Service
metadata:
  name: scm-cache-api
  labels:
    helm.sh/chart: scm-cache-0.1.0
    app.kubernetes.io/name: scm-cache
    app.kubernetes.io/instance: scm-cache
    app.kubernetes.io/version: "8.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  externalIPs:
    - 10.10.4.122

  selector:
    app.kubernetes.io/name: scm-cache
    app.kubernetes.io/instance: scm-cache
---
# Source: scm-cache/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scm-cache
  labels:
    helm.sh/chart: scm-cache-0.1.0
    app.kubernetes.io/name: scm-cache
    app.kubernetes.io/instance: scm-cache
    app.kubernetes.io/version: "8.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: scm-cache
      app.kubernetes.io/instance: scm-cache
  template:
    metadata:
      labels:
        helm.sh/chart: scm-cache-0.1.0
        app.kubernetes.io/name: scm-cache
        app.kubernetes.io/instance: scm-cache
        app.kubernetes.io/version: "8.3.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: scm-cache-service-account
      securityContext:
        {}
      containers:
        - name: scm-cache
          securityContext:
            {}
          image: "reg.daneshrefah.ir/modern-banking/scm-app:8.3.0-b0513T1800"
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: test
            - name: SPRING_APPLICATION_NAME
              value: scm-cache
            - name: VERSION
              value: 8.3.0
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_CLOUD_CONFIG_URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CLOUD_CONFIG_URI
                  name: scm-config-configmap
          ports:
            - name: hazelcast
              containerPort: 5701
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP




          resources:
            {}
      nodeSelector:
        app: scm-cache
      tolerations:
        - effect: NoSchedule
          key: daneshrefah.ir/group
          operator: Equal
          value: scm
