spring:
  application:
    name: scm-web
  config:
    import: 'optional:configserver:'
    activate:
      on-profile: ib4dev
  cloud:
    config:
      username: scm
      password: scm
      name: scm
      enabled: true
      uri: http://10.10.4.125:8888/config
      allow-override: true