scm:
  channels: IB4DEV
  provider:
    nab: http://scm-core.daneshrefah.ir/Service
    nab-tcp: 10.15.27.12:3080
    iban: http://10.15.29.131:8086/ibanq/services/IBANService
    #    iban: http://10.15.8.195:8080/ibanq/services/IBANService
    pichack: http://10.15.27.51:8080/dpi/api/pichak
    #    pichack: http://10.15.46.105:8080/dpi/api/pichak
    sayad: http://10.15.1.98:8080/sayad/services/api
  #    sayad: http://10.15.46.20:8080/sayad/services/api
  datasource:
    primary:
      url: jdbc:db2://10.10.4.104:50001/DBREFSW
      username: db2inst1
      password: db2inst1
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 10
      default-schema: REF
    secondary:
      -
        name: default
        url: jdbc:db2://10.10.4.104:50001/DBREFSW
        username: db2inst1
        password: db2inst1
        driver-class-name: com.ibm.db2.jcc.DB2Driver
        max-connection: 10
        default-schema: REF
      -
        name: default2
        url: jdbc:db2://10.10.4.104:50001/DBREFSW
        username: db2inst1
        password: db2inst1
        driver-class-name: com.ibm.db2.jcc.DB2Driver
        max-connection: 10
        default-schema: REF
  log:
    file-directory: log
    file-name: ${spring.application.name}.log
    log-pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %msg%n"
    file-name-pattern: "%d{yyyy-MM-dd}.%i.log"
    file-size: 1MB  #Max size of each log file
    keep-log-history: 30 #Keep up to 30 days of log files
  security:
    client-id: scm
    client-secret:
    distributed: true
    person-service: local
    issuer-uri: http://10.10.4.125:8000
  cache:
    client:
      config:
        distributed: true
        cluster-name: dev3
        server-host: 10.10.4.125
        server-port: 5701
        near-cache-config:
          myMap:
            in-memory-format: object
            time-to-live-seconds: 10
  process:
    enabled: true
    client-id: BPM
    client-secret: myClientSecretValue
    datasource:
      url: jdbc:db2://10.10.4.104:50001/DBREFSW
      username: db2inst1
      password: db2inst1
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 10
      default-schema: db-camunda #change it to REF


server:
  servlet:
    context-path: /scm
  port: 8086
#spring:
#  datasource:
#    url: jdbc:db2://10.10.4.104:50001/DBREFSW
#    username: db2inst1
#    password: db2inst1
#    driver-class-name: com.ibm.db2.jcc.DB2Driver
#  jpa:
#    properties:
#      hibernate:
#        default_schema: REF
#        format_sql: true
#        show_sql: true
#  mvc:
#    servlet:
#      load-on-startup: 1
#      path: /
logging:
  config: classpath:logback-spring.xml
  level:
    org.hibernate.SQL: debug #just for develop
    org.hibernate.type.descriptor.sql: trace #just for develop
    org.hibernate.orm.jdbc.bind: trace #just for develop
spring:
  jpa:
    show-sql: true
#  properties:
#    hibernate:
#      format_sql: true
  cloud:
    config:
      enabled: false
  application:
    name: scm-web