scm:
  profile: IB4DEV
  inbound:
    host: localhost
    port: 8582
  log:
    enabled: true
    type: file
  security:
    distributed: true
    token-endpoint: http://127.0.0.1:8000/oauth2/token
  cache:
    client:
      config:
        distributed: false
        cluster-name: dev3
        server-host: 127.0.0.1
        server-port: 5701
        near-cache-config:
          myMap:
            in-memory-format: object
            time-to-live-seconds: 10

server:
  servlet:
    context-path: /scm
  port: 8086
spring:
  datasource:
    url: jdbc:db2://10.10.4.104:50001/DBREFSW
    username: db2inst1
    password: db2inst1
    driver-class-name: com.ibm.db2.jcc.DB2Driver
  jpa:
    properties:
      hibernate:
        default_schema: REF
#  mvc:
#    servlet:
#      load-on-startup: 1
#      path: /
logging:
  config: classpath:logback-spring.xml
