
SCM_UAA_BASE_URL: ${SCM_UAA_PILOT_BASE_URL}
SCM_CACHE_CLUSTER_NAME: scm-cache-pilot
SCM_CACHE_ADDRESS: ${SCM_CACHE_PILOT_ADDRESS}

SCM_OBS_ROOT_DIR: ${SCM_UAA_PILOT_OBS_ROOT_DIR:/var/obs}
SCM_OBS_LOG_CONSOLE_ENABLED: false
SCM_OBS_LOG_FILE_ENABLED: true
SCM_OBS_TRACE_ENABLED: true
SCM_OBS_TRACE_CONSOLE_ENABLED: false
SCM_OBS_TRACE_FILE_ENABLED: true
SCM_OBS_AUDIT_ENABLED: true
SCM_OBS_AUDIT_CONSOLE_ENABLED: false
SCM_OBS_AUDIT_FILE_ENABLED: true
SCM_OBS_HTTP_SERVER_ENABLED: false
SCM_OBS_HTTP_SERVER_MODE: channel-only
