package ir.daneshrefah.scm.core.integration.observability;

public final class RouteLogEvents {
    public static final String GATEWAY_ROUTE_CONSTRUCTION_STARTED = "GATEWAY_ROUTE_CONSTRUCTION_STARTED";
    public static final String GATEWAY_ROUTE_CONSTRUCTION_SKIPPED = "GATEWAY_ROUTE_CONSTRUCTION_SKIPPED";
    public static final String GATEWAY_CHANNEL_RESOLVED = "GATEWAY_CHANNEL_RESOLVED";
    public static final String GATEWAY_TARGET_KIND_RESOLVED = "GATEWAY_TARGET_KIND_RESOLVED";
    public static final String GATEWAY_ROUTE_PLAN_RESOLVED = "GATEWAY_ROUTE_PLAN_RESOLVED";
    public static final String GATEWAY_INBOUND_ROUTE_FACTORY_RESOLVED = "GATEWAY_INBOUND_ROUTE_FACTORY_RESOLVED";
    public static final String GATEWAY_ROUTE_REGISTRATION_STARTED = "GATEWAY_ROUTE_REGISTRATION_STARTED";
    public static final String GATEWAY_ROUTE_REGISTERED = "GATEWAY_ROUTE_REGISTERED";
    public static final String GATEWAY_ROUTE_CONSTRUCTION_COMPLETED = "GATEWAY_ROUTE_CONSTRUCTION_COMPLETED";
    public static final String GATEWAY_ROUTE_CONSTRUCTION_FAILED = "GATEWAY_ROUTE_CONSTRUCTION_FAILED";
    public static final String GATEWAY_REQUEST_RECEIVED = "GATEWAY_REQUEST_RECEIVED";
    public static final String GATEWAY_CONTRACT_RESOLUTION_STARTED = "GATEWAY_CONTRACT_RESOLUTION_STARTED";
    public static final String GATEWAY_CONTRACT_RESOLVED = "GATEWAY_CONTRACT_RESOLVED";
    public static final String GATEWAY_REQUEST_DECODE_STARTED = "GATEWAY_REQUEST_DECODE_STARTED";
    public static final String GATEWAY_REQUEST_DECODED = "GATEWAY_REQUEST_DECODED";
    public static final String GATEWAY_DISPATCH_STARTED = "GATEWAY_DISPATCH_STARTED";
    public static final String GATEWAY_DISPATCH_FINISHED = "GATEWAY_DISPATCH_FINISHED";
    public static final String GATEWAY_RESPONSE_HANDLER_STARTED = "GATEWAY_RESPONSE_HANDLER_STARTED";
    public static final String GATEWAY_RESPONSE_HANDLER_FINISHED = "GATEWAY_RESPONSE_HANDLER_FINISHED";
    public static final String GATEWAY_FAULT_ENCODING_STARTED = "GATEWAY_FAULT_ENCODING_STARTED";
    public static final String GATEWAY_FAULT_ENCODED = "GATEWAY_FAULT_ENCODED";
    public static final String GATEWAY_FAULT_ENCODING_FAILED = "GATEWAY_FAULT_ENCODING_FAILED";
    public static final String GATEWAY_REQUEST_SUCCEEDED = "GATEWAY_REQUEST_SUCCEEDED";
    public static final String GATEWAY_REQUEST_FAILED = "GATEWAY_REQUEST_FAILED";

    public static final String SERVICE_ROUTE_CONSTRUCTION_STARTED = "SERVICE_ROUTE_CONSTRUCTION_STARTED";
    public static final String SERVICE_ROUTE_CONSTRUCTION_SKIPPED = "SERVICE_ROUTE_CONSTRUCTION_SKIPPED";
    public static final String SERVICE_GATEWAY_CHANNEL_RESOLVED = "SERVICE_GATEWAY_CHANNEL_RESOLVED";
    public static final String SERVICE_TARGET_KIND_RESOLVED = "SERVICE_TARGET_KIND_RESOLVED";
    public static final String SERVICE_ROUTE_PLAN_RESOLVED = "SERVICE_ROUTE_PLAN_RESOLVED";
    public static final String SERVICE_ROUTE_REGISTRATION_STARTED = "SERVICE_ROUTE_REGISTRATION_STARTED";
    public static final String SERVICE_ROUTE_REGISTERED = "SERVICE_ROUTE_REGISTERED";
    public static final String SERVICE_ROUTE_CONSTRUCTION_COMPLETED = "SERVICE_ROUTE_CONSTRUCTION_COMPLETED";
    public static final String SERVICE_ROUTE_CONSTRUCTION_FAILED = "SERVICE_ROUTE_CONSTRUCTION_FAILED";
    public static final String SERVICE_REQUEST_RECEIVED = "SERVICE_REQUEST_RECEIVED";
    public static final String SERVICE_GUARD_CHECK_STARTED = "SERVICE_GUARD_CHECK_STARTED";
    public static final String SERVICE_GUARD_CHECK_PASSED = "SERVICE_GUARD_CHECK_PASSED";
    public static final String SERVICE_GUARD_CHECK_FAILED = "SERVICE_GUARD_CHECK_FAILED";
    public static final String SERVICE_PLUGIN_STARTED = "SERVICE_PLUGIN_STARTED";
    public static final String SERVICE_PLUGIN_FINISHED = "SERVICE_PLUGIN_FINISHED";
    public static final String SERVICE_PLUGIN_FAILED = "SERVICE_PLUGIN_FAILED";
    public static final String SERVICE_TARGET_ROUTING_STARTED = "SERVICE_TARGET_ROUTING_STARTED";
    public static final String SERVICE_TARGET_ROUTING_FINISHED = "SERVICE_TARGET_ROUTING_FINISHED";
    public static final String SERVICE_RESPONSE_PROCESSING_STARTED = "SERVICE_RESPONSE_PROCESSING_STARTED";
    public static final String SERVICE_RESPONSE_PROCESSING_FINISHED = "SERVICE_RESPONSE_PROCESSING_FINISHED";
    public static final String SERVICE_REQUEST_SUCCEEDED = "SERVICE_REQUEST_SUCCEEDED";
    public static final String SERVICE_REQUEST_FAILED = "SERVICE_REQUEST_FAILED";

    public static final String OPERATION_ROUTE_CONSTRUCTION_STARTED = "OPERATION_ROUTE_CONSTRUCTION_STARTED";
    public static final String OPERATION_ROUTE_PLAN_RESOLVED = "OPERATION_ROUTE_PLAN_RESOLVED";
    public static final String OPERATION_ROUTE_REGISTERED = "OPERATION_ROUTE_REGISTERED";
    public static final String OPERATION_ROUTE_SKIPPED = "OPERATION_ROUTE_SKIPPED";
    public static final String OPERATION_ROUTE_CONSTRUCTION_COMPLETED = "OPERATION_ROUTE_CONSTRUCTION_COMPLETED";
    public static final String OPERATION_ROUTE_CONSTRUCTION_FAILED = "OPERATION_ROUTE_CONSTRUCTION_FAILED";

    private RouteLogEvents() {
    }
}
