package ir.daneshrefah.scm.common.model.error;

/**
 * @apiNote Use ExceptionResolver pattern. using constant exception code
 * can occur code duplication.
 * @see ir.daneshrefah.scm.common.error.ErrorMapping
 */
@Deprecated
public interface ErrorCodes {

     int ERROR_CODE_SYSTEM_ERROR = 1001;
     int ERROR_CODE_AUTHENTICATION_REQUIRED = 1002;
     int ERROR_CODE_AUTHENTICATION_TRANSACTION_REQUIRED = 1003;
     int ERROR_CODE_AUTHENTICATION_FAILED = 1004;
     int ERROR_CODE_TRANSACTION_AUTHENTICATION_FAILED = 1005;
     int ERROR_CODE_DUPLICATE_RECORD = 1006;
     int ERROR_CODE_INPUT_IS_INVALID = 1007;
     int ERROR_CODE_DATE_INPUT_IS_INVALID = 1008;
     int ERROR_CODE_MISSING_REQUIRED_INPUT = 1009;
     int ERROR_CODE_TOO_MANY_RECORD_FOUND = 1010;
     int ERROR_CODE_ACCESS_DENIED = 1011;
     int ERROR_CODE_INVALID_REMOTE_RESPONSE = 1012;
     int ERROR_CODE_UNSUCCESSFUL_PROVIDER_RESPONSE = 1013;
     int ERROR_CODE_REQUEST_IS_NULL = 1014;
     int ERROR_CODE_SOCKET_TIMEOUT = 1015;
     int ERROR_CODE_UNKNOWN_HOST = 1016;
     int ERROR_CODE_HOST_UNREACHABLE = 1017;
     int ERROR_CODE_HOST_TIMEOUT = 1037;
     int ERROR_CODE_NO_RECORD_FOUND = 1018;
     int ERROR_CODE_NOT_SUPPORT_DATA = 1019;
     int ERROR_CODE_INVALID_REQUEST_FORMAT = 1020;
     int ERROR_CODE_VALIDATION_NO_DATA_CHANGE = 1021;
     int ERROR_CODE_JAVA_SERVICE_IS_DISABLED = 1022;
     int ERROR_CODE_VALIDATION_SERVICE_NOT_ASSIGNED_TO_TERMINAL = 1023;
     int ERROR_CODE_VALIDATION_SERVICE_NOT_FOUND = 1024;
     int ERROR_CODE_PROVIDER_UNKNOWN_EXCEPTION = 1025;
     int ERROR_CODE_TRANSFORMER_UNKNOWN_EXCEPTION = 1026;
     int ERROR_CODE_JAVA_SERVICE_METHOD_NOT_FOUND = 1027;
     int ERROR_CODE_VIOLATION_DATA_INTEGRITY = 1028;
     int ERROR_CODE_VALIDATION_GLOBAL = 1029;
     int ERROR_CODE_HTTP_METHOD_NOT_ALLOWED = 1030;
     int ERROR_CODE_MISMATCH_REQUIRED_INPUT = 1031;
     int ERROR_CODE_JAVA_SERVICE_CLASS_NOT_FOUND = 1032;
     int ERROR_CODE_VALIDATION_SERVICE_JAVA_CLASS_IS_EMPTY = 1033;
     int ERROR_CODE_VALIDATION_SERVICE_PARAMETER_CLASS_NOT_FOUND = 1034;
     int ERROR_CODE_VALIDATION_SERVICE_CODE_IS_INVALID = 1035;
     int ERROR_CODE_VALIDATION_PERSON_NOT_FOUND = 1036;
     int ERROR_CODE_PAYLOAD_MERGE_ERROR = 1037;
     int ERROR_CODE_INVALID_TARGET_URL = 1038;
     int ERROR_CODE_INVALID_SERVICE_METADATA = 1039;
     int ERROR_CODE_VALIDATION_PROVIDER_CUSTOMER_NOT_FOUND = 1104;
     int ERROR_CODE_VALIDATION_PROVIDER_ASSET_NOT_FOUND = 1105;






     int ERROR_CODE_ASSET_IS_EMPTY = 1101;
     int ERROR_CODE_ASSET_NOT_ASSIGNED = 1102;
     int ERROR_CODE_SERVICE_NOT_ASSIGNED_TO_USER = 1103;

     int ERROR_CODE_NOTIFICATION_CONCURRENT_EXCEPTION = 1200;
     int ERROR_CODE_NOTIFICATION_TEMPLATE_NOT_FOUND = 1201;
     int ERROR_CODE_NOTIFICATION_BODY_PROCESSOR_NOT_FOUND = 1202;
     int ERROR_CODE_NOTIFICATION_BODY_PROCESSING_EXCEPTION = 1203;
     int ERROR_CODE_NOTIFICATION_NOT_SUPPORTED_BODY_PROCESSOR_EXCEPTION = 1204;

     int ERROR_CODE_RECORD_VERSION_EXCEPTION = 1205;
     int ERROR_CODE_TASK_ASSIGMENT_EXCEPTION = 1206;
     int ERROR_CODE_TASK_NOT_FOUND_EXCEPTION = 1206;
     int ERROR_CODE_PROCESS_FILE_NOT_FOUND_EXCEPTION = 1207;



//     int ERROR_CODE_ACCESS_PARAMETER_IS_EMPTY = 1006;
//     int ERROR_CODE_TERMINAL_CODE_IS_EMPTY = 1007;
//     int ERROR_CODE_TERMINAL_CODE_IS_INVALID = 1008;
//     int ERROR_CODE_INVALID_PROVIDER_RESPONSE = 1016;
//     int ERROR_CODE_JPA_SYSTEM = 1022;
//     int ERROR_CODE_VALIDATION_BODY_IS_EMPTY = 1050;
//     int ERROR_CODE_VALIDATION_SERVICE_IMPLEMENTATION_TYPE_IS_EMPTY = 1052;
//     int ERROR_CODE_VALIDATION_SERVICE_IMPLEMENTATION_TYPE_IS_INVALID = 1053;
//     int ERROR_CODE_VALIDATION_SERVICE_CODE_IS_EMPTY = 1054;
//     int ERROR_CODE_VALIDATION_SERVICE_TITLE_IS_EMPTY = 1056;
//     int ERROR_CODE_VALIDATION_SERVICE_TYPE_IS_EMPTY = 1057;
//     int ERROR_CODE_VALIDATION_SERVICE_EXTERNAL_PROVIDER_IS_EMPTY = 1059;
//     int ERROR_CODE_VALIDATION_SERVICE_EXTERNAL_PROVIDER_IS_INVALID = 1066;
//     int ERROR_CODE_VALIDATION_SERVICE_EXTERNAL_PROVIDER_NOT_SUPPORT_CUSTOMER = 1070;
//     int ERROR_CODE_VALIDATION_SERVICE_ID_IS_EMPTY = 1060;
//     int ERROR_CODE_VALIDATION_SERVICE_ID_IS_INVALID = 1061;
//     int ERROR_CODE_VALIDATION_SERVICE_ID_NOT_FOUND = 1072;
//     int ERROR_CODE_VALIDATION_OBJECT_NOT_FOUND = 1062;
//     int ERROR_CODE_VALIDATION_TERMINAL_ID_IS_EMPTY = 1064;
//     int ERROR_CODE_VALIDATION_TERMINAL_ID_IS_INVALID = 1065;
//     int ERROR_CODE_VALIDATION_PERSON_ID_IS_EMPTY = 1068;
//     int ERROR_CODE_VALIDATION_PERSON_PROFILE_ID_IS_EMPTY = 1069;
//     int ERROR_CODE_VALIDATION_PERSON_TYPE_IS_EMPTY = 1073;
//     int ERROR_CODE_VALIDATION_PERSON_TYPE_IS_INVALID = 1074;
//     int ERROR_CODE_VALIDATION_PERSON_NATIONAL_ID_IS_EMPTY = 1075;
//     int ERROR_CODE_VALIDATION_PERSON_SUB_ORGANIZATION_ID_IS_EMPTY = 1076;
//     int ERROR_CODE_VALIDATION_PERSON_NATIONALITY_IS_EMPTY = 1077;
//     int ERROR_CODE_VALIDATION_PERSON_NATIONALITY_IS_INVALID = 1078;
//     int ERROR_CODE_VALIDATION_INVALID_INSTANT_FORMAT = 1071;
}
