SCM_CONFIG_ENABLED: true
SCM_CONFIG_SERVER_IMPORT: configserver:${SCM_CONFIG_SERVER_URL:http://scm-config.scm.svc.cluster.local:8888/config}
SCM_CONFIG_FAIL_FAST: true
SCM_CONFIG_RETRY_MAX_ATTEMPTS: 10
SCM_CONFIG_RETRY_MAX_INTERVAL: 3000
