scm:
  metadata:
    namespace: ${SCM_METADATA_NAMESPACE:local}
    instance-id: ${SCM_METADATA_INSTANCE_ID:local-scm-logging}
  observation:
    log:
      console:
        enabled: true
    trace:
      console:
        enabled: true
    audit:
      console:
        enabled: true

SCM_SERVER_PORT: ${SERVER_PORT:9090}

SCM_CONFIG_ENABLED: false
SCM_CONFIG_SERVER_IMPORT: ""
SCM_CONFIG_FAIL_FAST: false

SCM_LOGGING_JMS_DEFAULT_DESTINATION: SCM2LOG
SCM_LOGGING_JMS_DESTINATION: SCM2LOG
SCM_LOGGING_MQ_QUEUE_MANAGER: CSQ1
SCM_LOGGING_MQ_CHANNEL: DEV.ADMIN.SVRCONN
SCM_LOGGING_MQ_HOST: 10.10.4.238
SCM_LOGGING_MQ_PORT: 11414
SCM_LOGGING_MQ_CONN_NAME: 10.10.4.238(11414)
SCM_LOGGING_MQ_USERNAME: admin
SCM_LOGGING_MQ_PASSWORD: ${SCM_DEV_LOGGING_MQ_PASSWORD:passw0rd}

SCM_LOGGING_TRANSACTION_DB_ENABLED: true
SCM_LOGGING_TRANSACTION_DB_URL: jdbc:db2://10.10.4.104:50001/DBREFSW
SCM_LOGGING_TRANSACTION_DB_USERNAME: db2inst1
SCM_LOGGING_TRANSACTION_DB_PASSWORD: ${SCM_DEV_LOGGING_TRANSACTION_DB_PASSWORD:db2inst1}
SCM_LOGGING_TRANSACTION_DB_SCHEMA: REF
SCM_LOGGING_TRANSACTION_DB_MAX_CONNECTION: 10

SCM_LOGGING_TRACE_DB_ENABLED: true
SCM_LOGGING_TRACE_DB_URL: jdbc:db2://10.15.27.82:446/DSNALOC
SCM_LOGGING_TRACE_DB_USERNAME: casadm
SCM_LOGGING_TRACE_DB_PASSWORD: ${SCM_DEV_LOGGING_TRACE_DB_PASSWORD:a}
SCM_LOGGING_TRACE_DB_SCHEMA: REF
SCM_LOGGING_TRACE_DB_MAX_CONNECTION: 10

SCM_LOGGING_MESSAGE_DB_ENABLED: true
SCM_LOGGING_MESSAGE_DB_URL: jdbc:db2://10.15.1.197:50000/DBREFSW
SCM_LOGGING_MESSAGE_DB_USERNAME: pwausr
SCM_LOGGING_MESSAGE_DB_PASSWORD: ${SCM_DEV_LOGGING_MESSAGE_DB_PASSWORD:pwausr}
SCM_LOGGING_MESSAGE_DB_SCHEMA: LOGGER
SCM_LOGGING_MESSAGE_DB_MAX_CONNECTION: 10

SCM_CACHE_DISTRIBUTED: true
SCM_CACHE_CLUSTER_NAME: scm-cache-dev
SCM_CACHE_ADDRESS: 10.10.4.125:5701
