spring:
  application:
    name: Logging-server
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:db2://10.15.27.82:546/DSNBLOC
    username: casadm
    password: a
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    hikari:
      maximum-pool-size: 10
      schema: REF
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9090

scm:
  log:
    chunkSize: 27128
  jms:
    log:
      destination: SCM2LOG
      queueManager: CSQ1
      channel: DEV.ADMIN.SVRCONN
      host: 10.10.4.238
      port: 11414
      username: admin
      password: passw0rd
  cache:
    client:
      distributed: true
      config:
        cluster-name: dev3
        network-config:
          addresses:
            - 10.10.4.125:5701
