spring:
  application:
    name: Logging-server
  datasource:
    url: jdbc:db2://10.10.4.104:50001/DBREFSW
    username: db2inst1
    password: db2inst1
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    hikari:
      maximum-pool-size: 10
      schema: REF
  cloud:
    config:
      enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    config: logback-spring.xml
    level:
      root: INFO
      ir.daneshrefah: DEBUG # Set the logging level for your package
      org.hibernate.SQL: DEBUG # Just for development
      org.hibernate.type.descriptor.sql: TRACE # Just for development
      org.hibernate.orm.jdbc.bind: TRACE # Just for development
    file:
      path: /log # Specify the directory path for logs
      name: log-server.log
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" # Define the log pattern
server:
  port: 9090

scm:
  jms:
    log:
      destination: SCM2LOG
      queueManager: CSQ1
      channel: DEV.ADMIN.SVRCONN
      host: 10.10.4.238
      port: 11414
      username: admin
      password: passw0rd
  log:
    file-directory: log
    rolling-archive-directory: archive
    file-name: ${spring.application.name}.log
    log-pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %msg%n"
    file-name-pattern: "%d{yyyy-MM-dd}.%i.log"
    file-size: 1MB  #Max size of each log file
    keep-log-history: 30 #Keep up to 30 days of log files
    listener:
      enabled: true
  cache:
    client:
      distributed: true
      config:
        cluster-name: dev3
        network-config:
          addresses:
            - 10.10.4.125:5701