spring:
  application:
    name: Logging-server
  cloud:
    config:
      enabled: false
  jms:
    template:
      default-destination: SCM2LOG
      delivery-mode: NON_PERSISTENT
      qos-enabled: false
      time-to-live: 172800000   # 2 days
      receive-timeout: 5000     # optional
    listener:
      min-concurrency: 5
      max-concurrency: 30
server:
  port: 9090
scm:
  log:
    root-level: INFO
    console:
      enabled: false
    level:
      spring: INFO
      hibernate: WARN
    app:
      file-directory: /var/log/app
      rolling-archive-directory: /var/log/app/archive
      max-history-days: 50
      max-file-size: 200MB
      total-size-cap: 10GB
    transactionLogConverter:
      enabled: true
      versionRequirement: '>=7.20.0'
    logTraceConverter:
      enabled: true
      versionRequirement: '>=8.0.0'
    messageLogConverter:
      enabled: true
      versionRequirement: '>=8.0.0'
    chunkSize: 5600
    logSchedulerThreadPool:
       corePoolSize: 5
       maxPoolSize: 5
       fixedRate: 5000

  jms:
    log:
      destination: SCM2LOG
      queueManager: CSQ1
      channel: DEV.ADMIN.SVRCONN
      host: 10.10.4.238
      port: 11414
      username: admin
      password: passw0rd
  cache:
    client:
      distributed: true
      config:
        cluster-name: dev3
        network-config:
          addresses:
            - 10.10.4.125:5701
  datasource:
    transactionLog:
      enabled: true
      url: jdbc:db2://10.10.4.104:50001/DBREFSW
      username: db2inst1
      password: db2inst1
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 10
      default-schema: REF
    logTrace:
      enabled: true
      url: jdbc:db2://10.15.27.82:446/DSNALOC
      username: casadm
      password: a
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 10
      default-schema: REF
    messageLog:
      enabled: true
      url: jdbc:db2://10.15.1.197:50000/DBREFSW
      username: pwausr
      password: pwausr
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 10
      default-schema: LOGGER
ibm:
  mq:
    queue-manager: CSQ1
    channel: DEV.ADMIN.SVRCONN
    conn-name: 10.10.4.238(11414)
    user: admin
    password: passw0rd

