CREATE TABLE SCM_TRANSACTION_LOG
(
    id                     BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CHANNEL_CODE           VARCHAR(255),
    TERMINAL_CODE          VARCHAR(255),
    CLIENT_ID              VARCHAR(255),
    CORRELATION_ID         VARCHAR(255),
    CLIENT_CORRELATION_ID  VARCHAR(36),
    CLIENT_FLOW_ID         VARCHAR(255),
    FLOW_ID                VARCHAR(36),
    MESSAGE_ID             VARCHAR(36),
    PARENT_MESSAGE_ID      VARCHAR(36),
    LEVEL                  INT,
    SERVICE_CODE           VARCHAR(255),
    NICKNAME               VARCHAR(255),
    USERNAME               VARCHAR(255),
    DELEGATOR_USERNAME     VARCHAR(255),
    DELEGATOR_NICKNAME     VARCHAR(255),
    HOST_ADDRESS           VARCHAR(255),
    EVENT_TYPE             VARCHAR(255),
    MESSAGE_STATUS         VARCHAR(255),
    START_TIME             TIMESTAMP,
    END_TIME               TIMESTAMP,
    DURATION_MILLS         BIGINT,
    VERSION                INT,
    CLIENT_IP_ADDRESS      VARCHAR(255),
    PROVIDER_CODE          VARCHAR(255),
    PROVIDER_RESPONSE_CODE VARCHAR(255),
    RESPONSE_STATUS_CODE   INT,
    EXCEPTION_CLASS_NAME   VARCHAR(255),
    METHOD_TYPE            VARCHAR(20),
    URL                    VARCHAR(255),
    PAYLOAD                CLOB,
    AMOUNT                 VARCHAR(255),
    CARD_NUMBER            VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE REF.SCM_AUDIT
(
    ID         BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY ,
    CREATOR    VARCHAR(255),
    MODIFY_BY  VARCHAR(255),
    CLASS_TYPE VARCHAR(255),
    AUDIT_TIME TIMESTAMP,
    REVISION_TYPE VARCHAR(255),
    PAYLOAD    CLOB
);