---
# Source: scm-config/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scm-config
  labels:
    helm.sh/chart: scm-config-8.5.4
    app.kubernetes.io/name: scm-config
    app.kubernetes.io/instance: scm-config
    app.kubernetes.io/version: "8.5.4"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: scm-config/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: scm-config-configmap
data:
  # Key-value pairs for your configuration
  SCM_CONFIG_SERVER_URL: "http://scm-config.scm.svc.cluster.local:8888/config"
  SPRING_CLOUD_CONFIG_URI: "http://scm-config.scm.svc.cluster.local:8888/config"
---
# Source: scm-config/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: scm-config
  labels:
    helm.sh/chart: scm-config-8.5.4
    app.kubernetes.io/name: scm-config
    app.kubernetes.io/instance: scm-config
    app.kubernetes.io/version: "8.5.4"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  externalIPs:
    - 10.10.4.121
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: scm-config
    app.kubernetes.io/instance: scm-config
---
# Source: scm-config/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scm-config
  labels:
    helm.sh/chart: scm-config-8.5.4
    app.kubernetes.io/name: scm-config
    app.kubernetes.io/instance: scm-config
    app.kubernetes.io/version: "8.5.4"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scm-config
      app.kubernetes.io/instance: scm-config
  template:
    metadata:
      labels:
        helm.sh/chart: scm-config-8.5.4
        app.kubernetes.io/name: scm-config
        app.kubernetes.io/instance: scm-config
        app.kubernetes.io/version: "8.5.4"
        app.kubernetes.io/managed-by: Helm
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: scm-config
      securityContext:
        {}
      containers:
        - name: scm-config
          securityContext:
            {}
          image: "reg.daneshrefah.ir/modern-banking/scm-app:8.5.4"
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_APPLICATION_NAME
              value: scm-config
            - name: VERSION
              value: 8.5.4
            - name: SERVER_PORT
              value: "8888"
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP




          resources:
            {}
          volumeMounts:
            - mountPath: /mnt/log
              name: log-volume
            - mountPath: /mnt/config-repo-server
              name: config-repo-server-volume
      volumes:
        - hostPath:
            path: /log
            type: DirectoryOrCreate
          name: log-volume
        - hostPath:
            path: /config-repo-server
            type: DirectoryOrCreate
          name: config-repo-server-volume
      nodeSelector:
        app: scm-config
      tolerations:
        - effect: NoSchedule
          key: daneshrefah.ir/group
          operator: Equal
          value: scm
