
SCM_DB_URL: ${SCM_CACHE_PROD_DB_URL}
SCM_DB_USERNAME: ${SCM_CACHE_PROD_DB_USERNAME}
SCM_DB_PASSWORD: ${SCM_CACHE_PROD_DB_PASSWORD}
SCM_DB_DRIVER: ${SCM_CACHE_PROD_DB_DRIVER:com.ibm.db2.jcc.DB2Driver}
SCM_DB_SCHEMA: ${SCM_CACHE_PROD_DB_SCHEMA}
SCM_DB_MAX_CONNECTION: ${SCM_CACHE_PROD_DB_MAX_CONNECTION:10}
SCM_CACHE_DB_SCHEMA: ${SCM_CACHE_PROD_DB_SCHEMA}

SCM_CACHE_CLUSTER_NAME: scm-cache-prod
SCM_CACHE_MEMBER_NAME: ${HOSTNAME:scm-cache-prod}
SCM_CACHE_KUBERNETES_ENABLED: true
SCM_CACHE_KUBERNETES_NAMESPACE: ${SCM_CACHE_PROD_KUBERNETES_NAMESPACE:scm}
SCM_CACHE_KUBERNETES_SERVICE_NAME: ${SCM_CACHE_PROD_KUBERNETES_SERVICE_NAME:scm-cache}
SCM_CACHE_MANAGEMENT_ENABLED: false

SCM_OBS_ROOT_DIR: ${SCM_CACHE_PROD_OBS_ROOT_DIR:/var/obs}
SCM_OBS_LOG_CONSOLE_ENABLED: false
SCM_OBS_LOG_FILE_ENABLED: true
SCM_OBS_TRACE_ENABLED: true
SCM_OBS_TRACE_CONSOLE_ENABLED: false
SCM_OBS_TRACE_FILE_ENABLED: true
SCM_OBS_AUDIT_ENABLED: false
SCM_OBS_AUDIT_CONSOLE_ENABLED: false
SCM_OBS_AUDIT_FILE_ENABLED: true
SCM_OBS_HTTP_SERVER_ENABLED: false
SCM_OBS_HTTP_SERVER_MODE: channel-only
