-------------------------------------------------------------------------------------------------------

CREATE TABLE TBL_SNT_MESSAGE_TEMPLATE
(
    MESSAGE_TEMPLATE_ID DECIMAL(22) GENERATED ALWAYS AS IDENTITY NOT NULL,
    CREATOR             VARCHAR(255),
    LAST_EDITOR         VARCHAR(255),
    CREATE_DATE         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE      TIMESTAMP,
    CODE                VARCHAR(255),
    TITLE               VARCHAR(255),
    BODY                VARCHAR(255),
    IS_SYSTEMIC         SMALLINT  DEFAULT 0                      NOT NULL,
    CONSTRAINT PK_TBL_SNT_MESSAGE_TEMPLATE PRIMARY KEY (MESSAGE_TEMPLATE_ID)
);

----------------------------------------------------------------------------------------------

CREATE TABLE TBL_SNT_NOTIFICATION_LOG
(
    NOTIFICATION_LOG_ID DECIMAL(22) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TERMINAL_CODE       VARCHAR(255),
    USERNAME            VARCHAR(255),
    RECIPIENT           VARCHAR(255),
    MEDIA               VARCHAR(255),
    DATA                VARCHAR(255),
    MESSAGE_TEMPLATE_ID DECIMAL(22)                              NOT NULL,
    BODY                VARCHAR(255),
    STATUS              INTEGER,
    ERROR               VARCHAR(255),
    CONSTRAINT PK_TBL_SNT_NOTIFICATION_LOG PRIMARY KEY (NOTIFICATION_LOG_ID)
);

ALTER TABLE TBL_SNT_NOTIFICATION_LOG
    ADD CONSTRAINT UC_TBL_SNT_NOTIFICATION_LOG_MESSAGE_TEMPLATE UNIQUE (MESSAGE_TEMPLATE_ID);

ALTER TABLE TBL_SNT_NOTIFICATION_LOG
    ADD CONSTRAINT FK_TBL_SNT_NOTIFICATION_LOG_ON_MESSAGE_TEMPLATE FOREIGN KEY (MESSAGE_TEMPLATE_ID) REFERENCES TBL_SNT_MESSAGE_TEMPLATE (MESSAGE_TEMPLATE_ID);

---------------------------------------------------------------------------------------------------

CREATE TABLE SCM_NTF_NOTIFICATION_QUEUE
(
    NOTIFICATION_QUEUE_ID VARCHAR(255) NOT NULL,
    MEDIA                 VARCHAR(255),
    MESSAGE_TEMPLATE_ID   DECIMAL(22),
    MESSAGE               VARCHAR(255),
    STATUS                INTEGER,
    EXPIRATION            TIMESTAMP,
    CONSTRAINT PK_SCM_NTF_NOTIFICATION_QUEUE PRIMARY KEY (NOTIFICATION_QUEUE_ID)
);

ALTER TABLE SCM_NTF_NOTIFICATION_QUEUE
    ADD CONSTRAINT FK_SCM_NTF_NOTIFICATION_QUEUE_ON_MESSAGE_TEMPLATE FOREIGN KEY (MESSAGE_TEMPLATE_ID) REFERENCES TBL_SNT_MESSAGE_TEMPLATE (MESSAGE_TEMPLATE_ID);