CREATE TABLE REF.TBL_SYN_DISTRIBUTED_LOCK
(
    ID                         VARCHAR(255) NOT NULL,
    LOCK_GROUP                 VARCHAR(255),
    LOCK_UNIQUE_PERSISTENCE_ID VARCHAR(255) NOT NULL ,
    INITIALIZED_TIME           TIMESTAMP,
    EXPIRATION_TIME            TIMESTAMP,
    CONSTRAINT PK_TBL_SYN_DISTRIBUTED_LOCK PRIMARY KEY (ID)
);

ALTER TABLE REF.TBL_SYN_DISTRIBUTED_LOCK
    ADD CONSTRAINT UC_TBL_SYN_DISTRIBUTED_LOCK_LOCK_UNIQUE_PERSISTENCE UNIQUE (LOCK_UNIQUE_PERSISTENCE_ID);