

scm:
  cif:
    url: http://scm-core.daneshrefah.ir/Service/
  security:
    key-store:
      name: config/keystore.p12
      password: password
      alias: selfsigned
    authenticationDatasource:
      url: jdbc:db2://10.10.4.104:50001/DBREFSW
      username: db2inst1
      password: db2inst1
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 10
      default-schema: REF
    activationDatasource:
      url: jdbc:db2://10.10.4.104:50001/DBREFSW
      username: db2inst1
      password: db2inst1
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 10
      default-schema: REF
  cache:
    client:
      config:
        distributed: true
        cluster-name: dev3
        server-host: 10.10.4.125
        server-port: 5701
  otp:
    time-to-live-minutes: 1
  notification:
    enabled: true
    sms:
      enabled: true
      ibm-mq:
        queue-manager: CSQ1
        channel: DEV.ADMIN.SVRCONN
        username: admin
        password: passw0rd
        port: 11414
        host: 10.10.4.238
  captcha:
    border:
      enabled: true
      color: '200,200,200'
      thickness: 1
    noise:
      color: '124,133,174'
    items:
      login:
        path: /public/login/captcha
        session:
          key: loginCaptchaKey
          date: loginCaptchaDate
        background:
          color-from: '81,89,130'
          color-to: '81,89,130'
        text-producer:
          font:
            color: '255,255,255'






#spring:
#  application:
#    name: scm-uaa
#  config:
#    import: configserver:http://localhost:8888/config
#  cloud:
#    config:
#      profile: default

spring:
  cloud:
    config:
      enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true




#spring:
#  datasource:
#    url: jdbc:db2://10.10.4.104:50001/DBREFSW
#    username: db2inst1
#    password: db2inst1
#    driver-class-name: com.ibm.db2.jcc.DB2Driver
#    hikari:
#      maximum-pool-size: 10

server:
  port: 8001
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /public/index.html
  api-docs:
    path: /public/v3/api-docs
