scm:
  cif:
    url: http://scm-core.daneshrefah.ir/Service/
  logging:
    datasource:
      url: jdbc:db2://10.15.27.82:446/DSNALOC
      username: casadm
      password: a
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 10
      default-schema: REF
      enabled: true
  security:
    client:
      default-role: ROLE_CLIENT
    key-store:
      name: config/keystore.p12
      password: password
      alias: selfsigned
    authenticationDatasource:
      url: jdbc:db2://10.15.27.82:446/DSNALOC
      username: casadm
      password: a
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 10
      default-schema: REF
    activationDatasource:
      url: jdbc:db2://10.15.1.197:50000/DBREFSW
      username: pwausr
      password: pwausr
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 10
      default-schema: MBUAA

    oauth:
      config:
        pwa:
          white-list-enabled: false
          activation:
            check-registry-token: true
            otp-code-trails-count: 5
            otp-code-expiration-minutes: 2
            rate-limit-count: 5
            rate-limit-blocked-time-minutes: 10
          login:
            rate-limit-count: 5
            rate-limit-blocked-time-minutes: 10
            token-change-warn-period-days: 31

  cache:
    client:
      distributed: true
      security:
        user-cache:
          enabled: true
          cache-name: user_cache
          key-expression: "#user.username + '::' + #user.user.terminalCode"
      caches:
        user_cache:
          type: remote
        session_cache:
          type: remote
        "jwt:jti":
          type: remote
        cache_otp:
          type: remote
      config:
        cluster-name: dev3
        network-config:
          addresses:
            - '10.10.4.125:5701'
  otp:
    time-to-live-minutes: 1
    jms:
      avacas:
        hostName: 10.15.1.185
        port: 1717
        channel: SYSTEM.ADMIN.SVRCONN
        queueManager: CSQ1
        username: Administrator
        password:
        sendQueueName: AVACAS2CM_R
        receiverQueueName: AVACAS2CM_L

    channel:
      id: 1
      channelCode: OTP
      jcaAlgorithm: RSA
      storeKey: storeKey-test
      password: 123456

  notification:
    enabled: true
    sms:
      enabled: true
      ibm-mq:
        queue-manager: CSQ1
        channel: SYSTEM.ADMIN.SVRCONN
        username: Administrator
        password: " "
        port: 1717
        host: 10.15.1.185
  captcha:
    border:
      enabled: true
      color: '200,200,200'
      thickness: 1
    noise:
      color: '124,133,174'
    items:
      login:
        path: /public/login/captcha
        session:
          key: loginCaptchaKey
          date: loginCaptchaDate
        background:
          color-from: '81,89,130'
          color-to: '81,89,130'
        text-producer:
          font:
            color: '255,255,255'

  log:
    trace:
      file-directory: log
      rolling-archive-directory: archive
      file-name: ${spring.application.name}.log
      log-pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %msg%n"
      file-name-pattern: "%d{yyyy-MM-dd}.%i.log"
      file-size: 1MB  #Max size of each log file
      keep-log-history: 30 #Keep up to 30 days of log files
      aspect:
        enable: true
    root-level: INFO
    console:
      enabled: false
    level:
      spring: INFO
      hibernate: WARN
    app:
      file-directory: /var/log/app
      rolling-archive-directory: /var/log/app/archive
      max-history-days: 50
      max-file-size: 200MB
      total-size-cap: 10GB
  jms:
    logout:
      enabled: true
      host: 10.15.1.185
      port: 1818
      channel: SYSTEM.ADMIN.SVRCONN
      queueManager: CSQ2
      username:
      password:
      topic: SUA/LOGOUT
  super-app:
    session-ttl: 3600_000


#spring:
#  application:
#    name: scm-uaa
#  config:
#    import: configserver:http://localhost:8888/config
#  cloud:
#    config:
#      profile: default

spring:
  cloud:
    config:
      enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: uaa



#spring:
#  datasource:
#    url: jdbc:db2://10.15.27.82:446/DSNALOC
#    username: casadm
#    password: a
#    driver-class-name: com.ibm.db2.jcc.DB2Driver
#    hikari:
#      maximum-pool-size: 10

server:
  port: 8000
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /public/index.html
  api-docs:
    path: /public/v3/api-docs

logging:
  level:
    org.hibernate.SQL: debug #just for develop
    org.hibernate.type.descriptor.sql: trace #just for develop
    org.hibernate.orm.jdbc.bind: trace #just for develop


service:
  shahkar:
    baseUrl: http://10.15.6.53:8088
    tokenPath: /connect/token
    inquiryPath: /gov/1.0/ShahkarService
    clientId: cm_develop
    clientSecret: 9jl48zohr0cqa6wnc54h
    grant_Type: client_credentials