scm:
  cache:
    client:
      config:
        distributed: true
        kubernetes:
          enabled: true
          name-space: scm
          service-name: scm-cache
          service-dns: scm-cache.scm.svc.cluster.local