scm:
  cif:
    url: http://scm-core.daneshrefah.ir/Service/
  logging:
    datasource:

      url: jdbc:db2://10.10.4.104:50001/DBREFSW
      username: db2inst1
      password: db2inst1
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 10
      default-schema: REF
      enabled: true
  security:
    client:
      default-role: ROLE_CLIENT
    key-store:
      name: config/keystore.p12
      password: password
      alias: selfsigned
    authenticationDatasource:
      url: jdbc:db2://10.10.4.104:50001/DBREFSW
      username: db2inst1
      password: db2inst1
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 10
      default-schema: REF
    activationDatasource:
      url: jdbc:db2://10.10.4.104:50001/DBREFSW
      username: db2inst1
      password: db2inst1
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 10
      default-schema: MBUAA
  cache:
    client:
      distributed: true
      config:
        cluster-name: dev3
        network-config:
          addresses:
            - 10.10.4.125:5701
  otp:
    time-to-live-minutes: 1
    jms:
      avacas:
        hostName: 10.15.1.185
        port: 1717
        channel: SYSTEM.ADMIN.SVRCONN
        queueManager: CSQ1
        username: Administrator
        password:
        sendQueueName: AVACAS2CM_R
        receiverQueueName: AVACAS2CM_L

    channel:
      id: 1
      channelCode: OTP
      jcaAlgorithm: RSA
      storeKey: storeKey-test
      password: 123456

  notification:
    enabled: true
    sms:
      enabled: true
      ibm-mq:
        queue-manager: CSQ1
        channel: DEV.ADMIN.SVRCONN
        username: admin
        password: passw0rd
        port: 11414
        host: 10.10.4.238
  captcha:
    border:
      enabled: true
      color: '200,200,200'
      thickness: 1
    noise:
      color: '124,133,174'
    items:
      login:
        path: /public/login/captcha
        session:
          key: loginCaptchaKey
          date: loginCaptchaDate
        background:
          color-from: '81,89,130'
          color-to: '81,89,130'
        text-producer:
          font:
            color: '255,255,255'

  log:
    file-directory: log
    rolling-archive-directory: archive
    file-name: ${spring.application.name}.log
    log-pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %msg%n"
    file-name-pattern: "%d{yyyy-MM-dd}.%i.log"
    file-size: 1MB  #Max size of each log file
    keep-log-history: 30 #Keep up to 30 days of log files
    aspect:
      enable: true
  jms:
    logout:
      host: 10.15.1.185
      port: 1818
      channel: SYSTEM.ADMIN.SVRCONN
      queueManager: CSQ2
      username:
      password:
      topic: SUA/LOGOUT
#spring:
#  application:
#    name: scm-uaa
#  config:
#    import: configserver:http://localhost:8888/config
#  cloud:
#    config:
#      profile: default

spring:
  cloud:
    config:
      enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: uaa



#spring:
#  datasource:
#    url: jdbc:db2://10.10.4.104:50001/DBREFSW
#    username: db2inst1
#    password: db2inst1
#    driver-class-name: com.ibm.db2.jcc.DB2Driver
#    hikari:
#      maximum-pool-size: 10

server:
  port: 8000
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /public/index.html
  api-docs:
    path: /public/v3/api-docs

logging:
  level:
    org.hibernate.SQL: debug #just for develop
    org.hibernate.type.descriptor.sql: trace #just for develop
    org.hibernate.orm.jdbc.bind: trace #just for develop