spring:
  config:
    import: ${SCM_CONFIG_IMPORT:optional:configserver:${SCM_CONFIG_SERVER_URL:${SPRING_CLOUD_CONFIG_URI:http://scm-config.scm.svc.cluster.local:8888/config}}}
  cloud:
    config:
      enabled: true
      uri: ${SCM_CONFIG_SERVER_URL:${SPRING_CLOUD_CONFIG_URI:http://scm-config.scm.svc.cluster.local:8888/config}}
      username: ${SCM_CONFIG_USERNAME:${SPRING_CLOUD_CONFIG_USERNAME:}}
      password: ${SCM_CONFIG_PASSWORD:${SPRING_CLOUD_CONFIG_PASSWORD:}}
      fail-fast: ${SCM_CONFIG_FAIL_FAST:true}
      retry:
        max-attempts: ${SCM_CONFIG_RETRY_MAX_ATTEMPTS:5}
        max-interval: ${SCM_CONFIG_RETRY_MAX_INTERVAL:3000}

scm:
  uaa:
    security:
      password:
        current-encoding-id: ${SCM_UAA_PASSWORD_CURRENT_ENCODING_ID:argon2id}
        legacy-default-matching-id: ${SCM_UAA_PASSWORD_LEGACY_DEFAULT_MATCHING_ID:legacy-md5}
    datasource:
      main:
        url: ${SCM_UAA_MAIN_DB_URL:}
        username: ${SCM_UAA_MAIN_DB_USERNAME:}
        password: ${SCM_UAA_MAIN_DB_PASSWORD:}
      activation:
        enabled: ${SCM_UAA_ACTIVATION_DB_ENABLED:true}
        url: ${SCM_UAA_ACTIVATION_DB_URL:}
        username: ${SCM_UAA_ACTIVATION_DB_USERNAME:}
        password: ${SCM_UAA_ACTIVATION_DB_PASSWORD:}
    cors:
      allowed-origin-patterns: ${SCM_UAA_CORS_ALLOWED_ORIGIN_PATTERNS:}
  log:
    app:
      file-directory: ${SCM_APP_LOG_DIRECTORY:/var/log/app}
      rolling-archive-directory: ${SCM_APP_LOG_ARCHIVE_DIRECTORY:/var/log/app/archive}
  observation:
    log:
      console:
        enabled: ${SCM_OBSERVATION_LOG_CONSOLE_ENABLED:false}
      file:
        directory: ${SCM_OBSERVATION_LOG_FILE_DIRECTORY:/var/log/app/obs/log}
        archive-directory: ${SCM_OBSERVATION_LOG_ARCHIVE_DIRECTORY:/var/log/app/obs/log/archive}
    trace:
      file:
        directory: ${SCM_OBSERVATION_TRACE_FILE_DIRECTORY:/var/log/app/obs/trace}
        archive-directory: ${SCM_OBSERVATION_TRACE_ARCHIVE_DIRECTORY:/var/log/app/obs/trace/archive}
    audit:
      file:
        directory: ${SCM_OBSERVATION_AUDIT_FILE_DIRECTORY:/var/log/app/obs/audit}
        archive-directory: ${SCM_OBSERVATION_AUDIT_ARCHIVE_DIRECTORY:/var/log/app/obs/audit/archive}
