

scm:
  cif:
    url: http://scm-core.daneshrefah.ir/Service/
  security:
    key-store:
      name: config/keystore.p12
      password: password
      alias: selfsigned
    authenticationDatasource:
      url: jdbc:db2://10.10.4.104:50001/DBREFSW
      username: db2inst1
      password: db2inst1
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 10
      default-schema: REF
    activationDatasource:
      url: jdbc:db2://10.10.4.104:50001/DBREFSW
      username: db2inst1
      password: db2inst1
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 6
      default-schema: MBUAA
  cache:
    client:
      config:
        distributed: false
  notification:
    enabled: true
    data-source:
      url: jdbc:db2://10.10.4.104:50001/DBREFSW
      username: db2inst1
      password: db2inst1
      driver-class-name: com.ibm.db2.jcc.DB2Driver
      max-connection: 10
      default-schema: REF




#spring:
#  application:
#    name: scm-uaa
#  config:
#    import: configserver:http://localhost:8888/config
#  cloud:
#    config:
#      profile: default




#spring:
#  datasource:
#    url: jdbc:db2://10.10.4.104:50001/DBREFSW
#    username: db2inst1
#    password: db2inst1
#    driver-class-name: com.ibm.db2.jcc.DB2Driver
#    hikari:
#      maximum-pool-size: 10

server:
  port: 8000
