CREATE TABLE REF.TBL_SUA_SCOPE
(
    SCOPE_ID       DECIMAL(22) GENERATED ALWAYS AS IDENTITY,
    CODE           VARCHAR(50)  NOT NULL,
    TITLE          VARCHAR(100) NOT NULL,
    CREATE_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATOR        VARCHAR(255),
    LAST_EDITOR    VARCHAR(255),
    PRIMARY KEY (SCOPE_ID)
);
INSERT INTO TBL_SUA_SCOPE (CODE, TITLE, CREATOR, LAST_EDITOR)
values ('session', 'ایجاد session', 'Reza Jamshidi', 'Reza Jamshidi');

CREATE TABLE REF.TBL_SUA_CLIENT_AUTHORIZATION_GRANT_TYPE
(
    CLIENT_AUTHORIZATION_GRANT_TYPE_ID DECIMAL(22) GENERATED ALWAYS AS IDENTITY,
    CLIENT_ID                          DECIMAL(22)         NOT NULL,
    GRANT_TYPE_CODE                    VARCHAR(100)        NOT NULL,
    CREATE_DATE                        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE                     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATOR                            VARCHAR(255),
    LAST_EDITOR                        VARCHAR(255),
    FOREIGN KEY (CLIENT_ID) REFERENCES REF.TBL_SUA_CLIENT (CLIENT_ID),
    UNIQUE (CLIENT_ID, GRANT_TYPE_CODE),
    PRIMARY KEY (CLIENT_AUTHORIZATION_GRANT_TYPE_ID)
);
INSERT INTO ref.tbl_sua_client_authorization_grant_type (CLIENT_ID, GRANT_TYPE_CODE, CREATOR, LAST_EDITOR)
VALUES (1, 'authorization_code', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO ref.tbl_sua_client_authorization_grant_type (CLIENT_ID, GRANT_TYPE_CODE, CREATOR, LAST_EDITOR)
VALUES (1, 'refresh_token', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO ref.tbl_sua_client_authorization_grant_type (CLIENT_ID, GRANT_TYPE_CODE, CREATOR, LAST_EDITOR)
VALUES (2, 'authorization_code', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO ref.tbl_sua_client_authorization_grant_type (CLIENT_ID, GRANT_TYPE_CODE, CREATOR, LAST_EDITOR)
VALUES (2, 'refresh_token', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO ref.tbl_sua_client_authorization_grant_type (CLIENT_ID, GRANT_TYPE_CODE, CREATOR, LAST_EDITOR)
VALUES (2, 'second_password', 'Reza Jamshidi', 'Reza Jamshidi');


CREATE TABLE REF.TBL_SUA_CLIENT
(
    CLIENT_ID                     DECIMAL(22) GENERATED ALWAYS AS IDENTITY,
    TITLE                         VARCHAR(512)        NOT NULL,
    CLIENT_IDENTIFIER             VARCHAR(256)        NOT NULL,
    CLIENT_SECRET                 VARCHAR(512)        NOT NULL,
    TERMINAL_CODE                 VARCHAR(50)         NOT NULL,
    CLIENT_AUTH_METHOD_BASIC      SMALLINT  DEFAULT 0 NOT NULL,
    CLIENT_AUTH_METHOD_POST       SMALLINT  DEFAULT 0 NOT NULL,
    CLIENT_AUTH_METHOD_SEC_JWT    SMALLINT  DEFAULT 0 NOT NULL,
    CLIENT_AUTH_METHOD_KEY_JWT    SMALLINT  DEFAULT 0 NOT NULL,
--     AUTH_GRANT_AUTHORIZATION_CODE SMALLINT  DEFAULT 0 NOT NULL,
--     AUTH_GRANT_REFRESH_TOKEN      SMALLINT  DEFAULT 0 NOT NULL,
--     AUTH_GRANT_CLIENT_CREDENTIAL  SMALLINT  DEFAULT 0 NOT NULL,
--     AUTH_GRANT_FIRST_PASSWORD     SMALLINT  DEFAULT 0 NOT NULL,
--     AUTH_GRANT_SECOND_PASSWORD    SMALLINT  DEFAULT 0 NOT NULL,
    REDIRECT_URIS                 VARCHAR(1024)       NOT NULL,
    REQUIRE_AUTHORIZATION_CONSENT SMALLINT  DEFAULT 0 NOT NULL,
    REQUIRE_CLIENT_AUTHENTICATION SMALLINT  DEFAULT 0 NOT NULL,
    REQUIRE_PROOF_KEY             SMALLINT  DEFAULT 0 NOT NULL,
    CHECK_VERSION                 SMALLINT  DEFAULT 0 NOT NULL,
    CHECK_ACTIVATION              SMALLINT  DEFAULT 0 NOT NULL,
    SESSION_TIME_TO_LIVE_MINUTE   SMALLINT            NOT NULL,
    CREATE_DATE                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE                TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATOR                       VARCHAR(255),
    LAST_EDITOR                   VARCHAR(255),
    UNIQUE (CLIENT_IDENTIFIER),
    PRIMARY KEY (CLIENT_ID)
);
insert into TBL_SUA_CLIENT (TITLE, CLIENT_IDENTIFIER, CLIENT_SECRET, TERMINAL_CODE, CLIENT_AUTH_METHOD_BASIC,
                            CLIENT_AUTH_METHOD_POST, CLIENT_AUTH_METHOD_SEC_JWT, CLIENT_AUTH_METHOD_KEY_JWT,
                            REDIRECT_URIS, REQUIRE_AUTHORIZATION_CONSENT, REQUIRE_CLIENT_AUTHENTICATION, REQUIRE_PROOF_KEY, CHECK_VERSION,
                            CHECK_ACTIVATION, SESSION_TIME_TO_LIVE_MINUTE, CREATOR, LAST_EDITOR)
values ('Internet Bank', 'IB', '{noop}myClientSecretValue', 'IB', 0, 0, 0, 0, 'http://127.0.0.1:8080/authorized', 1, 0, 0, 0, 0, 1000, 'Reza Jamshidi', 'Reza Jamshidi');
insert into TBL_SUA_CLIENT (TITLE, CLIENT_IDENTIFIER, CLIENT_SECRET, TERMINAL_CODE, CLIENT_AUTH_METHOD_BASIC,
                            CLIENT_AUTH_METHOD_POST, CLIENT_AUTH_METHOD_SEC_JWT, CLIENT_AUTH_METHOD_KEY_JWT,
                            REDIRECT_URIS, REQUIRE_AUTHORIZATION_CONSENT, REQUIRE_CLIENT_AUTHENTICATION,
                            REQUIRE_PROOF_KEY, CHECK_VERSION, CHECK_ACTIVATION, SESSION_TIME_TO_LIVE_MINUTE,
                            CREATOR, LAST_EDITOR)
values ('Channel Manager', 'SCM', '{noop}myClientSecretValue', 'SCM', 1, 0, 0, 0, 'http://localhost', 1, 0, 0, 0, 0, 1000, 'Reza Jamshidi', 'Reza Jamshidi');

CREATE TABLE REF.TBL_SUA_CLIENT_SCOPE
(
    CLIENT_SCOPE_ID DECIMAL(22) GENERATED ALWAYS AS IDENTITY,
    CLIENT_ID       DECIMAL(22) NOT NULL,
    SCOPE_ID        DECIMAL(22) NOT NULL,
    CREATE_DATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATOR         VARCHAR(255),
    LAST_EDITOR     VARCHAR(255),
    FOREIGN KEY (CLIENT_ID) REFERENCES REF.TBL_SUA_CLIENT (CLIENT_ID),
    FOREIGN KEY (SCOPE_ID) REFERENCES REF.TBL_SUA_SCOPE (SCOPE_ID),
    PRIMARY KEY (CLIENT_SCOPE_ID)
);

CREATE TABLE REF.TBL_SUA_CLIENT_AUTHORITY
(
    CLIENT_AUTHORITY_ID DECIMAL(22) GENERATED ALWAYS AS IDENTITY,
    CLIENT_ID       DECIMAL(22) NOT NULL,
    ROLE_ID         SMALLINT NOT NULL,
    CREATE_DATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATOR         VARCHAR(255),
    LAST_EDITOR     VARCHAR(255),
    FOREIGN KEY (CLIENT_ID) REFERENCES REF.TBL_SUA_CLIENT (CLIENT_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES REF.ROLE (ROLE_ID),
    UNIQUE (CLIENT_ID, ROLE_ID),
    PRIMARY KEY (CLIENT_AUTHORITY_ID)
);

-- This table is equivalent to the table 'MBUAA.CLIENT' in the old system.
CREATE TABLE REF.TBL_SUA_CLIENT_VERSION
(
    CLIENT_VERSION_ID DECIMAL(22) GENERATED ALWAYS AS IDENTITY,
    CLIENT_ID         DECIMAL(22)         NOT NULL,
    VERSION           VARCHAR(100)        NOT NULL,
    IS_FORCED         SMALLINT  DEFAULT 0 NOT NULL,
    SIGNATURE         VARCHAR(255),
    STATUS            SMALLINT            NOT NULL,
    CREATE_DATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATOR           VARCHAR(255),
    LAST_EDITOR       VARCHAR(255),
    FOREIGN KEY (CLIENT_ID) REFERENCES REF.TBL_SUA_CLIENT (CLIENT_ID),
    UNIQUE (CLIENT_ID, VERSION),
    PRIMARY KEY (CLIENT_VERSION_ID)
);


-- SELECT * FROM MBUAA.CLIENT_INFO; -- User Activation where ACTIVATED = 1, link to CLIENT By CLIENT_ID