package ir.daneshrefah.scm.provider.shetab.iso.util;

public enum MTI {

    AUTHORIZATION_ADVICE_REQUEST_COMMAND("1100"),
    AUTHORIZATION_ADVICE_RESPONSE_COMMAND("1110"),
    TRANSFER_REQUEST_COMMAND("1200"),
    TRANSFER_RESPONSE_COMMAND("1210"),
    TRANSFER_CONFIRMATION_REQUEST_COMMAND("1220"),
    TRANSFER_CONFIRMATION_RESPONSE_COMMAND("1230"),
    DYNAMIC_PASSWORD_INQUIRY_REQUEST_COMMAND("1300"),
    DYNAMIC_PASSWORD_INQUIRY_RESPONSE_COMMAND("1310"),
    TRANSFER_REVERSAL_REQUEST_COMMAND("1420"),
    TRANSFER_REVERSAL_RESPONSE_COMMAND("1430"),
    RECONCILLIATION_REQUEST_COMMAND("1520"),
    RECONCILLIATION_RESPONSE_COMMAND("1530"),
    ACCOUNT_LIST_REQUEST_COMMAND("1604"),
    ACCOUNT_LIST_RESPONSE_COMMAND("1614"),
    NETWORK_MANAGEMENT_REQUEST_COMMAND("1804"),
    NETWORK_MANAGEMENT_RESPONSE_COMMAND("1814");

    private String code;

    MTI(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
