

spring:
  application:
    name: scm-cache
  config:
    import: configserver:http://localhost:8888/config
  cloud:
    config:
      profile: default



springdoc:
  api-docs:
    enabled: true
  packages-to-scan: ir.daneshrefah.scm.cache.rest

