SPRING_CLOUD_CONFIG_SERVER_URI: http://10.10.4.125:8888/config
spring:
  config:
    import: 'optional:configserver:'
    activate:
      on-profile: dev
  cloud:
    config:
      username: scm
      password: scm
      name: cache
      enabled: true
      uri: ${SPRING_CLOUD_CONFIG_SERVER_URI}
      retry:
        max-attempts: 10
        max-interval: 3000