CREATE TABLE REF.TBL_CHE_LIST_CONFIG
(
    INSTANCE_ID             VARCHAR(36) NOT NULL PRIMARY KEY ,
    INSTANCE_NAME           VARCHAR(64) NOT NULL,
    STATISTICS_ENABLED      SMALLINT,
    BACKUP_COUNT            INTEGER,
    ASYNC_BACKUP_COUNT      INTEGER,
    MAX_SIZE                INTEGER,
    MERGE_POLICY_BATCH_SIZE INTEGER
);

CREATE TABLE REF.TBL_CHE_MAP_CONFIG
(
    INSTANCE_ID              VARCHAR(36) NOT NULL PRIMARY KEY ,
    INSTANCE_NAME            VARCHAR(64) NOT NULL,
    STATISTICS_ENABLED       SMALLINT,
    TIME_TO_LIVE_SECONDS     INTEGER,
    BACK_UP_COUNT            INTEGER,
    ASYNC_BACKUP_COUNT       INTEGER,
    MAX_IDLE_SECONDS         INTEGER,
    EVICTION_SIZE            INTEGER,
    EVICTION_MAX_SIZE_POLICY INTEGER

);

CREATE TABLE REF.TBL_CHE_MULTI_MAP_CONFIG
(
    INSTANCE_ID                 VARCHAR(36) NOT NULL PRIMARY KEY ,
    INSTANCE_NAME               VARCHAR(64) NOT NULL,
    STATISTICS_ENABLED          SMALLINT,
    BINARY_ENABLED              SMALLINT,
    BACKUP_COUNT                INTEGER,
    ASYNC_BACKUP_COUNT          INTEGER,
    SPLIT_BRAIN_PROTECTION_NAME VARCHAR(64),
    VALUE_COLLECTION_TYPE       varchar(64)

);

CREATE TABLE REF.TBL_CHE_QUEUE_CONFIG
(
    INSTANCE_ID                    VARCHAR(36) NOT NULL PRIMARY KEY ,
    INSTANCE_NAME                  VARCHAR(64) NOT NULL,
    STATISTICS_ENABLED             SMALLINT,
    BACKUP_COUNT                   INTEGER,
    ASYNC_BACKUP_COUNT             INTEGER,
    MAX_SIZE                       INTEGER,
    EMPTY_QUEUE_TTL                INTEGER,
    PRIORITY_COMPARATOR_CLASS_NAME VARCHAR(128)
);

CREATE TABLE REF.TBL_CHE_REPLICATED_MAP_CONFIG
(
    INSTANCE_ID                 VARCHAR(36) NOT NULL PRIMARY KEY ,
    INSTANCE_NAME               VARCHAR(64) NOT NULL,
    STATISTICS_ENABLED          SMALLINT,
    ASYNC_FILL_UP_ENABLED       SMALLINT,
    IN_MEMORY_FORMAT            INTEGER,
    SPLIT_BRAIN_PROTECTION_NAME VARCHAR(64)
);

CREATE TABLE REF.TBL_CHE_SET_CONFIG
(
    INSTANCE_ID         VARCHAR(36) NOT NULL PRIMARY KEY ,
    INSTANCE_NAME       VARCHAR(64) NOT NULL,
    STATISTICS_ENABLED  SMALLINT,
    MAX_SIZE            INTEGER,
    ASYNC_BACKUP_COUNT  INTEGER,
    BACKUP_COUNT        INTEGER
);

CREATE TABLE REF.TBL_CHE_TOPIC_CONFIG
(
    INSTANCE_ID             VARCHAR(36) NOT NULL PRIMARY KEY ,
    INSTANCE_NAME           VARCHAR(64) NOT NULL,
    STATISTICS_ENABLED      SMALLINT,
    GLOBAL_ORDERING_ENABLED SMALLINT,
    MULTI_THREADING_ENABLED SMALLINT
);

INSERT INTO REF.TBL_CHE_MAP_CONFIG (INSTANCE_ID, INSTANCE_NAME, STATISTICS_ENABLED, TIME_TO_LIVE_SECONDS, BACK_UP_COUNT,
                                    ASYNC_BACKUP_COUNT, MAX_IDLE_SECONDS, EVICTION_SIZE, EVICTION_MAX_SIZE_POLICY)
VALUES ('01b0ebb2-8cfb-11ee-b9d1-0242ac120003', 'sessionManagerCache', 1, null, null, null, null, null, null);
