scm.atps.ATM=00
scm.atps.POS=01
scm.atps.IVR=02
scm.atps.MB=03
scm.atps.NEW_MB=03
scm.atps.PWA=03
scm.atps.MOBILE=03
scm.atps.USD=25
scm.atps.USSD=25
scm.atps.WAP=04
scm.atps.IB=05
scm.atps.CIB=05
scm.atps.INTERNET=05
scm.atps.FAX=06
scm.atps.EMAIL=07
scm.atps.PIN_PAD=08
scm.atps.EPAYMENT=09
scm.atps.IPG=09
scm.atps.KIOSK=10
scm.atps.ARM=11
scm.atps.ACQKIOSK=12
scm.atps.MOP=13
scm.atps.OB=20
scm.atps.SAP=21
scm.atps.NBK=22
scm.atps.HC=23
scm.atps.CIE=24
