CREATE TABLE REF.TBL_SCM_SERVICE_COMPONENT_PROVIDER (
    SERVICE_COMPONENT_PROVIDER_ID VARCHAR(36) NOT NULL,
    CODE VARCHAR(255),
    TITLE VARCHAR(255),
    COMPONENT_CLASS_NAME VARCHAR(255),
    METADATA VARCHAR(255),
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATOR VARCHAR(255),
    LAST_EDITOR VARCHAR(255),
    PRIMARY KEY (SERVICE_COMPONENT_PROVIDER_ID)
)
INSERT INTO REF.TBL_SCM_SERVICE_COMPONENT_PROVIDER (SERVICE_COMPONENT_PROVIDER_ID, CREATOR, LAST_EDITOR, CODE, TITLE, COMPONENT_CLASS_NAME, METADATA)
VALUES ('3ce3e10e-c3cd-49c7-ae5c-330a81e882d7', 'Reza Jamshidi', 'Reza Jamshidi', 'NAB', 'کر بانک رفاه', 'ir.daneshrefah.scm.plugin.nab.component.NabComponent', '{"baseUrl": "http://10.15.29.80/Service/"}');
INSERT INTO REF.TBL_SCM_SERVICE_COMPONENT_PROVIDER (SERVICE_COMPONENT_PROVIDER_ID, CREATOR, LAST_EDITOR, CODE, TITLE, COMPONENT_CLASS_NAME, METADATA)
VALUES ('ce027926-e5e1-4df5-b397-178dd41c87b8', 'Reza Jamshidi', 'Reza Jamshidi', 'ECHO', 'Echo', '', '');

CREATE TABLE REF.TBL_SCM_SERVICE_COMPONENT (
        SERVICE_COMPONENT_ID VARCHAR(36) NOT NULL,
        SERVICE_COMPONENT_PROVIDER_ID VARCHAR(36) NOT NULL,
        CODE VARCHAR(255),
        TITLE VARCHAR(255),
        METADATA VARCHAR(5000),
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        PRIMARY KEY (SERVICE_COMPONENT_ID),
        FOREIGN KEY (SERVICE_COMPONENT_PROVIDER_ID) REFERENCES REF.TBL_SCM_SERVICE_COMPONENT_PROVIDER (SERVICE_COMPONENT_PROVIDER_ID)
)
INSERT INTO "REF".TBL_SCM_SERVICE_COMPONENT
(SERVICE_COMPONENT_ID, SERVICE_COMPONENT_PROVIDER_ID, CREATOR, LAST_EDITOR, CODE, TITLE, METADATA)
VALUES('f2c5a60f-10b7-4b0f-9eeb-c89f28c2f7b1', '3ce3e10e-c3cd-49c7-ae5c-330a81e882d7', 'Reza Jamshidi', 'Reza Jamshidi', 'IBAN_INQ', 'استعلام شبا', '');
-- INSERT INTO "REF".TBL_SCM_SERVICE_COMPONENT
-- (SERVICE_COMPONENT_ID, SERVICE_COMPONENT_PROVIDER_ID, CREATE_DATE, LAST_EDIT_DATE, CREATOR, LAST_EDITOR, CODE, TITLE, METADATA)
-- VALUES('afc879a1-12c2-45ea-8f25-90b7088e5b13', '3ce3e10e-c3cd-49c7-ae5c-330a81e882d7', CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'Reza Jamshidi', 'Reza Jamshidi', 'ACH_XFER', 'ثبت درخواست پایا', '');
-- INSERT INTO "REF".TBL_SCM_SERVICE_COMPONENT
-- (SERVICE_COMPONENT_ID, SERVICE_COMPONENT_PROVIDER_ID, CREATE_DATE, LAST_EDIT_DATE, CREATOR, LAST_EDITOR, CODE, TITLE, METADATA)
-- VALUES('42f06667-118f-4320-91ad-098b313ac171', '3ce3e10e-c3cd-49c7-ae5c-330a81e882d7', CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'Reza Jamshidi', 'Reza Jamshidi', 'ACH_INQ', 'استعلام درخواست پایا', '');

CREATE TABLE REF.TBL_SCM_SERVICE (
        SERVICE_ID VARCHAR(36) NOT NULL,
        CODE VARCHAR(255),
        TITLE VARCHAR(255),
        REQUEST_JSON_SCHEMA VARCHAR(2500),
        RESPONSE_JSON_SCHEMA VARCHAR(2500),
        SERVICE_IMPLEMENTATION_TYPE_CODE INTEGER,
        JAVA_IMPLEMENTATION_CLASS_NAME VARCHAR(255),
        BPMN_IMPLEMENTATION_CONTENT VARCHAR(1000),
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        PRIMARY KEY (SERVICE_ID)
)
INSERT INTO "REF".TBL_SCM_SERVICE
(SERVICE_ID, CREATE_DATE, LAST_EDIT_DATE, CREATOR, LAST_EDITOR, CODE, TITLE, REQUEST_JSON_SCHEMA, RESPONSE_JSON_SCHEMA, SERVICE_IMPLEMENTATION_TYPE_CODE, JAVA_IMPLEMENTATION_CLASS_NAME, BPMN_IMPLEMENTATION_CONTENT)
VALUES('864d62c0-725c-4da4-91e6-8627fc0971c8', CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'Reza Jamshidi', 'Reza Jamshidi', 'IBAN_INQ', 'استعلام شبا', '', '', 1, '', '');
-- INSERT INTO "REF".TBL_SCM_SERVICE
-- (SERVICE_ID, CREATE_DATE, LAST_EDIT_DATE, CREATOR, LAST_EDITOR, CODE, TITLE, REQUEST_JSON_SCHEMA, RESPONSE_JSON_SCHEMA, SERVICE_IMPLEMENTATION_TYPE_CODE, JAVA_IMPLEMENTATION_CLASS_NAME, BPMN_IMPLEMENTATION_CONTENT)
-- VALUES('849e6953-9384-438e-bcda-9b165a7e7de9', CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'Reza Jamshidi', 'Reza Jamshidi', 'ACH_XFER', 'ثبت درخواست پایا', '', '', 1, '', '');
-- INSERT INTO "REF".TBL_SCM_SERVICE
-- (SERVICE_ID, CREATE_DATE, LAST_EDIT_DATE, CREATOR, LAST_EDITOR, CODE, TITLE, REQUEST_JSON_SCHEMA, RESPONSE_JSON_SCHEMA, SERVICE_IMPLEMENTATION_TYPE_CODE, JAVA_IMPLEMENTATION_CLASS_NAME, BPMN_IMPLEMENTATION_CONTENT)
-- VALUES('ec6dc0c5-ae02-4be1-93a7-1a2e8a91f5a1', CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'Reza Jamshidi', 'Reza Jamshidi', 'ACH_INQ', 'استعلام درخواست پایا', '', '', 1, '', '');

CREATE TABLE REF.TBL_SCM_SERVICE_COMPONENT_RELATION (
        SERVICE_COMPONENT_RELATION_ID VARCHAR(36) NOT NULL,
        SERVICE_ID VARCHAR(36) NOT NULL,
        SERVICE_COMPONENT_ID VARCHAR(36) NOT NULL,
        REQUEST_TRANSFORMER_TYPE_CODE INTEGER,
        RESPONSE_TRANSFORMER_TYPE_CODE INTEGER,
        REQUEST_METADATA VARCHAR(5000),
        RESPONSE_METADATA VARCHAR(5000),
        REQUEST_TRANSFORMER_CLASS VARCHAR(250),
        RESPONSE_TRANSFORMER_CLASS VARCHAR(250),
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        PRIMARY KEY (SERVICE_COMPONENT_RELATION_ID),
        FOREIGN KEY (SERVICE_ID) REFERENCES REF.TBL_SCM_SERVICE (SERVICE_ID),
        FOREIGN KEY (SERVICE_COMPONENT_ID) REFERENCES REF.TBL_SCM_SERVICE_COMPONENT (SERVICE_COMPONENT_ID)
)
INSERT INTO "REF".TBL_SCM_SERVICE_COMPONENT_RELATION
(SERVICE_COMPONENT_RELATION_ID, SERVICE_ID, SERVICE_COMPONENT_ID, REQUEST_TRANSFORMER_TYPE_CODE, RESPONSE_TRANSFORMER_TYPE_CODE, REQUEST_METADATA, RESPONSE_METADATA, REQUEST_TRANSFORMER_CLASS, RESPONSE_TRANSFORMER_CLASS, CREATOR, LAST_EDITOR)
VALUES('d43a89a9-56d7-4615-a4cd-c95a634d1e64', '864d62c0-725c-4da4-91e6-8627fc0971c8', 'f2c5a60f-10b7-4b0f-9eeb-c89f28c2f7b1', 3, 3, '', '', '', '', 'Reza Jamshidi', 'Reza Jamshidi');

CREATE TABLE REF.TBL_SCM_CHANNEL (
        CHANNEL_ID VARCHAR(36) NOT NULL,
        CODE VARCHAR(255),
        TITLE VARCHAR(255),
        PROTOCOL_CODE VARCHAR(100),
        METADATA VARCHAR(1000),
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        PRIMARY KEY (CHANNEL_ID)
)
INSERT INTO "REF".TBL_SCM_CHANNEL
(CHANNEL_ID, CODE, TITLE, PROTOCOL_CODE, METADATA, CREATOR, LAST_EDITOR)
VALUES('fc32467b-47cb-45c4-9076-2f7cc7d40f75', 'IBREST', 'کانال Rest اینتزنت بانک', 'REST', '{"contextPath": "/ib4dev", "port": 8082}', 'Reza Jamshidi', 'Reza Jamshidi');

CREATE TABLE REF.TBL_SCM_TERMINAL (
        TERMINAL_ID VARCHAR(36) NOT NULL,
        CODE VARCHAR(255),
        TITLE VARCHAR(255),
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        PRIMARY KEY (TERMINAL_ID)
)
INSERT INTO "REF".TBL_SCM_TERMINAL
(TERMINAL_ID, CODE, TITLE, CREATOR, LAST_EDITOR)
VALUES('a45687d9-71b7-4e7c-a97f-2e9c8a1d6efc', 'IB', 'اینترنت بانک', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TERMINAL
(TERMINAL_ID, CODE, TITLE, CREATOR, LAST_EDITOR)
VALUES('3f0b9c5a-8d89-4c8d-9a7d-4287f6e75639', 'MB', 'موبایل بانک', 'Reza Jamshidi', 'Reza Jamshidi');

CREATE TABLE REF.TBL_SCM_TERMINAL_SERVICE_ACCESS (
        TERMINAL_SERVICE_ACCESS_ID VARCHAR(36) NOT NULL,
        TERMINAL_ID VARCHAR(36) NOT NULL,
        SERVICE_ID VARCHAR(36) NOT NULL,
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        FOREIGN KEY (TERMINAL_ID) REFERENCES REF.TBL_SCM_TERMINAL (TERMINAL_ID),
        FOREIGN KEY (SERVICE_ID) REFERENCES REF.TBL_SCM_SERVICE (SERVICE_ID),
        PRIMARY KEY (TERMINAL_SERVICE_ACCESS_ID)
)
INSERT INTO "REF".TBL_SCM_TERMINAL_SERVICE_ACCESS
(TERMINAL_SERVICE_ACCESS_ID, TERMINAL_ID, SERVICE_ID, CREATOR, LAST_EDITOR)
VALUES('c498f605-ef9f-43d3-b389-35f83c49563b', 'a45687d9-71b7-4e7c-a97f-2e9c8a1d6efc', '864d62c0-725c-4da4-91e6-8627fc0971c8', 'Reza Jamshidi', 'Reza Jamshidi');

CREATE TABLE REF.TBL_SCM_TERMINAL_SERVICE_CHANNEL_ACCESS (
        TERMINAL_SERVICE_CHANNEL_ACCESS_ID VARCHAR(36) NOT NULL,
        TERMINAL_SERVICE_ACCESS_ID VARCHAR(36) NOT NULL,
        CHANNEL_ID VARCHAR(36) NOT NULL,
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        FOREIGN KEY (TERMINAL_SERVICE_ACCESS_ID) REFERENCES REF.TBL_SCM_TERMINAL_SERVICE_ACCESS (TERMINAL_SERVICE_ACCESS_ID),
        FOREIGN KEY (CHANNEL_ID) REFERENCES REF.TBL_SCM_CHANNEL (CHANNEL_ID),
        PRIMARY KEY (TERMINAL_SERVICE_CHANNEL_ACCESS_ID)
)
INSERT INTO "REF".TBL_SCM_TERMINAL_SERVICE_CHANNEL_ACCESS
(TERMINAL_SERVICE_CHANNEL_ACCESS_ID, TERMINAL_SERVICE_ACCESS_ID, CHANNEL_ID, CREATOR, LAST_EDITOR)
VALUES('de07c206-6671-4a27-9f16-62042153c94e', 'c498f605-ef9f-43d3-b389-35f83c49563b', 'fc32467b-47cb-45c4-9076-2f7cc7d40f75', 'Reza Jamshidi', 'Reza Jamshidi');









-- 14020424
CREATE TABLE REF.TBL_SCM_PROFILE (
        PROFILE_ID VARCHAR(36) NOT NULL,
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        NAME VARCHAR(255),
        TITLE VARCHAR(255),
        PRIMARY KEY (PROFILE_ID)
)
INSERT INTO REF.TBL_SCM_PROFILE (PROFILE_ID, CREATOR, LAST_EDITOR, NAME, TITLE)
VALUES ('a9dcfd02e4fc4f7f92bce0c6a2e7f225', 'Reza Jamshidi', 'Reza Jamshidi', 'IB4DEV', 'اینترنت بانک توسعه');
INSERT INTO REF.TBL_SCM_PROFILE (PROFILE_ID, CREATOR, LAST_EDITOR, NAME, TITLE)
VALUES ('f3e0ebe042f244b09be0581ac05351d0', 'Reza Jamshidi', 'Reza Jamshidi', 'MB4DEV', 'موبایل بانک توسعه');

