CREATE TABLE REF.TBL_SCM_SERVICE_COMPONENT_PROVIDER (
         SERVICE_COMPONENT_PROVIDER_ID VARCHAR(36) NOT NULL,
         CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
         LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
         CREATOR VARCHAR(255),
         LAST_EDITOR VARCHAR(255),
         CODE VARCHAR(255),
         TITLE VARCHAR(255),
         PRIMARY KEY (SERVICE_COMPONENT_PROVIDER_ID)
)
INSERT INTO REF.TBL_SCM_SERVICE_COMPONENT_PROVIDER (SERVICE_COMPONENT_PROVIDER_ID, CREATOR, LAST_EDITOR, CODE, TITLE)
VALUES ('3ce3e10e-c3cd-49c7-ae5c-330a81e882d7', 'Reza Jamshidi', 'Reza Jamshidi', 'NAB', 'کر بانک رفاه');
INSERT INTO REF.TBL_SCM_SERVICE_COMPONENT_PROVIDER (SERVICE_COMPONENT_PROVIDER_ID, CREATOR, LAST_EDITOR, CODE, TITLE)
VALUES ('ce027926-e5e1-4df5-b397-178dd41c87b8', 'Reza Jamshidi', 'Reza Jamshidi', 'ECHO', 'Echo');

CREATE TABLE REF.TBL_SCM_SERVICE_COMPONENT (
        SERVICE_COMPONENT_ID VARCHAR(36) NOT NULL,
        SERVICE_COMPONENT_PROVIDER_ID VARCHAR(36) NOT NULL,
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        CODE VARCHAR(255),
        TITLE VARCHAR(255),
        REQUEST_JSON_SCHEMA VARCHAR(255),
        RESPONSE_JSON_SCHEMA VARCHAR(255),
        METADATA VARCHAR(1000),
        PRIMARY KEY (SERVICE_COMPONENT_ID)
)
INSERT INTO "REF".TBL_SCM_SERVICE_COMPONENT
(SERVICE_COMPONENT_ID, SERVICE_COMPONENT_PROVIDER_ID, CREATE_DATE, LAST_EDIT_DATE, CREATOR, LAST_EDITOR, CODE, TITLE, REQUEST_JSON_SCHEMA, RESPONSE_JSON_SCHEMA, METADATA)
VALUES('afc879a1-12c2-45ea-8f25-90b7088e5b13', '3ce3e10e-c3cd-49c7-ae5c-330a81e882d7', CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'Reza Jamshidi', 'Reza Jamshidi', 'ACH_XFER', 'ثبت درخواست پایا', '', '', '');
INSERT INTO "REF".TBL_SCM_SERVICE_COMPONENT
(SERVICE_COMPONENT_ID, SERVICE_COMPONENT_PROVIDER_ID, CREATE_DATE, LAST_EDIT_DATE, CREATOR, LAST_EDITOR, CODE, TITLE, REQUEST_JSON_SCHEMA, RESPONSE_JSON_SCHEMA, METADATA)
VALUES('42f06667-118f-4320-91ad-098b313ac171', '3ce3e10e-c3cd-49c7-ae5c-330a81e882d7', CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'Reza Jamshidi', 'Reza Jamshidi', 'ACH_INQ', 'استعلام درخواست پایا', '', '', '');



CREATE TABLE REF.TBL_SCM_SERVICE (
        SERVICE_ID VARCHAR(36) NOT NULL,
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        CODE VARCHAR(255),
        TITLE VARCHAR(255),
        REQUEST_JSON_SCHEMA VARCHAR(255),
        RESPONSE_JSON_SCHEMA VARCHAR(255),
        SERVICE_TYPE_CODE INTEGER,
        JAVA_IMPLEMENTATION_CLASS_NAME VARCHAR(255),
        BPMN_IMPLEMENTATION_CONTENT VARCHAR(1000),
        PRIMARY KEY (SERVICE_ID)
)
INSERT INTO "REF".TBL_SCM_SERVICE
(SERVICE_ID, CREATE_DATE, LAST_EDIT_DATE, CREATOR, LAST_EDITOR, CODE, TITLE, REQUEST_JSON_SCHEMA, RESPONSE_JSON_SCHEMA, SERVICE_TYPE_CODE, JAVA_IMPLEMENTATION_CLASS_NAME, BPMN_IMPLEMENTATION_CONTENT)
VALUES('849e6953-9384-438e-bcda-9b165a7e7de9', CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'Reza Jamshidi', 'Reza Jamshidi', 'ACH_XFER', 'ثبت درخواست پایا', '', '', 1, '', '');
INSERT INTO "REF".TBL_SCM_SERVICE
(SERVICE_ID, CREATE_DATE, LAST_EDIT_DATE, CREATOR, LAST_EDITOR, CODE, TITLE, REQUEST_JSON_SCHEMA, RESPONSE_JSON_SCHEMA, SERVICE_TYPE_CODE, JAVA_IMPLEMENTATION_CLASS_NAME, BPMN_IMPLEMENTATION_CONTENT)
VALUES('ec6dc0c5-ae02-4be1-93a7-1a2e8a91f5a1', CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'Reza Jamshidi', 'Reza Jamshidi', 'ACH_INQ', 'استعلام درخواست پایا', '', '', 1, '', '');


CREATE TABLE REF.TBL_SCM_SERVICE_RELATION (
        SERVICE_RELATION_ID VARCHAR(36) NOT NULL,
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        SERVICE_ID VARCHAR(36) NOT NULL,
        SERVICE_COMPONENT_ID VARCHAR(36) NOT NULL,
        PRIMARY KEY (SERVICE_RELATION_ID)
)
INSERT INTO "REF".TBL_SCM_SERVICE_RELATION
(SERVICE_RELATION_ID, CREATE_DATE, LAST_EDIT_DATE, CREATOR, LAST_EDITOR, SERVICE_ID, SERVICE_COMPONENT_ID)
VALUES('1efc0f12-4a4d-4651-8b7a-c891a1da598a', CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'Reza Jamshidi', 'Reza Jamshidi', '849e6953-9384-438e-bcda-9b165a7e7de9', 'afc879a1-12c2-45ea-8f25-90b7088e5b13');
INSERT INTO "REF".TBL_SCM_SERVICE_RELATION
(SERVICE_RELATION_ID, CREATE_DATE, LAST_EDIT_DATE, CREATOR, LAST_EDITOR, SERVICE_ID, SERVICE_COMPONENT_ID)
VALUES('7abf95c0-3a2d-4d9c-9f4c-e9c8dc75e753', CURRENT TIMESTAMP, CURRENT TIMESTAMP, 'Reza Jamshidi', 'Reza Jamshidi', 'ec6dc0c5-ae02-4be1-93a7-1a2e8a91f5a1', '42f06667-118f-4320-91ad-098b313ac171');

-- 14020424
CREATE TABLE REF.TBL_SCM_PROFILE (
        PROFILE_ID VARCHAR(36) NOT NULL,
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        NAME VARCHAR(255),
        TITLE VARCHAR(255),
        PRIMARY KEY (PROFILE_ID)
)

INSERT INTO REF.TBL_SCM_PROFILE (PROFILE_ID, CREATOR, LAST_EDITOR, NAME, TITLE)
VALUES ('a9dcfd02e4fc4f7f92bce0c6a2e7f225', 'Reza Jamshidi', 'Reza Jamshidi', 'IB4DEV', 'اینترنت بانک توسعه');

INSERT INTO REF.TBL_SCM_PROFILE (PROFILE_ID, CREATOR, LAST_EDITOR, NAME, TITLE)
VALUES ('f3e0ebe042f244b09be0581ac05351d0', 'Reza Jamshidi', 'Reza Jamshidi', 'MB4DEV', 'موبایل بانک توسعه');

CREATE TABLE REF.TBL_SCM_SERVICE_PROVIDER (
        SERVICE_PROVIDER_ID VARCHAR(36) NOT NULL,
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        NAME VARCHAR(255),
        TITLE VARCHAR(255),
        COMPONENT_NAME VARCHAR(255),
        VALUE VARCHAR(255),
        PRIMARY KEY (SERVICE_PROVIDER_ID)
)


INSERT INTO REF.TBL_SCM_SERVICE_PROVIDER (SERVICE_PROVIDER_ID, CREATOR, LAST_EDITOR, NAME, TITLE, COMPONENT_NAME, VALUE)
VALUES ('c3a52c86-8f97-4c9d-9c01-877be1242d92', 'Reza Jamshidi', 'Reza Jamshidi', 'Nab Rest', 'همراه', 'NAB', '');