CREATE TABLE REF.TBL_SCM_CHANNEL (
        CHANNEL_ID VARCHAR(36) NOT NULL,
        CODE VARCHAR(255),
        TITLE VARCHAR(255),
        CHANNEL_CLASS_NAME VARCHAR(255),
        METADATA VARCHAR(1000),
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        PRIMARY KEY (CHANNEL_ID)
)
INSERT INTO "REF".TBL_SCM_CHANNEL
(CHANNEL_ID, CODE, TITLE, CHANNEL_CLASS_NAME, METADATA, CREATOR, LAST_EDITOR)
VALUES('fc32467b-47cb-45c4-9076-2f7cc7d40f75', 'bean:restInboundChannelGenerator', 'کانال Rest اینتزنت بانک', 'REST', '{"contextPath": "/ib4dev", "port": 8082}', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_CHANNEL
(CHANNEL_ID, CODE, TITLE, CHANNEL_CLASS_NAME, METADATA, CREATOR, LAST_EDITOR)
VALUES('a5f8d15a-9e79-4f86-b0f7-92a2f8b9d62c', 'SCM_REST', 'کانال Rest مدیریت کانال', 'bean:restInboundChannelGenerator', '{"contextPath": "/scm", "port": 8083}', 'Reza Jamshidi', 'Reza Jamshidi');


CREATE TABLE REF.TBL_SCM_TERMINAL (
        TERMINAL_ID VARCHAR(36) NOT NULL,
        CODE VARCHAR(255),
        TITLE VARCHAR(255),
        SUPPORT_CHECK_AUTHENTICATION SMALLINT DEFAULT 1,
        SUPPORT_CHECK_SECOND_AUTHENTICATION SMALLINT DEFAULT 1,
        SUPPORT_CHECK_SERVICE_ACCESS SMALLINT DEFAULT 1,
        SUPPORT_CHECK_ACCOUNT_AUTHORIZATION SMALLINT DEFAULT 1,
        SUPPORT_CHECK_MAX_WITHDRAW SMALLINT DEFAULT 1,
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        PRIMARY KEY (TERMINAL_ID)
)
INSERT INTO "REF".TBL_SCM_TERMINAL
(TERMINAL_ID, CODE, TITLE, CREATOR, LAST_EDITOR)
VALUES('a45687d9-71b7-4e7c-a97f-2e9c8a1d6efc', 'IB', 'اینترنت بانک', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TERMINAL
(TERMINAL_ID, CODE, TITLE, CREATOR, LAST_EDITOR)
VALUES('3f0b9c5a-8d89-4c8d-9a7d-4287f6e75639', 'MB', 'موبایل بانک', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TERMINAL
(TERMINAL_ID, CODE, TITLE, CREATOR, LAST_EDITOR, SUPPORT_CHECK_AUTHENTICATION, SUPPORT_CHECK_SECOND_AUTHENTICATION, SUPPORT_CHECK_SERVICE_ACCESS, SUPPORT_CHECK_ACCOUNT_AUTHORIZATION, SUPPORT_CHECK_MAX_WITHDRAW)
VALUES('c2eb2878-2f0e-4e82-9037-f8b7cfab7f95', 'SCM', 'مدیریت کانال', 'Reza Jamshidi', 'Reza Jamshidi', 1, 0, 1, 0, 0);



CREATE TABLE REF.TBL_SCM_EXTERNAL_SERVICE_PROVIDER (
        EXTERNAL_SERVICE_PROVIDER_ID VARCHAR(36) NOT NULL,
        CODE VARCHAR(255),
        TITLE VARCHAR(255),
        PROVIDER_CLASS_NAME VARCHAR(255),
        METADATA VARCHAR(255),
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        PRIMARY KEY (EXTERNAL_SERVICE_PROVIDER_ID)
)
INSERT INTO REF.TBL_SCM_EXTERNAL_SERVICE_PROVIDER (EXTERNAL_SERVICE_PROVIDER_ID, CREATOR, LAST_EDITOR, CODE, TITLE, PROVIDER_CLASS_NAME, METADATA)
VALUES ('3ce3e10e-c3cd-49c7-ae5c-330a81e882d7', 'Reza Jamshidi', 'Reza Jamshidi', 'NAB', 'کر بانک رفاه', 'ir.daneshrefah.scm.plugin.nab.component.NabComponent', '{"baseUrl": "http://10.15.29.80/Service/"}');
INSERT INTO REF.TBL_SCM_EXTERNAL_SERVICE_PROVIDER (EXTERNAL_SERVICE_PROVIDER_ID, CREATOR, LAST_EDITOR, CODE, TITLE, PROVIDER_CLASS_NAME, METADATA)
VALUES ('ce027926-e5e1-4df5-b397-178dd41c87b8', 'Reza Jamshidi', 'Reza Jamshidi', 'MOCK', 'Mock', '', '');

EXTERNAL(1), JAVA(2), COMPOSITION(3), BPMN(4), PARENT(5);

CREATE TABLE REF.TBL_SCM_SERVICE (
        SERVICE_ID VARCHAR(36) NOT NULL,
        CODE VARCHAR(255),
        TITLE VARCHAR(255),
        REQUEST_JSON_SCHEMA VARCHAR(2500),
        RESPONSE_JSON_SCHEMA VARCHAR(2500),
        METADATA VARCHAR(1000),
        SERVICE_TYPE_CODE INTEGER,
        SERVICE_IMPLEMENTATION_TYPE_CODE INTEGER NOT NULL,
        IMPLEMENTATION_JAVA_CLASS_NAME VARCHAR(255),
        IMPLEMENTATION_EXTERNAL_SERVICE_PROVIDER_ID VARCHAR(36),
        IMPLEMENTATION_BPMN_CONTENT VARCHAR(1000),
        IMPLEMENTATION_COMPOSITION_TYPE_CODE INTEGER,
        TRANSFORMER_TYPE_CODE_REQUEST INTEGER,
        TRANSFORMER_TYPE_CODE_RESPONSE INTEGER,
        TRANSFORM_METADATA_REQUEST VARCHAR(5000),
        TRANSFORM_METADATA_RESPONSE VARCHAR(5000),
        TRANSFORM_CLASS_REQUEST VARCHAR(250),
        TRANSFORM_CLASS_RESPONSE VARCHAR(250),
        CHECK_ACCESS_FIRST_AUTHENTICATION SMALLINT DEFAULT 0 NOT NULL,
        CHECK_ACCESS_SECOND_AUTHENTICATION SMALLINT DEFAULT 0 NOT NULL,
        CHECK_ACCESS_SERVICE SMALLINT DEFAULT 0 NOT NULL,
        CHECK_ACCESS_ACCOUNT SMALLINT DEFAULT 0 NOT NULL,
        CHECK_ACCESS_WITHDRAW SMALLINT DEFAULT 0 NOT NULL,
        PROPERTY_NAME_AMOUNT VARCHAR(100),
        PROPERTY_NAME_ACCOUNT VARCHAR(100),
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        FOREIGN KEY (IMPLEMENTATION_EXTERNAL_SERVICE_PROVIDER_ID) REFERENCES REF.TBL_SCM_EXTERNAL_SERVICE_PROVIDER (EXTERNAL_SERVICE_PROVIDER_ID),
        PRIMARY KEY (SERVICE_ID)
)
INSERT INTO "REF".TBL_SCM_SERVICE
(SERVICE_ID, CODE, TITLE, REQUEST_JSON_SCHEMA, RESPONSE_JSON_SCHEMA, SERVICE_IMPLEMENTATION_TYPE_CODE, IMPLEMENTATION_JAVA_CLASS_NAME, IMPLEMENTATION_EXTERNAL_SERVICE_PROVIDER_ID, IMPLEMENTATION_BPMN_CONTENT, CREATOR, LAST_EDITOR)
VALUES('864d62c0-725c-4da4-91e6-8627fc0971c8', 'IBAN_INQ', 'استعلام شبا', '', '', 1, '', '3ce3e10e-c3cd-49c7-ae5c-330a81e882d7', '', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_SERVICE
(SERVICE_ID, CODE, TITLE, REQUEST_JSON_SCHEMA, RESPONSE_JSON_SCHEMA, SERVICE_IMPLEMENTATION_TYPE_CODE, IMPLEMENTATION_JAVA_CLASS_NAME, IMPLEMENTATION_EXTERNAL_SERVICE_PROVIDER_ID, IMPLEMENTATION_BPMN_CONTENT, CREATOR, LAST_EDITOR)
VALUES('d87402c2-8a49-4f68-9c1a-98de6e4ac45d', 'GET_AUTH_CUSTOMER_NO', 'دریافت شماره مشتری از لاگین', '', '', 2, 'bean:cardToAccountConvertService', null, '', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_SERVICE
(SERVICE_ID, CODE, TITLE, REQUEST_JSON_SCHEMA, RESPONSE_JSON_SCHEMA, SERVICE_IMPLEMENTATION_TYPE_CODE, IMPLEMENTATION_JAVA_CLASS_NAME, IMPLEMENTATION_EXTERNAL_SERVICE_PROVIDER_ID, IMPLEMENTATION_BPMN_CONTENT, IMPLEMENTATION_COMPOSITION_TYPE_CODE, CREATOR, LAST_EDITOR)
VALUES('2b6216d6-c9a1-4f13-89ef-af5b7f7ebd14', 'IBAN_INQ_FROM_LOGIN', 'استعلام شبا کاربر لاگین شده', '', '', 3, '', null, '', 1, 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_SERVICE
(SERVICE_ID, CODE, TITLE, REQUEST_JSON_SCHEMA, RESPONSE_JSON_SCHEMA, SERVICE_IMPLEMENTATION_TYPE_CODE, IMPLEMENTATION_JAVA_CLASS_NAME, CREATOR, LAST_EDITOR)
VALUES('6c2e85a0-87e7-4eab-a9b2-df33c3884b77', 'TERMINAL_LIST', 'لیست ترمینال ها', '', '', 2, '', 'Reza Jamshidi', 'Reza Jamshidi');

CREATE TABLE REF.TBL_SCM_SERVICE_RELATION (
        SERVICE_RELATION_ID VARCHAR(36) NOT NULL,
        SOURCE_SERVICE_ID VARCHAR(36) NOT NULL,
        ORDER INTEGER,
        RELATION_TYPE_CODE INTEGER,
        TARGET_SERVICE_ID VARCHAR(36) NOT NULL,
        TARGET_SERVICE_TRANSFORMER_REQUEST_TYPE_CODE INTEGER,
        TARGET_SERVICE_TRANSFORMER_REQUEST_METADATA VARCHAR(5000),
        TARGET_SERVICE_TRANSFORMER_REQUEST_CLASS_NAME VARCHAR(250),
        TARGET_SERVICE_TRANSFORMER_RESPONSE_TYPE_CODE INTEGER,
        TARGET_SERVICE_TRANSFORMER_RESPONSE_METADATA VARCHAR(5000),
        TARGET_SERVICE_TRANSFORMER_RESPONSE_CLASS_NAME VARCHAR(250),
        TARGET_SERVICE_COMMIT_ID VARCHAR(36),
        TARGET_SERVICE_COMMIT_TRANSFORMER_REQUEST_TYPE_CODE INTEGER,
        TARGET_SERVICE_COMMIT_TRANSFORMER_REQUEST_METADATA VARCHAR(5000),
        TARGET_SERVICE_COMMIT_TRANSFORMER_REQUEST_CLASS_NAME VARCHAR(250),
        TARGET_SERVICE_COMMIT_TRANSFORMER_RESPONSE_TYPE_CODE INTEGER,
        TARGET_SERVICE_COMMIT_TRANSFORMER_RESPONSE_METADATA VARCHAR(5000),
        TARGET_SERVICE_COMMIT_TRANSFORMER_RESPONSE_CLASS_NAME VARCHAR(250),
        TARGET_SERVICE_REVERSE_ID VARCHAR(36),
        TARGET_SERVICE_REVERSE_TRANSFORMER_REQUEST_TYPE_CODE INTEGER,
        TARGET_SERVICE_REVERSE_TRANSFORMER_REQUEST_METADATA VARCHAR(5000),
        TARGET_SERVICE_REVERSE_TRANSFORMER_REQUEST_CLASS_NAME VARCHAR(250),
        TARGET_SERVICE_REVERSE_TRANSFORMER_RESPONSE_TYPE_CODE INTEGER,
        TARGET_SERVICE_REVERSE_TRANSFORMER_RESPONSE_METADATA VARCHAR(5000),
        TARGET_SERVICE_REVERSE_TRANSFORMER_RESPONSE_CLASS_NAME VARCHAR(250),
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        FOREIGN KEY (SOURCE_SERVICE_ID) REFERENCES REF.TBL_SCM_SERVICE (SERVICE_ID),
        FOREIGN KEY (TARGET_SERVICE_ID) REFERENCES REF.TBL_SCM_SERVICE (SERVICE_ID),
        FOREIGN KEY (TARGET_SERVICE_COMMIT_ID) REFERENCES REF.TBL_SCM_SERVICE (SERVICE_ID),
        FOREIGN KEY (TARGET_SERVICE_REVERSE_ID) REFERENCES REF.TBL_SCM_SERVICE (SERVICE_ID),
        PRIMARY KEY (SERVICE_RELATION_ID)
)
INSERT INTO "REF".TBL_SCM_SERVICE_RELATION
(SERVICE_RELATION_ID, SOURCE_SERVICE_ID, "ORDER", RELATION_TYPE_CODE,
TARGET_SERVICE_ID, TARGET_SERVICE_TRANSFORMER_REQUEST_TYPE_CODE, TARGET_SERVICE_TRANSFORMER_REQUEST_METADATA, TARGET_SERVICE_TRANSFORMER_REQUEST_CLASS_NAME, TARGET_SERVICE_TRANSFORMER_RESPONSE_TYPE_CODE, TARGET_SERVICE_TRANSFORMER_RESPONSE_METADATA, TARGET_SERVICE_TRANSFORMER_RESPONSE_CLASS_NAME,
TARGET_SERVICE_COMMIT_ID, TARGET_SERVICE_COMMIT_TRANSFORMER_REQUEST_TYPE_CODE, TARGET_SERVICE_COMMIT_TRANSFORMER_REQUEST_METADATA, TARGET_SERVICE_COMMIT_TRANSFORMER_REQUEST_CLASS_NAME, TARGET_SERVICE_COMMIT_TRANSFORMER_RESPONSE_TYPE_CODE, TARGET_SERVICE_COMMIT_TRANSFORMER_RESPONSE_METADATA, TARGET_SERVICE_COMMIT_TRANSFORMER_RESPONSE_CLASS_NAME,
TARGET_SERVICE_REVERSE_ID, TARGET_SERVICE_REVERSE_TRANSFORMER_REQUEST_TYPE_CODE, TARGET_SERVICE_REVERSE_TRANSFORMER_REQUEST_METADATA, TARGET_SERVICE_REVERSE_TRANSFORMER_REQUEST_CLASS_NAME, TARGET_SERVICE_REVERSE_TRANSFORMER_RESPONSE_TYPE_CODE, TARGET_SERVICE_REVERSE_TRANSFORMER_RESPONSE_METADATA, TARGET_SERVICE_REVERSE_TRANSFORMER_RESPONSE_CLASS_NAME,
CREATOR, LAST_EDITOR)
VALUES('7d2e1a3b-e894-4ea3-b01a-685361fd75e5', '2b6216d6-c9a1-4f13-89ef-af5b7f7ebd14', 0, 1,
'd87402c2-8a49-4f68-9c1a-98de6e4ac45d', 0, '', '', 0, '', '',
null, 0, '', '', 0, '', '',
null, 0, '', '', 0, '', '',
'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_SERVICE_RELATION
(SERVICE_RELATION_ID, SOURCE_SERVICE_ID, "ORDER", RELATION_TYPE_CODE,
TARGET_SERVICE_ID, TARGET_SERVICE_TRANSFORMER_REQUEST_TYPE_CODE, TARGET_SERVICE_TRANSFORMER_REQUEST_METADATA, TARGET_SERVICE_TRANSFORMER_REQUEST_CLASS_NAME, TARGET_SERVICE_TRANSFORMER_RESPONSE_TYPE_CODE, TARGET_SERVICE_TRANSFORMER_RESPONSE_METADATA, TARGET_SERVICE_TRANSFORMER_RESPONSE_CLASS_NAME,
TARGET_SERVICE_COMMIT_ID, TARGET_SERVICE_COMMIT_TRANSFORMER_REQUEST_TYPE_CODE, TARGET_SERVICE_COMMIT_TRANSFORMER_REQUEST_METADATA, TARGET_SERVICE_COMMIT_TRANSFORMER_REQUEST_CLASS_NAME, TARGET_SERVICE_COMMIT_TRANSFORMER_RESPONSE_TYPE_CODE, TARGET_SERVICE_COMMIT_TRANSFORMER_RESPONSE_METADATA, TARGET_SERVICE_COMMIT_TRANSFORMER_RESPONSE_CLASS_NAME,
TARGET_SERVICE_REVERSE_ID, TARGET_SERVICE_REVERSE_TRANSFORMER_REQUEST_TYPE_CODE, TARGET_SERVICE_REVERSE_TRANSFORMER_REQUEST_METADATA, TARGET_SERVICE_REVERSE_TRANSFORMER_REQUEST_CLASS_NAME, TARGET_SERVICE_REVERSE_TRANSFORMER_RESPONSE_TYPE_CODE, TARGET_SERVICE_REVERSE_TRANSFORMER_RESPONSE_METADATA, TARGET_SERVICE_REVERSE_TRANSFORMER_RESPONSE_CLASS_NAME,
CREATOR, LAST_EDITOR)
VALUES('fc73df1a-9c67-4c8c-9d84-5a765ca94210', '2b6216d6-c9a1-4f13-89ef-af5b7f7ebd14', 0, 1,
'864d62c0-725c-4da4-91e6-8627fc0971c8', 0, '', '', 0, '', '',
null, 0, '', '', 0, '', '',
null, 0, '', '', 0, '', '',
'Reza Jamshidi', 'Reza Jamshidi');



CREATE TABLE REF.TBL_SCM_TERMINAL_SERVICE_ACCESS (
        TERMINAL_SERVICE_ACCESS_ID VARCHAR(36) NOT NULL,
        TERMINAL_ID VARCHAR(36) NOT NULL,
        SERVICE_ID VARCHAR(36) NOT NULL,
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        FOREIGN KEY (TERMINAL_ID) REFERENCES REF.TBL_SCM_TERMINAL (TERMINAL_ID),
        FOREIGN KEY (SERVICE_ID) REFERENCES REF.TBL_SCM_SERVICE (SERVICE_ID),
        PRIMARY KEY (TERMINAL_SERVICE_ACCESS_ID)
)
INSERT INTO "REF".TBL_SCM_TERMINAL_SERVICE_ACCESS
(TERMINAL_SERVICE_ACCESS_ID, TERMINAL_ID, SERVICE_ID, CREATOR, LAST_EDITOR)
VALUES('c498f605-ef9f-43d3-b389-35f83c49563b', 'a45687d9-71b7-4e7c-a97f-2e9c8a1d6efc', '864d62c0-725c-4da4-91e6-8627fc0971c8', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TERMINAL_SERVICE_ACCESS
(TERMINAL_SERVICE_ACCESS_ID, TERMINAL_ID, SERVICE_ID, CREATOR, LAST_EDITOR)
VALUES('56e4d558-7a8e-46be-b8b3-c07e2db7c0a6', 'a45687d9-71b7-4e7c-a97f-2e9c8a1d6efc', 'd87402c2-8a49-4f68-9c1a-98de6e4ac45d', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TERMINAL_SERVICE_ACCESS
(TERMINAL_SERVICE_ACCESS_ID, TERMINAL_ID, SERVICE_ID, CREATOR, LAST_EDITOR)
VALUES('f2e5daae-7d07-4a6c-81f0-1ca5e9f9d5c3', 'a45687d9-71b7-4e7c-a97f-2e9c8a1d6efc', '2b6216d6-c9a1-4f13-89ef-af5b7f7ebd14', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TERMINAL_SERVICE_ACCESS
(TERMINAL_SERVICE_ACCESS_ID, TERMINAL_ID, SERVICE_ID, CREATOR, LAST_EDITOR)
VALUES('53b125e4-4182-4ab5-9d26-862842129c87', 'c2eb2878-2f0e-4e82-9037-f8b7cfab7f95', '6c2e85a0-87e7-4eab-a9b2-df33c3884b77', 'Reza Jamshidi', 'Reza Jamshidi');

CREATE TABLE REF.TBL_SCM_TERMINAL_SERVICE_CHANNEL_ACCESS (
        TERMINAL_SERVICE_CHANNEL_ACCESS_ID VARCHAR(36) NOT NULL,
        TERMINAL_SERVICE_ACCESS_ID VARCHAR(36) NOT NULL,
        CHANNEL_ID VARCHAR(36) NOT NULL,
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        FOREIGN KEY (TERMINAL_SERVICE_ACCESS_ID) REFERENCES REF.TBL_SCM_TERMINAL_SERVICE_ACCESS (TERMINAL_SERVICE_ACCESS_ID),
        FOREIGN KEY (CHANNEL_ID) REFERENCES REF.TBL_SCM_CHANNEL (CHANNEL_ID),
        PRIMARY KEY (TERMINAL_SERVICE_CHANNEL_ACCESS_ID)
)
INSERT INTO "REF".TBL_SCM_TERMINAL_SERVICE_CHANNEL_ACCESS
(TERMINAL_SERVICE_CHANNEL_ACCESS_ID, TERMINAL_SERVICE_ACCESS_ID, CHANNEL_ID, CREATOR, LAST_EDITOR)
VALUES('de07c206-6671-4a27-9f16-62042153c94e', 'c498f605-ef9f-43d3-b389-35f83c49563b', 'fc32467b-47cb-45c4-9076-2f7cc7d40f75', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TERMINAL_SERVICE_CHANNEL_ACCESS
(TERMINAL_SERVICE_CHANNEL_ACCESS_ID, TERMINAL_SERVICE_ACCESS_ID, CHANNEL_ID, CREATOR, LAST_EDITOR)
VALUES('a459f229-55b0-49b7-9d16-71da84f55d6c', '56e4d558-7a8e-46be-b8b3-c07e2db7c0a6', 'fc32467b-47cb-45c4-9076-2f7cc7d40f75', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TERMINAL_SERVICE_CHANNEL_ACCESS
(TERMINAL_SERVICE_CHANNEL_ACCESS_ID, TERMINAL_SERVICE_ACCESS_ID, CHANNEL_ID, CREATOR, LAST_EDITOR)
VALUES('89ab82e9-5c4f-482a-9c10-62c8961a674b', 'f2e5daae-7d07-4a6c-81f0-1ca5e9f9d5c3', 'fc32467b-47cb-45c4-9076-2f7cc7d40f75', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TERMINAL_SERVICE_CHANNEL_ACCESS
(TERMINAL_SERVICE_CHANNEL_ACCESS_ID, TERMINAL_SERVICE_ACCESS_ID, CHANNEL_ID, CREATOR, LAST_EDITOR)
VALUES('a736a6ef-8c1d-4c3c-9e92-23a308570a19', '53b125e4-4182-4ab5-9d26-862842129c87', 'a5f8d15a-9e79-4f86-b0f7-92a2f8b9d62c', 'Reza Jamshidi', 'Reza Jamshidi');

CREATE TABLE REF.TBL_SCM_ERROR_MAPPING (
        ERROR_MAPPING_ID VARCHAR(36) NOT NULL,
        EXTERNAL_SERVICE_PROVIDER_ID VARCHAR(36),
        PROVIDER_ERROR_CODE VARCHAR(36),
        EXCEPTION_CLASS_NAME VARCHAR(300),
        SCM_ERROR_CODE VARCHAR(50) NOT NULL,
        STATUS_CODE VARCHAR(50) NOT NULL,
        MESSAGE VARCHAR(200) NOT NULL,
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        FOREIGN KEY (EXTERNAL_SERVICE_PROVIDER_ID) REFERENCES REF.TBL_SCM_EXTERNAL_SERVICE_PROVIDER (EXTERNAL_SERVICE_PROVIDER_ID),
        PRIMARY KEY (ERROR_MAPPING_ID)
)
INSERT INTO "REF".TBL_SCM_ERROR_MAPPING
(ERROR_MAPPING_ID, EXCEPTION_CLASS_NAME, SCM_ERROR_CODE, STATUS_CODE, MESSAGE, CREATOR, LAST_EDITOR)
VALUES('0d8e22e3-79f1-4b02-b7b5-7480f446c723', '', 'SCM-2001', 'SC_ERROR_BUSINESS', '', 'Reza Jamshidi', 'Reza Jamshidi');

CREATE TABLE REF.TBL_SCM_AUTHORITY (
        AUTHORITY_ID VARCHAR(36) NOT NULL,
        AUTHORITY_TYPE_CODE SMALLINT NOT NULL,
        SOURCE_TERMINAL_ID VARCHAR(36) NOT NULL,
        SOURCE_CHANNEL_ID VARCHAR(36),
        SOURCE_SERVICE_ID VARCHAR(36),
        SOURCE_AUTHENTICATION_METHOD_CODE VARCHAR(36),
        SOURCE_CONDITION VARCHAR(500),
        SOURCE_USER_ID VARCHAR(36),
        SOURCE_MEMBERSHIP_ID VARCHAR(36),
        TARGET_SERVICE_ACCESS_ALLOW SMALLINT DEFAULT 1,
        TARGET_WITHDRAW_DURATION_TYPE_CODE SMALLINT,
        TARGET_WITHDRAW_DURATION SMALLINT,
        TARGET_WITHDRAW_MIN_AMOUNT DECIMAL(20, 2),
        TARGET_WITHDRAW_MAX_AMOUNT DECIMAL(20, 2),
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        FOREIGN KEY (SOURCE_TERMINAL_ID) REFERENCES REF.TBL_SCM_TERMINAL (TERMINAL_ID),
        FOREIGN KEY (SOURCE_CHANNEL_ID) REFERENCES REF.TBL_SCM_CHANNEL (CHANNEL_ID),
        FOREIGN KEY (SOURCE_SERVICE_ID) REFERENCES REF.TBL_SCM_SERVICE (SERVICE_ID),
        PRIMARY KEY (AUTHORITY_ID)
)
INSERT INTO "REF".TBL_SCM_AUTHORITY
(AUTHORITY_ID, AUTHORITY_TYPE_CODE, SOURCE_TERMINAL_ID, SOURCE_CHANNEL_ID, SOURCE_SERVICE_ID, SOURCE_AUTHENTICATION_METHOD_CODE, SOURCE_CONDITION, SOURCE_USER_ID, SOURCE_MEMBERSHIP_ID, TARGET_WITHDRAW_DURATION_TYPE_CODE, TARGET_WITHDRAW_DURATION, TARGET_WITHDRAW_MIN_AMOUNT, TARGET_WITHDRAW_MAX_AMOUNT, CREATOR, LAST_EDITOR)
VALUES('8d230ef3-4a9c-4a3a-a8e4-0d8e0a8712c7', 2, 'a45687d9-71b7-4e7c-a97f-2e9c8a1d6efc', null, null, null, null, null, null, 1, 1, 0, 1000000000, 'Reza Jamshidi', 'Reza Jamshidi');


CREATE TABLE REF.TBL_SCM_TRANSFORMER (
        TRANSFORMER_ID VARCHAR(36) NOT NULL,
        TITLE VARCHAR(255),
        METADATA VARCHAR(1000),
        JAVA_CLASS_NAME VARCHAR(255),
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        PRIMARY KEY (TRANSFORMER_ID)
)
INSERT INTO "REF".TBL_SCM_TRANSFORMER
(TRANSFORMER_ID, TITLE, JAVA_CLASS_NAME, CREATOR, LAST_EDITOR)
VALUES('8f71b0f1-4b53-4c81-a40d-88e6cc53a3a7', 'ایجاد بدنه خالی', 'bean:emptyTransformer', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TRANSFORMER
(TRANSFORMER_ID, TITLE, JAVA_CLASS_NAME, CREATOR, LAST_EDITOR)
VALUES('d6b1a874-2c7c-4932-a6fc-9a7e1d038b03', 'پویا', 'bean:dynamicTransformer', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TRANSFORMER
(TRANSFORMER_ID, TITLE, JAVA_CLASS_NAME, CREATOR, LAST_EDITOR)
VALUES('675e0d37-af60-4f0c-88e7-5a499b20f3ac', 'ریکوئست استعلام شبا', 'ir.daneshrefah.scm.plugin.nab.transformer.IbanInqRequestTransformer', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TRANSFORMER
(TRANSFORMER_ID, TITLE, JAVA_CLASS_NAME, CREATOR, LAST_EDITOR)
VALUES('1f8e84e3-56a3-47f2-ba85-c2a285430824', 'ریسپانس استعلام شبا', 'bean:ibanInqResponseTransformer', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TRANSFORMER
(TRANSFORMER_ID, TITLE, JAVA_CLASS_NAME, CREATOR, LAST_EDITOR)
VALUES('c7943a8d-0db1-4851-951e-1d4a89439f5f', 'افزودن ویژگی', 'bean:appendPropTransformer', 'Reza Jamshidi', 'Reza Jamshidi');


CREATE TABLE REF.TBL_SCM_TRANSFORMER_RELATION (
        TRANSFORMER_RELATION_ID VARCHAR(36) NOT NULL,
        RELATION_TYPE_CODE INTEGER,
        ORDER SMALLINT,
        METADATA VARCHAR(1000),
        TRANSFORMER_ID VARCHAR(36),
        SOURCE_ID VARCHAR(36),
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        FOREIGN KEY (TRANSFORMER_ID) REFERENCES REF.TBL_SCM_TRANSFORMER (TRANSFORMER_ID),
        PRIMARY KEY (TRANSFORMER_RELATION_ID)
);
INSERT INTO "REF".TBL_SCM_TRANSFORMER_RELATION
(TRANSFORMER_RELATION_ID, RELATION_TYPE_CODE, "ORDER", TRANSFORMER_ID, SOURCE_ID, CREATOR, LAST_EDITOR)
VALUES('f28c1bf7-61ac-4d64-b65a-f7f154e394fc', 1, 1, '675e0d37-af60-4f0c-88e7-5a499b20f3ac', '864d62c0-725c-4da4-91e6-8627fc0971c8', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TRANSFORMER_RELATION
(TRANSFORMER_RELATION_ID, RELATION_TYPE_CODE, "ORDER", TRANSFORMER_ID, SOURCE_ID, CREATOR, LAST_EDITOR)
VALUES('aeb6f4e9-c188-4e42-8d8d-3d2f0b59e3e0', 2, 1, '1f8e84e3-56a3-47f2-ba85-c2a285430824', '864d62c0-725c-4da4-91e6-8627fc0971c8', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TRANSFORMER_RELATION
(TRANSFORMER_RELATION_ID, RELATION_TYPE_CODE, "ORDER", TRANSFORMER_ID, SOURCE_ID, CREATOR, LAST_EDITOR)
VALUES('5b8a22cc-6a7e-4e4c-9b62-9d3b8d011a35', 3, 1, '8f71b0f1-4b53-4c81-a40d-88e6cc53a3a7', '7d2e1a3b-e894-4ea3-b01a-685361fd75e5', 'Reza Jamshidi', 'Reza Jamshidi');
INSERT INTO "REF".TBL_SCM_TRANSFORMER_RELATION
(TRANSFORMER_RELATION_ID, RELATION_TYPE_CODE, "ORDER", "METADATA", TRANSFORMER_ID, SOURCE_ID, CREATOR, LAST_EDITOR)
VALUES('dbf21d25-9ff7-4e60-82b1-78e0d428db4a', 4, 1, '[{"sourceProp": "body", "targetProp": "iban"}]', 'c7943a8d-0db1-4851-951e-1d4a89439f5f', '7d2e1a3b-e894-4ea3-b01a-685361fd75e5', 'Reza Jamshidi', 'Reza Jamshidi');


-- ebb0b663-8ee2-4b22-9f1a-3d9f985d6a41

-- 14020424
CREATE TABLE REF.TBL_SCM_PROFILE (
        PROFILE_ID VARCHAR(36) NOT NULL,
        SERVICE_COMPONENT_PROVIDER_ID VARCHAR(36) NOT NULL,
        CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_EDIT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CREATOR VARCHAR(255),
        LAST_EDITOR VARCHAR(255),
        NAME VARCHAR(255),
        TITLE VARCHAR(255),
        PRIMARY KEY (PROFILE_ID)
)
INSERT INTO REF.TBL_SCM_PROFILE (PROFILE_ID, CREATOR, LAST_EDITOR, NAME, TITLE)
VALUES ('a9dcfd02e4fc4f7f92bce0c6a2e7f225', 'Reza Jamshidi', 'Reza Jamshidi', 'IB4DEV', 'اینترنت بانک توسعه');
INSERT INTO REF.TBL_SCM_PROFILE (PROFILE_ID, CREATOR, LAST_EDITOR, NAME, TITLE)
VALUES ('f3e0ebe042f244b09be0581ac05351d0', 'Reza Jamshidi', 'Reza Jamshidi', 'MB4DEV', 'موبایل بانک توسعه');

