plugins {
    id 'ir.daneshrefah.scm.java-library-conventions'
    id 'maven-publish'
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'ir.daneshrefah.scm.docs'
            artifactId = 'scm-docs-client'
            version = '1.0.0-SNAPSHOT'

            from components.java
        }
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
