server:
  port: 8888
spring:
  application:
    name: scm-config-server
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      server:
        git:
          uri: /home/cheshmapoush.a@drp.local/Projects/scm/config-repo-server
          search-paths: '{application}'
          clone-on-start: true
          default-label: master
          basedir: /home/cheshmapoush.a@drp.local/Projects/scm/config-repo
        encrypt:
          enabled: true
        prefix: /config
scm:
  config:
    applications:
      scm: ib, mb, pwa
      uaa: dev, test, prod
    scm-user:
      name: scm
      pass: scm
    cfg-user:
      name: cfg
      pass: cfg
    opr-user:
      name: opr
      pass: opr
encrypt:
  key: "WW@MwjtA9znCPVMi"