plugins {
    id 'ir.daneshrefah.scm.java-library-conventions'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    compileOnly 'org.springframework.data:spring-data-jpa'
    compileOnly 'jakarta.persistence:jakarta.persistence-api'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    implementation 'org.mapstruct:mapstruct'
    annotationProcessor 'org.mapstruct:mapstruct-processor'
    compileOnly project(':scm-utils')
    compileOnly project(':scm-common')
}

