package ir.daneshrefah.scm.common.model.taskworkflow;

public enum TaskWorkflowStepType {
    START_PROCESS,
    TASK_COMPLETE,
    APPROVE_PROCESS,
    BUSINESS_OPERATION,
    COMPLETE_PROCESS,
    REJECT_PROCESS,
    GET_ALL_PROCESS,
    GET_ALL_TASK,
    GET_TASK,
    UPDATE_DESCRIPTION
//    FIND_PROCUREMENT_BY_ACCOUNT,
//    FIND_PROCUREMENT_BY_NATIONAL,
//    PROCUREMENT_STATEMENT_INQUIRY
}
