-------------------------------------------------------------------------------------------------------

CREATE TABLE REF.TBL_SNT_MESSAGE_TEMPLATE
(
    MESSAGE_TEMPLATE_ID    DECIMAL(22) GENERATED ALWAYS AS IDENTITY NOT NULL,
    CODE                   VARCHAR(255)                             NOT NULL, -- AUTHENTICATION, ACTIVATION, ...
    TITLE                  VARCHAR(255)                             NOT NULL,
    TEMPLATE_FORMAT        VARCHAR(255)                             NOT NULL, -- JSON, HTML, XML, PLAIN_TEXT, ...
    BODY                   VARCHAR(255)                             NOT NULL,
    MAX_TRY_COUNT          INTEGER                                  NOT NULL DEFAULT 1,
    MAX_MINUTES_EXPIRATION INTEGER                                  NOT NULL DEFAULT 5,
    IS_SYSTEMIC            SMALLINT                                 NOT NULL DEFAULT 0,
    CREATOR                VARCHAR(255)                             NOT NULL,
    LAST_EDITOR            VARCHAR(255)                             NOT NULL,
    CREATE_DATE            TIMESTAMP                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_EDIT_DATE         TIMESTAMP                                NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MESSAGE_TEMPLATE_ID)
);
INSERT INTO ref.tbl_snt_message_template
(CODE,TITLE,TEMPLATE_FORMAT,BODY,MAX_TRY_COUNT,MAX_MINUTES_EXPIRATION,IS_SYSTEMIC,CREATOR,LAST_EDITOR)
VALUES ('authentication','ورود به سامانه','PLAIN_TEXT','سلام، خوش آمدید',1,0,1,'Reza Jamshidi','Reza Jamshidi')

---------------------------------------------------------------------------------------------------

-- CREATE TABLE REF.TBL_SNT_NOTIFICATION
-- (
--     NOTIFICATION_ID     DECIMAL(22) GENERATED ALWAYS AS IDENTITY,
--     MEDIA               VARCHAR(255)  NOT NULL, -- SMS, EMAIL, FAX
--     PAYLOAD             VARCHAR(2500) NOT NULL,
--     RECIPIENT           VARCHAR(255)  NOT NULL,
--     STATUS              VARCHAR(255)  NOT NULL,
--     TRY_COUNT           SMALLINT      NOT NULL DEFAULT 0,
--     EXPIRATION          TIMESTAMP,
--     RECIPIENT_USERNAME  VARCHAR(255),
--     REQUEST_DATA        VARCHAR(500)  NOT NULL,
--     MESSAGE_TEMPLATE_ID DECIMAL(22)   NOT NULL,
--     ISSUER_NICKNAME     VARCHAR(255)  NOT NULL,
--     ISSUER_TERMINAL_ID  VARCHAR(36)   NOT NULL,
--     CREATOR             VARCHAR(255)  NOT NULL,
--     LAST_EDITOR         VARCHAR(255)  NOT NULL,
--     CREATE_DATE         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     LAST_EDIT_DATE      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (MESSAGE_TEMPLATE_ID) REFERENCES REF.TBL_SNT_MESSAGE_TEMPLATE (MESSAGE_TEMPLATE_ID),
--     FOREIGN KEY (ISSUER_TERMINAL_ID) REFERENCES REF.TBL_SCM_TERMINAL (TERMINAL_ID),
--     CONSTRAINT PK_TBL_SNT_NOTIFICATION PRIMARY KEY (NOTIFICATION_ID)
-- );
--
-- CREATE TABLE REF.TBL_SNT_NOTIFICATION_LOG
-- (
--     NOTIFICATION_LOG_ID DECIMAL(22) GENERATED ALWAYS AS IDENTITY,
--     NOTIFICATION_ID     DECIMAL(22)  NOT NULL,
--     OLD_STATUS          VARCHAR(255) NOT NULL,
--     NEW_STATUS          VARCHAR(255) NOT NULL,
--     LOG_USER            VARCHAR(255) NOT NULL,
--     LOG_DATE            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (NOTIFICATION_ID) REFERENCES REF.TBL_SNT_NOTIFICATION (NOTIFICATION_ID),
--     CONSTRAINT PK_TBL_SNT_NOTIFICATION_LOG PRIMARY KEY (NOTIFICATION_LOG_ID)
-- );