plugins {
    id 'ir.daneshrefah.scm.java-library-conventions'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencies {
    compileOnly 'jakarta.persistence:jakarta.persistence-api'
    implementation "org.quartz-scheduler:quartz"
    compileOnly project(':scm-common')
    compileOnly project(':scm-common-data')
}