---
# Source: scm-ui/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scm-ui-service-account
  labels:
    app.kubernetes.io/name: scm-ui
automountServiceAccountToken: true
---
# Source: scm-ui/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: scm-ui
  labels:
    app.kubernetes.io/name: scm-ui
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: http
      protocol: TCP
      name: http
  externalIPs:
    - 10.10.4.128
  selector:
    app.kubernetes.io/name: scm-ui
---
# Source: scm-ui/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scm-ui
  labels:
    app.kubernetes.io/name: scm-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scm-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scm-ui
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: scm-ui-service-account
      securityContext:
        {}
      containers:
        - name: scm-ui
          securityContext:
            {}
          image: "reg.daneshrefah.ir/modern-banking/scm-app:8.2.0-b0313T1700"
          imagePullPolicy: IfNotPresent
          env:
            - name: JDWP_OPTS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            - name: SPRING_PROFILES_ACTIVE
              value: scm4test
            - name: SPRING_APPLICATION_NAME
              value: scm-web
            - name: VERSION
              value: 8.2.0
            - name: SERVER_PORT
              value: "8086"
            - name: SPRING_CLOUD_CONFIG_URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CLOUD_CONFIG_URI
                  name: scm-config-configmap
            - name: SPRING_SECURITY_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SECURITY_ISSUER_URI
                  name: scm-uaa-configmap
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          resources:
            {}
          volumeMounts:
            - mountPath: /mnt/log
              name: log-volume
      volumes:
        - hostPath:
            path: /log
            type: DirectoryOrCreate
          name: log-volume
      nodeSelector:
        app: scm-ui
      tolerations:
        - effect: NoSchedule
          key: daneshrefah.ir/group
          operator: Equal
          value: scm
