---
# Source: scm-web/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scm-web-service-account
  labels:
    app.kubernetes.io/name: scm-web
automountServiceAccountToken: true
---
# Source: scm-web/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: scm-web
  labels:
    app.kubernetes.io/name: scm-web
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: http
      protocol: TCP
      name: http
  externalIPs:
    - 10.10.4.127
  selector:
    app.kubernetes.io/name: scm-web
---
# Source: scm-web/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scm-web
  labels:
    app.kubernetes.io/name: scm-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scm-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scm-web
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: scm-web-service-account
      securityContext:
        {}
      containers:
        - name: scm-web
          securityContext:
            {}
          image: "reg.daneshrefah.ir/modern-banking/scm-app:8.3.0-b0513T1800"
          imagePullPolicy: IfNotPresent
          env:
            - name: JDWP_OPTS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            - name: SPRING_PROFILES_ACTIVE
              value: ib4test
            - name: SPRING_APPLICATION_NAME
              value: scm-web
            - name: VERSION
              value: 8.3.0
            - name: SERVER_PORT
              value: "8086"
            - name: SPRING_CLOUD_CONFIG_URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CLOUD_CONFIG_URI
                  name: scm-config-configmap
            - name: SPRING_SECURITY_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SECURITY_ISSUER_URI
                  name: scm-uaa-configmap
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          resources:
            {}
          volumeMounts:
            - mountPath: /mnt/log
              name: log-volume
      volumes:
        - hostPath:
            path: /log
            type: DirectoryOrCreate
          name: log-volume
      nodeSelector:
        app: scm-web
      tolerations:
        - effect: NoSchedule
          key: daneshrefah.ir/group
          operator: Equal
          value: scm
