---
# Source: scm-web/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scm-web-service-account
  labels:
    helm.sh/chart: scm-web-0.1.0
    app.kubernetes.io/name: scm-web
    app.kubernetes.io/instance: scm-web
    app.kubernetes.io/version: "8.2.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: scm-web/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
#  name: scm-web
  name: scm-ui #-> for scm-ui
  labels:
    helm.sh/chart: scm-web-0.1.0
    app.kubernetes.io/name: scm-web
    app.kubernetes.io/instance: scm-web
    app.kubernetes.io/version: "8.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
#    - port: 8082
    - port: 8083 #-> for scm-ui
      targetPort: http
      protocol: TCP
      name: http
  externalIPs:
#    - 10.10.4.127
    - 10.10.4.128 #-> for scm-ui
  selector:
    app.kubernetes.io/name: scm-web
    app.kubernetes.io/instance: scm-web
---
# Source: scm-web/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
#  name: scm-web
  name: scm-ui #-> for scm-ui
  labels:
    helm.sh/chart: scm-web-0.1.0
    app.kubernetes.io/name: scm-web
    app.kubernetes.io/instance: scm-web
    app.kubernetes.io/version: "8.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: scm-web
      app.kubernetes.io/instance: scm-web
  template:
    metadata:
      labels:
        helm.sh/chart: scm-web-0.1.0
        app.kubernetes.io/name: scm-web
        app.kubernetes.io/instance: scm-web
        app.kubernetes.io/version: "8.2.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: scm-web-service-account
      securityContext:
        {}
      containers:
#        - name: scm-web
        - name: scm-ui #-> for scm-ui
          securityContext:
            {}
          image: "reg.daneshrefah.ir/modern-banking/scm-app:8.2.0-b0223T1630"
          imagePullPolicy: IfNotPresent
          env:
            - name: JDWP_OPTS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            - name: SPRING_PROFILES_ACTIVE
#              value: ib4test
              value: scm4test #-> for scm-ui
            - name: SPRING_APPLICATION_NAME
              value: scm-web
            - name: VERSION
              value: 8.2.0
            - name: SERVER_PORT
              value: "8086"
            - name: SPRING_CLOUD_CONFIG_URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CLOUD_CONFIG_URI
                  name: scm-config-configmap
            - name: SPRING_SECURITY_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SECURITY_ISSUER_URI
                  name: scm-uaa-configmap
          ports:
            - name: http
#              containerPort: 8082
              containerPort: 8083 #-> for scm-ui
              protocol: TCP




          resources:
            {}
          volumeMounts:
            - mountPath: /mnt/log
              name: log-volume
      volumes:
        - hostPath:
            path: /log
            type: DirectoryOrCreate
          name: log-volume
      nodeSelector:
        daneshrefah.ir/app: scm-ui

      dnsPolicy: "ClusterFirst"
      dnsConfig:
        nameservers:
          - 10.15.131.28
          - 10.96.0.10
        searches:
          - scm.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "5"
