---
# Source: scm-uaa/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-scm-uaa
  labels:
    helm.sh/chart: scm-uaa-0.1.0
    app.kubernetes.io/name: scm-uaa
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: scm-uaa
    app.kubernetes.io/instance: test
---
# Source: scm-uaa/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-scm-uaa
  labels:
    helm.sh/chart: scm-uaa-0.1.0
    app.kubernetes.io/name: scm-uaa
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: scm-uaa
      app.kubernetes.io/instance: test
  template:
    metadata:
      labels:
        helm.sh/chart: scm-uaa-0.1.0
        app.kubernetes.io/name: scm-uaa
        app.kubernetes.io/instance: test
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: scm-uaa
          securityContext:
            {}
          image: "nginx:0.1.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /public/token
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /public/token
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3
          resources:
            {}
          volumeMounts:
            - mountPath: /mnt/log
              name: log-hostpath-volume
      volumes:
        - hostPath:
            path: /log
            type: DirectoryOrCreate
          name: log-hostpath-volume
---
# Source: scm-uaa/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-scm-uaa
  labels:
    helm.sh/chart: scm-uaa-0.1.0
    app.kubernetes.io/name: scm-uaa
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: nginx
  rules:
    - host: "scm-uaa.daneshrefah.ir"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-scm-uaa
                port:
                  number: 8000
