spring:
  datasource:
    url: jdbc:db2://10.10.4.104:50001/DBREFSW
    username: db2inst1
    password: db2inst1
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    hikari:
      maximum-pool-size: 10
      schema: REF
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

  logging:
    config: logback-spring.xml
    level:
      root: INFO
      ir.daneshrefah: DEBUG # Set the logging level for your package
    file:
      path: /logserver # Specify the directory path for logs
      name: log-server.log
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" # Define the log pattern


---

ibm:
  mq:
    queue-manager: CSQ1
    channel: DEV.ADMIN.SVRCONN
    conn-name: 10.10.4.238(11414)
    user: admin
    password: passw0rd

server:
  port: 9090

scm:
  mq:
    concurrency: 10
    destination: SCM2LOG
    enabled: true