plugins {
    id 'ir.daneshrefah.scm.java-library-conventions'
    id 'maven-publish'
    id 'java'
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'ir.daneshrefah.scm.uaa'
            artifactId = 'scm-uaa-client'
            version = '1.0.0-SNAPSHOT'

            from components.java
        }
    }
}

dependencies {
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    api 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    api project(':scm-uaa-common')
    api project(':scm-cache-client')
    api project(':scm-utils')
}
