plugins {
    id 'ir.daneshrefah.scm.java-library-conventions'
    id 'maven-publish'
    id 'java'
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'ir.daneshrefah.scm.uaa'
            artifactId = 'scm-uaa-common'
            version = '1.0.0-SNAPSHOT'

            from components.java
        }
    }
}

dependencies {
    annotationProcessor 'org.projectlombok:lombok'
    compileOnly 'org.projectlombok:lombok'
    compileOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    compileOnly 'org.springframework.security:spring-security-core'
    compileOnly 'org.springframework.security:spring-security-web'
    compileOnly 'org.springframework.security:spring-security-oauth2-core'
    compileOnly 'org.springframework.security:spring-security-oauth2-jose'
    api 'com.oopsguy.kaptcha:kaptcha-spring-boot-starter:1.0.0-beta-2'
//    implementation 'com.github.penggle:kaptcha:2.3.2'
//    implementation 'net.logicsquad:nanocaptcha:2.1'
    api project(':scm-common')
    api project(':scm-common-data')
    api project(':scm-utils')
    api project(':scm-cache-client')
    api 'com.ibm.mq:com.ibm.mq.allclient:9.4.1.0'
    api 'com.ibm.mq:com.ibm.mq.jakarta.client:9.4.1.0'
    api 'org.springframework:spring-jms'
}
